/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 349433ba-3916-4e93-9645-d242cbfa2934

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of "Statistical inference on black-box generative models in the data kernel perspective space" (Helm et al., 2025).

This module defines the abstract setting for DKPS estimation and proves the main theoretical results:
1. `risk_converges_fixed_n` (Theorem 1): Convergence of risk using estimated embeddings to risk using true embeddings for fixed sample size n.
2. `consistency_transfer_dkps` (Theorem 2): Consistency of the learning rule transfers from true embeddings to estimated embeddings, given an appropriate schedule of estimation budgets.
3. `diagonal_convergence`: A diagonal sequence lemma used to prove Theorem 2.

Notation mapping:
- ψ (true embeddings) : `psi_true` (or implicit in `risk`)
- ψ̂ (estimated embeddings) : `psi_hat`
- ℓ (loss) : `loss`
- h (learning rule) : `learn`
- Rℓ (risk) : `risk` (true), `risk_est` (estimated)
- Alignment consistency (Eq 3) : `DKPSAlignmentConsistency`

Assumptions A1-A4 from the paper are formalized as:
- A1: `InvariantToAffineIsometries`
- A2: `ContinuousLearningRule`
- A3: `BoundedLearningRule`
- A4: `ContinuousLoss` + `BoundedLabelSupport`

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

-- set_option maxHeartbeats 0
-- set_option maxRecDepth 4000
-- set_option synthInstance.maxHeartbeats 20000
-- set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Helm2025
namespace DKPS

/-!
# DKPS (Helm et al., 2025) — paper-oriented formalization

This file is intended to be readable alongside the paper
"Statistical inference on black-box generative models in the data kernel perspective space"
(Helm et al., 2025).

Design goals:
* keep the *mathematical objects* and *assumptions* named and ordered like the paper;
* provide small wrapper definitions (`Rℓ`, `Rhatℓ`, `TrainingSet`, …) so statements read like the paper;
* keep the existing proof development (which compiles in the checkpoint) mostly intact.

Notation mapping (paper → Lean):
* embedding space `ℝ^d`                      → `E d`
* label space `ℝ^{d'}`                        → `Y d'`
* training set `T_n = {(ψ_i,y_i)}_{i=1}^n`     → `Fin n → E d × Y d'`
* decision rule `h(·;T_n)`                     → `learn t : E d → Y d'`
* loss `ℓ : 𝒴×𝒴 → ℝ`                          → `LossFunction d'`
* risk `R_ℓ(P_{ψY}, h(·;T_n))`                 → `Rℓ n d d' P learn loss`
* estimated risk `R_ℓ(P_{ψY}, ĥ(·; T̂_n))`      → `Rhatℓ n d d' P learn loss psi_hat`
* alignment consistency (Eq. (3))              → `DKPSAlignmentConsistency`
* Theorem 1                                    → `risk_converges_fixed_n` (and wrapper `Theorem1` below)
* Theorem 2                                    → `consistency_transfer_dkps(_bayes)` (and wrapper `Theorem2` below)
-/


/-
Definitions of the DKPS setting: Euclidean spaces for embeddings and labels, LearningRule type, LossFunction type, risk functional, and a helper to transform training data.
-/
open MeasureTheory Filter Topology Metric
open scoped BigOperators

variable {d d' : ℕ}

-- Paper objects:
-- True (population) model proxy embeddings: ψ_i ∈ ℝ^d.
-- Labels/covariates: y_i ∈ ℝ^{d'} (could be ℝ, {0,1}, etc).
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)
abbrev Y (d' : ℕ) := EuclideanSpace ℝ (Fin d')

-- A learning algorithm / decision rule: h, which predicts y for a new ψ using the training set.
-- learn : (Fin n → (E × Y)) → E → Y
def LearningRule (n : ℕ) (d d' : ℕ) := (Fin n → E d × Y d') → E d → Y d'

-- Loss ℓ : Y × Y → ℝ≥0.
def LossFunction (d' : ℕ) := Y d' → Y d' → ℝ

-- Risk (expected loss) under the distribution P_{ψY}:
-- Rℓ(P_{ψY}, h(·;T_n)) = E[ ℓ( h(ψ_{n+1}; T_n), y_{n+1} ) ]
-- where (ψ_i, y_i) are i.i.d. from P_{ψY} for i=1..n+1.

variable {n : ℕ}

/--
The risk of a learning rule `learn` under distribution `P` with loss `loss`.
We integrate over the product measure of `n+1` samples.
The first `n` samples are the training set, the `n+1`-th is the test point.
-/
def risk (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => ω (Fin.castSucc i)) (ω (Fin.last n)).1) (ω (Fin.last n)).2 ∂P_prod

/--
Helper to transform the training set by applying an affine isometry to the embeddings.
-/
def transform_training (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') : Fin n → E d × Y d' :=
  fun i => (e (t i).1, (t i).2)

/-
Definition of risk_est, the risk using estimated embeddings.
-/
/--
The risk of a learning rule `learn` using estimated embeddings `psi_hat`.
`psi_hat` takes the full sample `ω` (training + test) and returns estimated embeddings for all points.
The learning rule is trained on `(psi_hat_train, y_train)` and evaluated on `psi_hat_test`.
The loss is computed against the true label `y_test`.
-/
def risk_est (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => (psi_hat ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat ω (Fin.last n))) (ω (Fin.last n)).2 ∂P_prod


/-! ## Paper-oriented helper types and notation -/

/-- Sample space for a single (embedding,label) pair. -/
abbrev Z (d d' : ℕ) := E d × Y d'

/-- Training set `T_n` (paper): `n` labeled embeddings. -/
abbrev TrainingSet (n : ℕ) (d d' : ℕ) := Fin n → Z d d'

/-- A full sample of size `n+1` (training + test). -/
abbrev Sample (n : ℕ) (d d' : ℕ) := Fin (n + 1) → Z d d'

/-- A decision function (paper): `h : ℝ^d → ℝ^{d'}`. -/
abbrev DecisionFn (d d' : ℕ) := E d → Y d'

/-- Extract the training set from an `(n+1)`-sample. -/
def sample_train {n d d' : ℕ} (ω : Sample n d d') : TrainingSet n d d' :=
  fun i => ω (Fin.castSucc i)

/-- Extract the test point from an `(n+1)`-sample. -/
def sample_test {n d d' : ℕ} (ω : Sample n d d') : Z d d' :=
  ω (Fin.last n)

/-- Paper risk notation `R_ℓ(P_{ψY}, h(·;T_n))` (wrapper around `risk`). -/
def Rℓ (n d d' : ℕ) (P : Measure (Z d d')) (learn : LearningRule n d d') (loss : LossFunction d') : ℝ :=
  risk n d d' P learn loss

/-- Paper estimated-risk notation (wrapper around `risk_est`). -/
def Rhatℓ (n d d' : ℕ) (P : Measure (Z d d')) (learn : LearningRule n d d') (loss : LossFunction d')
    (psi_hat : (Sample n d d') → Fin (n + 1) → E d) : ℝ :=
  risk_est n d d' P learn loss psi_hat

/-!
### About estimation budgets `m,r` (paper) vs. indices in Lean

The paper indexes embedding estimators by two budgets (written `m` and `r`) and takes limits
`m,r → ∞`.  In this development we typically index the estimators by a single natural `u : ℕ`
representing a *joint* budget schedule, and take `u → ∞`.  When you want to match the paper
literally, interpret `u` as an encoding of a cofinal schedule `(m(u), r(u))`.
-/

/-
Assumption A1: The learning rule is invariant to affine isometries.
-/
/--
Assumption A1: The learning rule is invariant to affine isometries.
For any affine isometry `e`, applying `e` to the training embeddings and the test embedding
does not change the prediction.
-/
def InvariantToAffineIsometries (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∀ (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') (ψ : E d),
    learn (transform_training e t) (e ψ) = learn t ψ

/-
Definitions of ContinuousLearningRule (A2), BoundedLearningRule (A3), ContinuousLoss (A4), and ConvergesInProbabilityToZero.
-/
/--
Assumption A2: The learning rule is continuous.
We assume standard continuity with respect to the product topology on inputs.
-/
def ContinuousLearningRule (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  Continuous (fun (p : (Fin n → E d × Y d') × E d) => learn p.1 p.2)

/--
Assumption A3: The learning rule has bounded range.
Specifically, the image of the learning rule is contained in a compact set.
-/
def BoundedLearningRule (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∃ K : Set (Y d'), IsCompact K ∧ ∀ (t : Fin n → E d × Y d') (ψ : E d), learn t ψ ∈ K

/--
Assumption A4: The loss function is continuous.
-/
def ContinuousLoss (d' : ℕ) (loss : LossFunction d') : Prop :=
  Continuous (fun (p : Y d' × Y d') => loss p.1 p.2)

/--
Convergence in probability to zero for a sequence of random variables `X_u`.
`∀ ε > 0, P(‖X_u‖ > ε) → 0` as `u → ∞`.
-/
def ConvergesInProbabilityToZero {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : ℕ → Ω → ℝ) : Prop :=
  ∀ ε > 0, Tendsto (fun u => P {ω | |X u ω| > ε}) atTop (𝓝 0)

/-
Assumption: DKPS alignment consistency. There exists a sequence of affine isometries such that the estimated embeddings converge to the transformed true embeddings in probability.
-/
/--
Assumption: DKPS alignment consistency.
There exists a sequence of affine isometries `e_u` such that the estimated embeddings `psi_hat`
converge to `e_u(psi_true)` uniformly over the training and test set, in probability.
-/
def DKPSAlignmentConsistency (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : Prop :=
  ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) (e u (ω i).1))


end DKPS
end Helm2025
