/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 349433ba-3916-4e93-9645-d242cbfa2934

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of "Statistical inference on black-box generative models in the data kernel perspective space" (Helm et al., 2025).

This module defines the abstract setting for DKPS estimation and proves the main theoretical results:
1. `risk_converges_fixed_n` (Theorem 1): Convergence of risk using estimated embeddings to risk using true embeddings for fixed sample size n.
2. `consistency_transfer_dkps` (Theorem 2): Consistency of the learning rule transfers from true embeddings to estimated embeddings, given an appropriate schedule of estimation budgets.
3. `diagonal_convergence`: A diagonal sequence lemma used to prove Theorem 2.

Notation mapping:
- ψ (true embeddings) : `psi_true` (or implicit in `risk`)
- ψ̂ (estimated embeddings) : `psi_hat`
- ℓ (loss) : `loss`
- h (learning rule) : `learn`
- Rℓ (risk) : `risk` (true), `risk_est` (estimated)
- Alignment consistency (Eq 3) : `DKPSAlignmentConsistency`

Assumptions A1-A4 from the paper are formalized as:
- A1: `InvariantToAffineIsometries`
- A2: `ContinuousLearningRule`
- A3: `BoundedLearningRule`
- A4: `ContinuousLoss` + `BoundedLabelSupport`

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

-- set_option maxHeartbeats 0
-- set_option maxRecDepth 4000
-- set_option synthInstance.maxHeartbeats 20000
-- set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Helm2025
namespace DKPS

/-!
# DKPS (Helm et al., 2025) — paper-oriented formalization

This file is intended to be readable alongside the paper
"Statistical inference on black-box generative models in the data kernel perspective space"
(Helm et al., 2025).

Design goals:
* keep the *mathematical objects* and *assumptions* named and ordered like the paper;
* provide small wrapper definitions (`Rℓ`, `Rhatℓ`, `TrainingSet`, …) so statements read like the paper;
* keep the existing proof development (which compiles in the checkpoint) mostly intact.

Notation mapping (paper → Lean):
* embedding space `ℝ^d`                      → `E d`
* label space `ℝ^{d'}`                        → `Y d'`
* training set `T_n = {(ψ_i,y_i)}_{i=1}^n`     → `Fin n → E d × Y d'`
* decision rule `h(·;T_n)`                     → `learn t : E d → Y d'`
* loss `ℓ : 𝒴×𝒴 → ℝ`                          → `LossFunction d'`
* risk `R_ℓ(P_{ψY}, h(·;T_n))`                 → `Rℓ n d d' P learn loss`
* estimated risk `R_ℓ(P_{ψY}, ĥ(·; T̂_n))`      → `Rhatℓ n d d' P learn loss psi_hat`
* alignment consistency (Eq. (3))              → `DKPSAlignmentConsistency`
* Theorem 1                                    → `risk_converges_fixed_n` (and wrapper `Theorem1` below)
* Theorem 2                                    → `consistency_transfer_dkps(_bayes)` (and wrapper `Theorem2` below)
-/


/-
Definitions of the DKPS setting: Euclidean spaces for embeddings and labels, LearningRule type, LossFunction type, risk functional, and a helper to transform training data.
-/
open MeasureTheory Filter Topology Metric
open scoped BigOperators

variable {d d' : ℕ}

-- Paper objects:
-- True (population) model proxy embeddings: ψ_i ∈ ℝ^d.
-- Labels/covariates: y_i ∈ ℝ^{d'} (could be ℝ, {0,1}, etc).
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)
abbrev Y (d' : ℕ) := EuclideanSpace ℝ (Fin d')

-- A learning algorithm / decision rule: h, which predicts y for a new ψ using the training set.
-- learn : (Fin n → (E × Y)) → E → Y
def LearningRule (n : ℕ) (d d' : ℕ) := (Fin n → E d × Y d') → E d → Y d'

-- Loss ℓ : Y × Y → ℝ≥0.
def LossFunction (d' : ℕ) := Y d' → Y d' → ℝ

-- Risk (expected loss) under the distribution P_{ψY}:
-- Rℓ(P_{ψY}, h(·;T_n)) = E[ ℓ( h(ψ_{n+1}; T_n), y_{n+1} ) ]
-- where (ψ_i, y_i) are i.i.d. from P_{ψY} for i=1..n+1.

variable {n : ℕ}

/--
The risk of a learning rule `learn` under distribution `P` with loss `loss`.
We integrate over the product measure of `n+1` samples.
The first `n` samples are the training set, the `n+1`-th is the test point.
-/
def risk (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => ω (Fin.castSucc i)) (ω (Fin.last n)).1) (ω (Fin.last n)).2 ∂P_prod

/--
Helper to transform the training set by applying an affine isometry to the embeddings.
-/
def transform_training (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') : Fin n → E d × Y d' :=
  fun i => (e (t i).1, (t i).2)

/-
Definition of risk_est, the risk using estimated embeddings.
-/
/--
The risk of a learning rule `learn` using estimated embeddings `psi_hat`.
`psi_hat` takes the full sample `ω` (training + test) and returns estimated embeddings for all points.
The learning rule is trained on `(psi_hat_train, y_train)` and evaluated on `psi_hat_test`.
The loss is computed against the true label `y_test`.
-/
def risk_est (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => (psi_hat ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat ω (Fin.last n))) (ω (Fin.last n)).2 ∂P_prod


/-! ## Paper-oriented helper types and notation -/

/-- Sample space for a single (embedding,label) pair. -/
abbrev Z (d d' : ℕ) := E d × Y d'

/-- Training set `T_n` (paper): `n` labeled embeddings. -/
abbrev TrainingSet (n : ℕ) (d d' : ℕ) := Fin n → Z d d'

/-- A full sample of size `n+1` (training + test). -/
abbrev Sample (n : ℕ) (d d' : ℕ) := Fin (n + 1) → Z d d'

/-- A decision function (paper): `h : ℝ^d → ℝ^{d'}`. -/
abbrev DecisionFn (d d' : ℕ) := E d → Y d'

/-- Extract the training set from an `(n+1)`-sample. -/
def sample_train {n d d' : ℕ} (ω : Sample n d d') : TrainingSet n d d' :=
  fun i => ω (Fin.castSucc i)

/-- Extract the test point from an `(n+1)`-sample. -/
def sample_test {n d d' : ℕ} (ω : Sample n d d') : Z d d' :=
  ω (Fin.last n)

/-- Paper risk notation `R_ℓ(P_{ψY}, h(·;T_n))` (wrapper around `risk`). -/
def Rℓ (n d d' : ℕ) (P : Measure (Z d d')) (learn : LearningRule n d d') (loss : LossFunction d') : ℝ :=
  risk n d d' P learn loss

/-- Paper estimated-risk notation (wrapper around `risk_est`). -/
def Rhatℓ (n d d' : ℕ) (P : Measure (Z d d')) (learn : LearningRule n d d') (loss : LossFunction d')
    (psi_hat : (Sample n d d') → Fin (n + 1) → E d) : ℝ :=
  risk_est n d d' P learn loss psi_hat

/-!
### About estimation budgets `m,r` (paper) vs. indices in Lean

The paper indexes embedding estimators by two budgets (written `m` and `r`) and takes limits
`m,r → ∞`.  In this development we typically index the estimators by a single natural `u : ℕ`
representing a *joint* budget schedule, and take `u → ∞`.  When you want to match the paper
literally, interpret `u` as an encoding of a cofinal schedule `(m(u), r(u))`.
-/

/-
Assumption A1: The learning rule is invariant to affine isometries.
-/
/--
Assumption A1: The learning rule is invariant to affine isometries.
For any affine isometry `e`, applying `e` to the training embeddings and the test embedding
does not change the prediction.
-/
def InvariantToAffineIsometries (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∀ (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') (ψ : E d),
    learn (transform_training e t) (e ψ) = learn t ψ

/-
Definitions of ContinuousLearningRule (A2), BoundedLearningRule (A3), ContinuousLoss (A4), and ConvergesInProbabilityToZero.
-/
/--
Assumption A2: The learning rule is continuous.
We assume standard continuity with respect to the product topology on inputs.
-/
def ContinuousLearningRule (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  Continuous (fun (p : (Fin n → E d × Y d') × E d) => learn p.1 p.2)

/--
Assumption A3: The learning rule has bounded range.
Specifically, the image of the learning rule is contained in a compact set.
-/
def BoundedLearningRule (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∃ K : Set (Y d'), IsCompact K ∧ ∀ (t : Fin n → E d × Y d') (ψ : E d), learn t ψ ∈ K

/--
Assumption A4: The loss function is continuous.
-/
def ContinuousLoss (d' : ℕ) (loss : LossFunction d') : Prop :=
  Continuous (fun (p : Y d' × Y d') => loss p.1 p.2)

/--
Convergence in probability to zero for a sequence of random variables `X_u`.
`∀ ε > 0, P(‖X_u‖ > ε) → 0` as `u → ∞`.
-/
def ConvergesInProbabilityToZero {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : ℕ → Ω → ℝ) : Prop :=
  ∀ ε > 0, Tendsto (fun u => P {ω | |X u ω| > ε}) atTop (𝓝 0)

/-
Assumption: DKPS alignment consistency. There exists a sequence of affine isometries such that the estimated embeddings converge to the transformed true embeddings in probability.
-/
/--
Assumption: DKPS alignment consistency.
There exists a sequence of affine isometries `e_u` such that the estimated embeddings `psi_hat`
converge to `e_u(psi_true)` uniformly over the training and test set, in probability.
-/
def DKPSAlignmentConsistency (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : Prop :=
  ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) (e u (ω i).1))

/-
Lemma: If a sequence of random variables converges in probability to zero and is uniformly bounded, then their expectations converge to zero.
-/
/--
Lemma: Convergence in probability to zero plus uniform boundedness implies convergence of expectations to zero.
-/
lemma expectation_converges_of_prob_converges_bounded {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X : ℕ → Ω → ℝ) (M : ℝ)
    (h_meas : ∀ u, Measurable (X u))
    (h_bound : ∀ u, ∀ᵐ ω ∂P, |X u ω| ≤ M)
    (h_conv : ConvergesInProbabilityToZero P X) :
    Tendsto (fun u => ∫ ω, |X u ω| ∂P) atTop (𝓝 0) := by
      -- By the dominated convergence theorem, it suffices to show that $|X_u|$ converges to $0$ in measure.
      have h_conv_in_measure : Filter.Tendsto (fun u => ∫ ω, |X u ω| ∂P) Filter.atTop (𝓝 0) := by
        have h_conv_in_measure_aux : ∀ ε > 0, ∃ N, ∀ u ≥ N, ∫ ω, |X u ω| ∂P ≤ ε + M * (P {ω | |X u ω| > ε}).toReal := by
          intro ε ε_pos
          have h_integral_le : ∀ u, ∫ ω, |X u ω| ∂P ≤ ∫ ω, ε + M * (if |X u ω| > ε then 1 else 0) ∂P := by
            intro u;
            refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
            · exact Filter.Eventually.of_forall fun ω => abs_nonneg _;
            · refine' MeasureTheory.Integrable.add _ _ <;> norm_num;
              refine' MeasureTheory.Integrable.indicator _ _;
              · norm_num;
              · exact measurableSet_lt measurable_const ( h_meas u |> Measurable.norm );
            · filter_upwards [ h_bound u ] with ω hω using by split_ifs <;> linarith;
          refine' ⟨ 0, fun u _ => le_trans ( h_integral_le u ) _ ⟩;
          rw [ MeasureTheory.integral_add, MeasureTheory.integral_const_mul ] <;> norm_num;
          · erw [ MeasureTheory.integral_indicator ( measurableSet_lt measurable_const ( h_meas u |> Measurable.norm ) ) ] ; aesop;
          · refine' MeasureTheory.Integrable.indicator _ _;
            · norm_num;
            · exact measurableSet_lt measurable_const ( h_meas u |> Measurable.norm )
        rw [ Metric.tendsto_nhds ];
        intro ε hε;
        obtain ⟨ N, hN ⟩ := h_conv_in_measure_aux ( ε / 2 ) ( half_pos hε );
        have := h_conv ( ε / 2 ) ( half_pos hε );
        rw [ ENNReal.tendsto_nhds_zero ] at this;
        filter_upwards [ this ( ENNReal.ofReal ( ε / ( 2 * ( |M| + 1 ) ) ) ) ( ENNReal.ofReal_pos.mpr ( div_pos hε ( by positivity ) ) ), Filter.Ici_mem_atTop N ] with u hu hu';
        rw [ ENNReal.le_ofReal_iff_toReal_le ] at hu <;> norm_num at *;
        · rw [ abs_of_nonneg ( MeasureTheory.integral_nonneg fun _ => abs_nonneg _ ) ];
          rw [ le_div_iff₀ ] at hu <;> cases abs_cases M <;> nlinarith [ hN u hu', show ( P { ω | ε / 2 < |X u ω| } |> ENNReal.toReal ) ≥ 0 by positivity ];
        · positivity;
      convert h_conv_in_measure using 1


/-
Lemma: Tightness of probability measures on second-countable locally compact spaces. For any epsilon > 0, there exists a compact set K such that the probability of Y not being in K is less than epsilon.
-/
/--
Lemma: Tightness of probability measures on second-countable locally compact spaces.
For any `ε > 0`, there exists a compact set `K` such that `P(Kᶜ) < ε`.
-/
lemma tightness_helper {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S : Type*} [MeasurableSpace S] [TopologicalSpace S] [BorelSpace S]
    [T2Space S] [LocallyCompactSpace S] [SecondCountableTopology S]
    (Y : Ω → S) (h_meas_Y : Measurable Y) :
    ∀ ε : ENNReal, 0 < ε → ∃ K : Set S, IsCompact K ∧ P {ω | Y ω ∉ K} < ε := by
  classical
  intro ε ε_pos

  -- pushforward
  let μ : Measure S := Measure.map Y P
  haveI : OpensMeasurableSpace S := by infer_instance
  haveI : IsFiniteMeasure μ := by infer_instance
  haveI : μ.InnerRegular := by infer_instance

  -- handle ε = ⊤ separately (then goal is trivial)
  by_cases htop : ε = ⊤
  · subst htop
    refine ⟨∅, isCompact_empty, ?_⟩
    -- P{ω | Y ω ∉ ∅} = P univ < ⊤
    -- and P univ ≠ ⊤ since P is finite (probability)
    simp [lt_top_iff_ne_top]

  -- tightness of {μ}
  have hT : IsTightMeasureSet ({μ} : Set (Measure S)) :=
    MeasureTheory.isTightMeasureSet_singleton_of_innerRegular (μ := μ)

  have hiff :=
    (MeasureTheory.isTightMeasureSet_iff_exists_isCompact_measure_compl_le
      (S := ({μ} : Set (Measure S))))

  -- positivity of ε/2 (uses your div_pos signature: a≠0 and b≠⊤)
  have half_pos : (0 : ENNReal) < ε / 2 := by
    refine ENNReal.div_pos (ne_of_gt ε_pos) ?_
    norm_num

  obtain ⟨K, hKc, hK⟩ := (hiff.mp hT) (ε / 2) half_pos
  have hμK : μ Kᶜ ≤ ε / 2 := by
    simpa using hK μ (by simp)

  refine ⟨K, hKc, ?_⟩

  have hKmeas : MeasurableSet K := hKc.measurableSet

  -- rewrite μ(Kᶜ) as P{ω | Y ω ∉ K}
  have h_event : μ (Kᶜ) = P (Y ⁻¹' K)ᶜ := by
    have hs : MeasurableSet (Kᶜ) := hKmeas.compl
    have hm : (Measure.map Y P) (Kᶜ) = P (Y ⁻¹' (Kᶜ)) :=
        MeasureTheory.Measure.map_apply (μ := P) (f := Y) h_meas_Y hs
    simpa [μ, Set.preimage_compl] using hm

  have h_le : P {ω | Y ω ∉ K} ≤ ε / 2 := by
    have hset : {ω | Y ω ∉ K} = (Y ⁻¹' K)ᶜ := by
        ext ω; rfl
    -- rewrite hμK using h_event
    have : P (Y ⁻¹' K)ᶜ ≤ ε / 2 := by
        simpa [h_event] using hμK
    simpa [hset] using this  -- prove ε/2 < ε (now we can use htop : ε ≠ ⊤)
  have hb0 : (2 : ENNReal) ≠ 0 := by norm_num
  have hbt : (2 : ENNReal) ≠ ⊤ := by norm_num

  have h_half_lt : ε / 2 < ε := by
    -- div_lt_iff: (c/b < a) ↔ (c < a*b)
    have hdiv :
        (ε / (2 : ENNReal) < ε) ↔ (ε < ε * (2 : ENNReal)) := by
      simpa using
        (ENNReal.div_lt_iff (a := ε) (b := (2 : ENNReal)) (c := ε)
          (h0 := Or.inl hb0) (ht := Or.inl hbt))
    -- show ε < ε*2 via mul strictness on the right
    have h1lt2 : (1 : ENNReal) < (2 : ENNReal) := by norm_num
    have hmul : ε * (1 : ENNReal) < ε * (2 : ENNReal) := by
      -- mul_lt_mul_right: multiply strict inequality on the right by ε
      -- signature in your build: mul_lt_mul_left / left' exist; right should exist per deprecation note.
      simpa [mul_assoc] using (ENNReal.mul_lt_mul_right (a := ε) (h0 := ne_of_gt ε_pos) (hinf := htop) h1lt2)
    have : ε < ε * (2 : ENNReal) := by simpa [mul_one] using hmul
    exact hdiv.mpr this

  -- finish: P(event) ≤ ε/2 < ε
  exact lt_of_le_of_lt h_le h_half_lt


/-
Lemma: If f is uniformly continuous on K with parameters delta and epsilon, then the probability that f(X) and f(Y) are more than epsilon apart is bounded by the probability that X and Y are more than delta apart plus the probability that Y is not in K.
-/
/--
Lemma: Probability bound from uniform continuity on a set.
If `f` maps `δ`-close points to `ε`-close points when the second point is in `K`,
then `P(dist (f X) (f Y) > ε) ≤ P(dist X Y ≥ δ) + P(Y ∉ K)`.
-/
lemma prob_bound_of_uniform_continuity {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω)
    {S S' : Type*} [PseudoMetricSpace S] [PseudoMetricSpace S']
    (X Y : Ω → S) (f : S → S') (K : Set S)
    (ε δ : ℝ)
    (h_unif : ∀ x y, y ∈ K → dist x y < δ → dist (f x) (f y) ≤ ε) :
    P {ω | dist (f (X ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X ω) (Y ω) ≥ δ} + P {ω | Y ω ∉ K} := by
      refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
      intro ω hω; contrapose! hω; aesop;

/-
Lemma: Continuous mapping theorem for convergence in probability. If X_u converges to Y in probability and f is continuous, then f(X_u) converges to f(Y) in probability.
-/
/--
Lemma: Continuous mapping theorem for convergence in probability.
If `X_u → Y` in probability and `f` is continuous, then `f(X_u) → f(Y)` in probability.
-/
lemma continuous_prob_convergence {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S S' : Type*}
    [PseudoMetricSpace S] [MeasurableSpace S] [OpensMeasurableSpace S] [SecondCountableTopology S]
    [T2Space S] [LocallyCompactSpace S] [BorelSpace S]
    [PseudoMetricSpace S'] [MeasurableSpace S'] [OpensMeasurableSpace S']
    (X : ℕ → Ω → S) (Y : Ω → S) (f : S → S')
    (_h_meas_X : ∀ u, Measurable (X u))
    (h_meas_Y : Measurable Y)
    (h_cont : Continuous f)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (Y ω))) :
    ConvergesInProbabilityToZero P (fun u ω => dist (f (X u ω)) (f (Y ω))) := by
      intro ε hε_pos
      have h_tight : ∀ η > 0, ∃ K : Set S, IsCompact K ∧ P {ω | Y ω∉K} < η := by
        exact fun η a ↦ tightness_helper P Y h_meas_Y η a;
      -- Since `f` is continuous and `K` is compact, `f` is uniformly continuous on `K`.
      have h_unif : ∀ K : Set S, IsCompact K → ∀ ε > 0, ∃ δ > 0, ∀ x y, y ∈ K → dist x y < δ → dist (f x) (f y) ≤ ε := by
        intro K hK ε hε_pos;
        have := hK.elim_nhds_subcover;
        -- By the definition of continuity at a point, for each $y \in K$, there exists $\delta_y > 0$ such that if $dist x y < \delta_y$, then $dist (f x) (f y) < \epsilon / 2$.
        have h_cont_at : ∀ y ∈ K, ∃ δ_y > 0, ∀ x, dist x y < δ_y → dist (f x) (f y) < ε / 2 := by
          exact fun y hy => Metric.continuous_iff.mp h_cont y ( ε / 2 ) ( half_pos hε_pos );
        choose! δ hδ_pos hδ using h_cont_at;
        obtain ⟨ t, ht₁, ht₂ ⟩ := this ( fun y => Metric.ball y ( δ y / 2 ) ) fun y hy => Metric.ball_mem_nhds _ ( half_pos ( hδ_pos y hy ) );
        -- Let $\delta = \min_{x \in t} \frac{\delta_x}{2}$.
        obtain ⟨δ_min, hδ_min_pos, hδ_min⟩ : ∃ δ_min > 0, ∀ x ∈ t, δ_min ≤ δ x / 2 := by
          by_cases ht_empty : t.Nonempty;
          · exact ⟨ Finset.min' ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩, by have := Finset.min'_mem ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩ ; aesop, fun x hx => Finset.min'_le _ _ ( Finset.mem_image_of_mem _ hx ) ⟩;
          · exact ⟨ 1, zero_lt_one, fun x hx => False.elim <| ht_empty ⟨ x, hx ⟩ ⟩;
        refine' ⟨ δ_min, hδ_min_pos, fun x y hy hxy => _ ⟩;
        obtain ⟨ z, hz₁, hz₂ ⟩ := Set.mem_iUnion₂.mp ( ht₂ hy );
        have := hδ z ( ht₁ z hz₁ ) x ?_;
        · have := hδ z ( ht₁ z hz₁ ) y ?_;
          · exact le_trans ( dist_triangle_right _ _ _ ) ( by linarith );
          · exact lt_of_lt_of_le hz₂ ( by linarith [ hδ_pos z ( ht₁ z hz₁ ) ] );
        · exact lt_of_le_of_lt ( dist_triangle _ _ _ ) ( by linarith [ hδ_min z hz₁, Metric.mem_ball.mp hz₂ ] );
      -- Fix `ε > 0`. By `tightness_helper`, for any `η > 0`, there exists a compact set `K` such that `P(Y ∉ K) < η`.
      have h_bound : ∀ η > 0, ∃ δ > 0, ∀ u, P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + η := by
        intro η hη_pos
        obtain ⟨K, hK_compact, hK_bound⟩ := h_tight η hη_pos
        obtain ⟨δ, hδ_pos, hδ_unif⟩ := h_unif K hK_compact ε hε_pos
        use δ, hδ_pos
        intro u
        have h_bound : P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + P {ω | Y ω∉K} := by
          refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
          intro ω hω; contrapose! hω; aesop;
        exact le_trans h_bound (add_le_add_right (le_of_lt hK_bound) _)
      -- By `h_conv`, for any `δ > 0`, `P(X u ω, Y ω) ≥ δ` tends to 0 as `u → ∞`.
      have h_conv_zero : ∀ δ > 0, Filter.Tendsto (fun u => P {ω | dist (X u ω) (Y ω) ≥ δ}) Filter.atTop (𝓝 0) := by
        intro δ hδ_pos
        have := h_conv δ hδ_pos
        simp_all +decide [ ConvergesInProbabilityToZero ];
        have := h_conv ( δ / 2 ) ( half_pos hδ_pos );
        rw [ ENNReal.tendsto_nhds_zero ] at *;
        exact fun ε ε_pos => by filter_upwards [ this ε ε_pos ] with u hu using le_trans ( MeasureTheory.measure_mono ( fun ω hω => by exact lt_of_lt_of_le ( half_lt_self hδ_pos ) hω.out ) ) hu;
      rw [ ENNReal.tendsto_nhds_zero ] at *;
      intro η hη_pos; rcases h_bound ( η / 2 ) ( ENNReal.half_pos hη_pos.ne' ) with ⟨ δ, δ_pos, hδ ⟩ ; filter_upwards [ h_conv_zero δ δ_pos |> fun h => h.eventually ( gt_mem_nhds <| ENNReal.half_pos hη_pos.ne' ) ] with u hu; simpa using le_trans ( hδ u ) ( add_le_add hu.le le_rfl ) |> le_trans <| by rw [ ENNReal.add_halves ] ;


/-
Lemma: If f is continuous and K is compact, then for any epsilon > 0, there exists delta > 0 such that if y is in K and x is within delta of y, then f(x) is within epsilon of f(y).
-/
/--
Lemma: A continuous function behaves uniformly continuously near a compact set.
If `f` is continuous and `K` is compact, then for any `ε > 0`, there exists `δ > 0`
such that for all `y ∈ K` and any `x`, `dist x y < δ → dist (f x) (f y) < ε`.
-/
lemma uniform_continuity_on_compact_approx {S S' : Type*}
    [PseudoMetricSpace S] [PseudoMetricSpace S']
    (f : S → S') (K : Set S) (h_cont : Continuous f) (h_compact : IsCompact K) :
    ∀ ε > 0, ∃ δ > 0, ∀ y ∈ K, ∀ x, dist x y < δ → dist (f x) (f y) < ε := by
      intro ε εpos;
      by_contra! h_contra;
      choose! y hy x hx using h_contra;
      -- Since $K$ is compact, the sequence $\{y_{1/n}\}$ has a convergent subsequence $\{y_{1/n_k}\}$ that converges to some $y \in K$.
      obtain ⟨y', hy', h_subseq⟩ : ∃ y' ∈ K, ∃ (nk : ℕ → ℕ), StrictMono nk ∧ Filter.Tendsto (fun k => y (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        have := h_compact.isSeqCompact fun n => hy ( 1 / ( n + 1 ) ) ( by positivity );
        tauto;
      -- Since $x_{1/n_k}$ converges to $y'$, we have $f(x_{1/n_k}) \to f(y')$ and $f(y_{1/n_k}) \to f(y')$.
      obtain ⟨nk, hnk_mono, hnk_conv⟩ := h_subseq;
      have hx_conv : Filter.Tendsto (fun k => x (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        have hx_conv : Filter.Tendsto (fun k => dist (x (1 / (nk k + 1)) (by positivity)) (y (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds 0) := by
          exact squeeze_zero ( fun _ => dist_nonneg ) ( fun k => le_of_lt ( hx _ ( by positivity ) |>.1 ) ) ( tendsto_one_div_add_atTop_nhds_zero_nat.comp hnk_mono.tendsto_atTop );
        -- show x_k → y' using dist(x_k,y_k) → 0 and y_k → y'
        refine Metric.tendsto_nhds.2 ?_
        intro ε εpos
        -- y_k → y' gives eventually dist(y_k,y') < ε/2
        have hy' : ∀ᶠ k in Filter.atTop,
            dist (y (1 / (nk k + 1)) (by positivity)) y' < ε / 2 := by
          have := (Metric.tendsto_nhds.1 hnk_conv) (ε / 2) (by linarith)
          simpa [Metric.ball, dist_comm] using this
        -- dist(x_k,y_k) → 0 gives eventually dist(x_k,y_k) < ε/2
        have hxy' : ∀ᶠ k in Filter.atTop,
            dist (x (1 / (nk k + 1)) (by positivity))
                 (y (1 / (nk k + 1)) (by positivity)) < ε / 2 := by
          -- your hx_conv was dist(...) → 0; unpack it
          have := (Metric.tendsto_nhds.1 hx_conv) (ε / 2) (by linarith)
          simpa [Metric.ball] using this
        -- combine via triangle inequality
        filter_upwards [hy', hxy'] with k hyk hxyk
        have : dist (x (1 / (nk k + 1)) (by positivity)) y' < ε := by
            -- triangle inequality
            have htri :
                dist (x (1 / (nk k + 1)) (by positivity)) y'
                    ≤ dist (x (1 / (nk k + 1)) (by positivity))
                            (y (1 / (nk k + 1)) (by positivity))
                    + dist (y (1 / (nk k + 1)) (by positivity)) y' :=
                dist_triangle _ _ _
            -- add the two strict bounds
            have hsum :
                dist (x (1 / (nk k + 1)) (by positivity))
                        (y (1 / (nk k + 1)) (by positivity))
                    + dist (y (1 / (nk k + 1)) (by positivity)) y' < ε := by
                have h := add_lt_add hxyk hyk   -- < ε/2 + ε/2
                -- turn ε/2 + ε/2 into ε
                -- (this is pure arithmetic, so nlinarith is safe here)
                have : (ε / 2 : ℝ) + (ε / 2) = ε := by nlinarith
                simpa [this, add_comm, add_left_comm, add_assoc] using h
            exact lt_of_le_of_lt htri hsum
        -- convert to membership in ball
        simpa [Metric.ball] using this

      have hy_conv : Filter.Tendsto (fun k => y (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        exact hnk_conv;
      have hf_conv : Filter.Tendsto (fun k => f (x (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds (f y')) := by
        exact h_cont.continuousAt.tendsto.comp hx_conv;
      have hf_conv' : Filter.Tendsto (fun k => f (y (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds (f y')) := by
        exact h_cont.continuousAt.tendsto.comp hy_conv;
      exact absurd ( le_of_tendsto_of_tendsto' tendsto_const_nhds ( Filter.Tendsto.dist hf_conv hf_conv' ) fun k => hx _ _ |>.2 ) ( by simp +decide [ εpos ] )

/-
Lemma: Continuous mapping theorem for convergence in probability. If X_u converges to Y in probability and f is continuous, then f(X_u) converges to f(Y) in probability.
-/
/--
Lemma: Continuous mapping theorem for convergence in probability.
If `X_u → Y` in probability and `f` is continuous, then `f(X_u) → f(Y)` in probability.
-/
lemma continuous_prob_convergence_lemma {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S S' : Type*}
    [PseudoMetricSpace S] [MeasurableSpace S] [OpensMeasurableSpace S] [SecondCountableTopology S]
    [T2Space S] [LocallyCompactSpace S] [BorelSpace S]
    [PseudoMetricSpace S'] [MeasurableSpace S'] [OpensMeasurableSpace S']
    (X : ℕ → Ω → S) (Y : Ω → S) (f : S → S')
    (_h_meas_X : ∀ u, Measurable (X u))
    (h_meas_Y : Measurable Y)
    (h_cont : Continuous f)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (Y ω))) :
    ConvergesInProbabilityToZero P (fun u ω => dist (f (X u ω)) (f (Y ω))) := by
      exact continuous_prob_convergence P X Y f _h_meas_X h_meas_Y h_cont h_conv

/-
Lemma: The risk using estimated embeddings is invariant under affine isometries of the embeddings.
-/
/--
Lemma: The risk using estimated embeddings is invariant under affine isometries of the embeddings.
-/
lemma risk_est_invariant (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (e : E d ≃ᵃⁱ[ℝ] E d)
    (h_inv : InvariantToAffineIsometries n d d' learn) :
    risk_est n d d' P learn loss (fun ω i => e (psi_hat ω i)) = risk_est n d d' P learn loss psi_hat := by
      unfold risk_est;
      simp +decide;
      congr! 2;
      convert rfl using 2;
      exact h_inv e _ _ ▸ rfl

/-
Lemma: The transformed estimated embeddings converge to the true embeddings in probability.
-/
/--
Lemma: under alignment consistency, there *exist* affine isometries `eᵤ` such
that the `eᵤ⁻¹`-transformed estimated embeddings converge to the true embeddings
in probability.  (The existential over the per-stage alignments is load-bearing.)
-/
lemma transformed_embeddings_converge (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat) :
    ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
      ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
        (fun u ω => ⨆ i : Fin (n + 1), dist ((e u).symm (psi_hat u ω i)) ((ω i).1)) := by
          obtain ⟨ e, he ⟩ := h_align;
          refine' ⟨ e, fun ε hε => _ ⟩;
          -- Since $e_u$ is an isometry, the distance between $e_u^{-1}(\psi_hat u \omega i)$ and $\omega i$ is equal to the distance between $\psi_hat u \omega i$ and $e_u(\omega i)$.
          have h_dist_eq : ∀ u ω i, dist (((e u).symm : E d → E d) (psi_hat u ω i)) (ω i).1 = dist (psi_hat u ω i) (e u (ω i).1) := by
            intro u ω i; exact (by
            rw [ ← ( e u ).isometry.dist_eq ] ; aesop;);
          simpa [ h_dist_eq ] using he ε hε

/-
Assumption that the labels y are almost surely contained in a compact set.
-/
def BoundedLabelSupport (d d' : ℕ) (P : Measure (E d × Y d')) : Prop :=
  ∃ K : Set (Y d'), IsCompact K ∧ ∀ᵐ p ∂P, p.2 ∈ K

/-
Lemma: If random variables X and Y are almost surely in compact sets K_A and K_B, and loss is continuous on K_A × K_B, then loss(X, Y) is almost surely bounded.
-/
lemma ae_bounded_of_compact_support {Ω A B : Type*} [MeasurableSpace Ω] [TopologicalSpace A] [TopologicalSpace B]
    (P : Measure Ω)
    (X : Ω → A) (Y : Ω → B)
    (K_A : Set A) (K_B : Set B)
    (loss : A → B → ℝ)
    (h_X : ∀ᵐ ω ∂P, X ω ∈ K_A)
    (h_Y : ∀ᵐ ω ∂P, Y ω ∈ K_B)
    (h_compact_A : IsCompact K_A)
    (h_compact_B : IsCompact K_B)
    (h_cont : ContinuousOn (fun p : A × B => loss p.1 p.2) (K_A ×ˢ K_B)) :
    ∃ M : ℝ, ∀ᵐ ω ∂P, |loss (X ω) (Y ω)| ≤ M := by
      obtain ⟨ M, hM ⟩ := IsCompact.exists_bound_of_continuousOn ( h_compact_A.prod h_compact_B ) h_cont;
      exact ⟨ M, by filter_upwards [ h_X, h_Y ] with ω hω₁ hω₂ using hM ( X ω, Y ω ) ⟨ hω₁, hω₂ ⟩ ⟩

/-
Lemma: If a property holds almost everywhere for a component measure, it holds almost everywhere for the product measure at that component.
-/
lemma ae_mem_of_ae_mem_pi {ι : Type*} [Fintype ι] {α : ι → Type*}
    [∀ i, MeasurableSpace (α i)]
    (μ : (i : ι) → Measure (α i)) [∀ i, SigmaFinite (μ i)]
    (i : ι) (S : Set (α i)) (hS : ∀ᵐ x ∂(μ i), x ∈ S) :
    ∀ᵐ ω ∂(Measure.pi μ), ω i ∈ S := by
      convert hS using 1;
      constructor;
      · exact fun a ↦ (fun {α} {s} {l} ↦ eventually_mem_set.mpr) hS;
      · intro hS;
        rw [ MeasureTheory.ae_iff ] at *;
        -- The set {a | a i ∉ S} is the preimage of {a | a ∉ S} under the projection map π_i.
        have h_preimage : {a : (i : ι) → α i | a i ∉ S} = (fun a => a i) ⁻¹' {a | a ∉ S} := by
          rfl;
        rw [ h_preimage ];
        (expose_names; exact Measure.pi_eval_preimage_null μ hS_1)

/-
Lemma: The loss is uniformly bounded almost surely by a constant M independent of u.
-/
lemma loss_uniformly_bounded (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_bound_learn : BoundedLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P) :
    ∃ M : ℝ, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)),
      |loss (learn (fun i => (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat u ω (Fin.last n))) (ω (Fin.last n)).2| ≤ M := by
        obtain ⟨ K_pred, hK_pred, hK_pred' ⟩ := h_bound_learn;
        obtain ⟨ K_label, hK_label, hK_label' ⟩ := h_bound_label;
        -- Apply ae_mem_of_ae_mem_pi to show label is almost surely in K_label
        have h_label_ae : ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), (ω (Fin.last n)).2 ∈ K_label := by
          refine ae_mem_of_ae_mem_pi (fun _ => P) (Fin.last n) {p | p.2 ∈ K_label} ?_;
          exact hK_label';
        -- Apply ae_bounded_of_compact_support
        let X := fun (u : ℕ) (ω : Fin (n + 1) → E d × Y d') => learn (fun i => (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat u ω (Fin.last n));
        let Y := fun (ω : Fin (n + 1) → E d × Y d') => (ω (Fin.last n)).2;
        -- Since M must be independent of u, we find M first
        obtain ⟨ M, hM ⟩ := IsCompact.exists_bound_of_continuousOn ( hK_pred.prod hK_label ) h_cont_loss.continuousOn;
        use M;
        intro u;
        filter_upwards [ h_label_ae ] with ω hω_label;
        -- Prediction is always in K_pred
        have h_pred : X u ω ∈ K_pred := hK_pred' _ _;
        simpa [Real.norm_eq_abs] using (hM (X u ω, Y ω) ⟨h_pred, hω_label⟩)

/-
Definition of the loss as a function of all embeddings and labels, and proof of its continuity.
-/
def combined_loss_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    ((Fin (n + 1) → E d) × (Fin (n + 1) → Y d')) → ℝ :=
  fun p =>
    let psis := p.1
    let ys := p.2
    let train := fun i : Fin n => (psis (Fin.castSucc i), ys (Fin.castSucc i))
    let test_psi := psis (Fin.last n)
    let test_y := ys (Fin.last n)
    loss (learn train test_psi) test_y

lemma combined_loss_continuous (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss) :
    Continuous (combined_loss_fn n d d' learn loss) := by
      unfold combined_loss_fn;
      unfold ContinuousLearningRule ContinuousLoss at *;
      fun_prop

/-
Lemma: The distance between two pairs with the same second component is the distance between their first components.
-/
lemma dist_prod_same_snd {α β : Type*} [PseudoMetricSpace α] [PseudoMetricSpace β] (x x' : α) (y : β) :
    dist (x, y) (x', y) = dist x x' := by
      simp +zetaDelta at *

/-
Lemma: If X_u converges to X_true in probability, then (X_u, Y) converges to (X_true, Y) in probability.
-/
lemma pair_convergence_in_prob {Ω A B : Type*} [MeasurableSpace Ω]
    (P : Measure Ω)
    [PseudoMetricSpace A] [PseudoMetricSpace B]
    (X : ℕ → Ω → A) (X_true : Ω → A)
    (Y : Ω → B)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (X_true ω))) :
    ConvergesInProbabilityToZero P (fun u ω => dist (X u ω, Y ω) (X_true ω, Y ω)) := by
      simp_all +decide

/-
Lemma: The loss using estimated embeddings converges in probability to the loss using true embeddings.
-/
lemma loss_converges_in_prob (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss) :
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => dist
        (combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2))
        (combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2))) := by
          -- Apply the continuous mapping theorem to conclude the proof.
          apply continuous_prob_convergence_lemma;
          · fun_prop;
          · fun_prop;
          · exact combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss;
          · simp_all +decide [ dist_eq_norm, Prod.norm_def ];
            convert h_conv using 1;
            ext u ω;
            rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ];
            · exact fun i => by simpa using norm_le_pi_norm ( psi_hat u ω - fun i => ( ω i |>.1 ) ) i;
            · intro w hw;
              contrapose! hw;
              exact pi_norm_le_iff_of_nonneg ( by linarith [ show 0 ≤ w by exact le_trans ( norm_nonneg _ ) ( hw 0 ) ] ) |>.2 hw

/-
Lemma: The risk is equal to the estimated risk when the estimated embeddings are the true embeddings.
-/
lemma risk_eq_risk_est_true (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    risk n d d' P learn loss = risk_est n d d' P learn loss (fun ω i => (ω i).1) := by
      exact Real.ext_cauchy rfl

/-
Definitions of the loss functions for estimated and true embeddings.
-/
def loss_est_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (u : ℕ) : (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2)

def loss_true_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2)

/-
Lemma: If estimated embeddings converge to true embeddings in probability, then the risk converges.
-/
lemma risk_convergence_of_aligned_embeddings (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_bound_learn : BoundedLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P) :
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
      -- Apply the lemma that states if the loss difference converges in probability to zero, then the risk converges.
      have h_risk_conv : Tendsto (fun u => ∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 (∫ ω, loss_true_fn n d d' learn loss ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)))) := by
        have h_risk_conv : Tendsto (fun u => ∫ ω, loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 0) := by
          have h_risk_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P)) (fun u ω => loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω) := by
            have h_risk_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P)) (fun u ω => dist (loss_est_fn n d d' learn loss psi_hat u ω) (loss_true_fn n d d' learn loss ω)) := by
              exact loss_converges_in_prob n d d' P learn loss psi_hat h_meas_psi h_conv h_cont_learn h_cont_loss
            exact fun ε hε => by simpa [ Real.dist_eq, abs_abs ] using h_risk_conv ε hε;
          have h_risk_conv : ∃ M : ℝ, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), |loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω| ≤ M := by
            obtain ⟨ M₁, hM₁ ⟩ := loss_uniformly_bounded n d d' P learn loss psi_hat h_bound_learn h_cont_loss h_bound_label;
            obtain ⟨ M₂, hM₂ ⟩ := loss_uniformly_bounded n d d' P learn loss ( fun _ => fun ω i => ( ω i ).1 ) h_bound_learn h_cont_loss h_bound_label;
            exact ⟨ M₁ + M₂, fun u => by filter_upwards [ hM₁ u, hM₂ u ] with ω hω₁ hω₂ using abs_le.mpr ⟨ by linarith! [ abs_le.mp hω₁, abs_le.mp hω₂ ], by linarith! [ abs_le.mp hω₁, abs_le.mp hω₂ ] ⟩ ⟩;
          have h_risk_conv : Tendsto (fun u => ∫ ω, |loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω| ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 0) := by
            obtain ⟨ M, hM ⟩ := h_risk_conv;
            apply_rules [ expectation_converges_of_prob_converges_bounded ];
            intro u;
            apply_rules [ Measurable.sub, Measurable.comp, measurable_const ];
            · apply_rules [ Continuous.measurable, combined_loss_continuous ];
            · fun_prop;
            · apply_rules [ Continuous.measurable, combined_loss_continuous ];
            · fun_prop;
          refine' squeeze_zero_norm ( fun u => MeasureTheory.norm_integral_le_integral_norm _ ) h_risk_conv;
        convert h_risk_conv.add_const ( ∫ ω, loss_true_fn n d d' learn loss ω ∂Measure.pi fun x => P ) using 2 <;> norm_num [ sub_eq_add_neg ];
        rw [ MeasureTheory.integral_add ];
        · rw [ MeasureTheory.integral_neg, add_assoc, neg_add_cancel, add_zero ];
        · -- Since the loss function is bounded, the integral of the loss function over the product measure is finite.
          have h_bounded : ∃ M, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), |loss_est_fn n d d' learn loss psi_hat u ω| ≤ M := by
            exact
              loss_uniformly_bounded n d d' P learn loss
                (fun u ω ↦ (psi_hat u ω, fun i ↦ (ω i).2).1) h_bound_learn h_cont_loss h_bound_label;
          refine' MeasureTheory.Integrable.mono' _ _ _;
          use fun ω => h_bounded.choose;
          · norm_num [ MeasureTheory.integrable_const_iff ];
          · refine' Measurable.aestronglyMeasurable _;
            refine' Measurable.comp ( show Measurable ( combined_loss_fn n d d' learn loss ) from _ ) _;
            · exact Continuous.measurable ( combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss );
            · exact Measurable.prodMk ( h_meas_psi _ ) ( measurable_pi_lambda _ fun _ => measurable_pi_apply _ |> Measurable.snd );
          · exact h_bounded.choose_spec _;
        · -- The loss function is continuous, hence integrable.
          have h_integrable : Integrable (fun ω => loss_true_fn n d d' learn loss ω) (Measure.pi fun x => P) := by
            obtain ⟨ K, hK_compact, hK_bound ⟩ := h_bound_label;
            obtain ⟨ M, hM ⟩ := loss_uniformly_bounded n d d' P learn loss ( fun _ => fun ω i => ( ω i |>.1 ) ) h_bound_learn h_cont_loss ⟨ K, hK_compact, hK_bound ⟩;
            refine' MeasureTheory.Integrable.mono' _ _ _;
            use fun ω => M;
            · norm_num;
            · refine' Continuous.aestronglyMeasurable _;
              apply_rules [ Continuous.comp, continuous_const ];
              · exact combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss;
              · fun_prop;
            · exact hM 0;
          exact h_integrable.neg;
      exact h_risk_conv

/-
Theorem 1: The risk using estimated embeddings converges to the risk using true
embeddings — UNDER the alignment-consistency hypothesis `h_align`
(`DKPSAlignmentConsistency`, the paper's Eq. 3).  This matches the paper's
theorem structure: alignment consistency is a legitimately-assumed input, not
derived here; the genuinely-proved content is the transfer (continuous mapping +
tightness + dominated convergence) from in-probability embedding convergence to
risk convergence.
-/
theorem risk_converges_fixed_n (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat)
    (h_inv : InvariantToAffineIsometries n d d' learn)
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_bound_learn : BoundedLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P) :
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
      obtain ⟨ e, he ⟩ := h_align;
      convert risk_convergence_of_aligned_embeddings n d d' P learn loss ( fun u ω i => ( e u ).symm ( psi_hat u ω i ) ) _ _ using 1;
      · constructor <;> intro h;
        · intro h_cont_learn h_bound_learn h_cont_loss h_bound_label;
          convert h using 1;
          exact funext fun u => risk_est_invariant n d d' P learn loss _ _ ( h_inv );
        · convert h h_cont_learn h_bound_learn h_cont_loss h_bound_label using 1;
          ext u;
          convert risk_est_invariant n d d' P learn loss ( fun ω i => ( e u ).symm ( psi_hat u ω i ) ) ( e u ) h_inv using 1;
          simp +decide [ risk_est ];
      · intro u; exact (by
        have h_meas_symm : Measurable (fun x : E d => (e u).symm x) := by
          exact Continuous.measurable ( by exact ( e u ).symm.continuous );
        fun_prop);
      · convert he using 4;
        ext i; simp +decide [ dist_comm ] ;
        rw [ dist_comm, ← ( e _ ).isometry.dist_eq ];
        swap;
        exacts [ ‹ℕ›, by simp +decide ]

/-
Diagonal sequence lemma: If a(n, u) -> b(n) as u -> infinity for each n, and b(n) -> L as n -> infinity, then there exists a diagonal sequence phi(n) -> infinity such that a(n, phi(n)) -> L.
-/
lemma diagonal_convergence {α : Type*} [TopologicalSpace α] [FirstCountableTopology α]
    (a : ℕ → ℕ → α) (b : ℕ → α) (L : α)
    (h_lim_u : ∀ n, Tendsto (fun u => a n u) atTop (𝓝 (b n)))
    (h_lim_n : Tendsto b atTop (𝓝 L)) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧ Tendsto (fun n => a n (phi n)) atTop (𝓝 L) := by
      -- By the first-countability of α, there exists a countable neighborhood basis at L.
      obtain ⟨U, hU⟩ : ∃ U : ℕ → Set α, (∀ k, IsOpen (U k)) ∧ (∀ k, L ∈ U k) ∧ (∀ k, U (k + 1) ⊆ U k) ∧ ∀ S ∈ nhds L, ∃ k, U k ⊆ S := by
        rcases ( nhds_basis_opens L ).exists_antitone_subbasis with ⟨ U, hU₁, hU₂ ⟩;
        exact ⟨ U, fun k => hU₁ k |>.2, fun k => hU₁ k |>.1, fun k => hU₂.2 k.le_succ, fun S hS => by rcases hU₂.mem_iff.mp hS with ⟨ k, hk ⟩ ; exact ⟨ k, hk ⟩ ⟩
      generalize_proofs at *; (
      -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$.
      obtain ⟨phi, hphi⟩ : ∃ phi : ℕ → ℕ, (∀ n, n ≤ phi n) ∧ (∀ k, ∃ N, ∀ n ≥ N, a n (phi n) ∈ U k) := by
        -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$. Use this fact.
        have h_phi : ∀ k, ∃ N, ∀ n ≥ N, ∃ M, ∀ u ≥ M, a n u ∈ U k := by
          intro k
          obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N, b n ∈ U k := by
            exact Filter.eventually_atTop.mp ( h_lim_n ( hU.1 k |> IsOpen.mem_nhds <| hU.2.1 k ) ) |> fun ⟨ N, hN ⟩ => ⟨ N, fun n hn => hN n hn ⟩
          generalize_proofs at *; (
          exact ⟨ N, fun n hn => by rcases Filter.eventually_atTop.mp ( h_lim_u n ( hU.1 k |> IsOpen.mem_nhds <| hN n hn ) ) with ⟨ M, hM ⟩ ; exact ⟨ M, fun u hu => hM u hu ⟩ ⟩)
        generalize_proofs at *; (
        choose N hN using h_phi
        generalize_proofs at *; (
        choose! M hM using hN
        generalize_proofs at *; (
        use fun n => max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1
        generalize_proofs at *; (
        refine' ⟨ fun n => _, fun k => _ ⟩
        generalize_proofs at *; (
        grind);
        use N k + k + 1
        generalize_proofs at *; (
        intro n hn
        specialize hM k n (by linarith) (max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1) (by
        linarith [ Finset.single_le_sum ( fun x _ => Nat.zero_le ( M x n ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), Finset.single_le_sum ( fun x _ => Nat.zero_le ( N x ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), le_max_left n ( M n n ), le_max_right n ( M n n ) ])
        generalize_proofs at *; exact hM)))))
      generalize_proofs at *; (
      refine' ⟨ phi, Filter.tendsto_atTop_mono hphi.1 tendsto_natCast_atTop_atTop, _ ⟩
      generalize_proofs at *; (
      exact fun S hS => by rcases hU.2.2.2 S hS with ⟨ k, hk ⟩ ; rcases hphi.2 k with ⟨ N, hN ⟩ ; exact Filter.eventually_atTop.2 ⟨ N, fun n hn => hk ( hN n hn ) ⟩ ;)))

/-
Theorem 2: Consistency transfer. If the learning rule is consistent with true embeddings, there exists a schedule of estimation budgets such that it is consistent with estimated embeddings.
-/
theorem consistency_transfer_dkps (d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (L : ℝ)
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))
    (h_bound_learn : ∀ n, BoundedLearningRule n d d' (learn n))
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P)
    (h_consistent : Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 L)) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop (𝓝 L) := by
        -- Apply the diagonal sequence lemma to the sequences $a(n, u)$ and $b(n)$.
        have h_diag : ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧ Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop (𝓝 (L)) := by
          have h_lim_u : ∀ n, Tendsto (fun u => risk_est n d d' P (learn n) loss (psi_hat n u)) atTop (𝓝 (risk n d d' P (learn n) loss)) := by
            exact fun n ↦
              risk_converges_fixed_n n d d' P (learn n) loss (psi_hat n) (h_meas_psi n) (h_align n)
                (h_inv n) (h_cont_learn n) (h_bound_learn n) h_cont_loss h_bound_label
          have h_lim_n : Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 L) := by
            exact h_consistent
          convert diagonal_convergence _ _ _ h_lim_u h_lim_n using 1;
        exact h_diag

/-
Checking if the declarations already exist.
-/

-- #check transformed_embeddings_converge
-- #check diagonal_convergence
-- #check consistency_transfer_dkps

/-!
# Paper-facing interface

This final section is **only documentation + paper-aligned wrappers** around the core
formalization above.  Nothing earlier in the file is renamed; all new names are added
as conveniences for readers of the paper.

## Notation crosswalk (paper → Lean)

Let `d` be the embedding dimension and `d'` be the label dimension.

* Paper `ψ ∈ ℝ^d`                    → `E d`  (a.k.a. `EuclideanSpace ℝ (Fin d)`)
* Paper `y ∈ ℝ^{d'}`                 → `Y d'`
* Paper learning rule `h(·; T_n)`     → `learn : LearningRule n d d'`
* Paper loss `ℓ : Y × Y → ℝ`          → `loss : LossFunction d'`
* Paper risk `R_ℓ(P_{ψY}, h(·; T_n))` → `risk n d d' P learn loss`
* Paper estimated-embedding risk       → `risk_est n d d' P learn loss psi_hat`

### About the paper's budgets `(m,r)`
The paper has two tuning parameters (estimation budgets) and takes limits as `(m,r) → ∞`.
In Lean we abstract this as **one** index `u : ℕ` and write `psi_hat u` for the estimator
at budget `u`.  (If you want the literal paper form, instantiate `u := (m,r)` using a
pair encoding.)

## Assumptions (paper → Lean)

* **A1** (invariance under orthogonal + translation)
  → `InvariantToAffineIsometries` (we use `AffineIsometryEquiv`, which subsumes `ψ ↦ Wψ + a`)

* **A2** (continuity of the learning rule)
  → `ContinuousLearningRule` (standard topological continuity).
  For convenience, we also define a *sequential* variant `PaperA2_SequentialContinuity`
  and show it follows from `ContinuousLearningRule`.

* **A3** (bounded/closed/complete image of each decision function in the hypothesis class)
  The paper states this for a hypothesis class `H ⊆ (E d → Y d')`.
  We provide the direct translation as `PaperA3_HypothesisClass`.
  Our main proofs above use the stronger `BoundedLearningRule`, which gives a **uniform**
  compact set containing *all* predictions of the learning rule across all training sets.

* **A4** (for every `y`, the map `ŷ ↦ ℓ(ŷ,y)` is continuous)
  → `ContinuousLossInPred`.  Our core development assumes the stronger joint continuity
  `ContinuousLoss`; we prove `ContinuousLoss → ContinuousLossInPred`.

* **Eq. (3)** (alignment consistency)
  → `DKPSAlignmentConsistency`.  The paper writes a `max` over training points; in Lean
  we use `iSup` over a finite index type.

## Theorems (paper → Lean)

* **Theorem 1** (fixed `n`: risk with estimated embeddings converges to risk with true embeddings)
  → `risk_converges_fixed_n`

* **Theorem 2** (diagonal schedule transfers consistency)
  → `consistency_transfer_dkps` (for an abstract limit `L`) and
    `consistency_transfer_dkps_bayes` (specialized to Bayes risk over a hypothesis class).

-/

section PaperFacing

/-- A *decision function* `h : E d → Y d'` (paper's `h ∈ H`). -/
abbrev DecisionFunction (d d' : ℕ) := E d → Y d'

/-- Turn a `LearningRule` plus a fixed training set into a decision function. -/
def decisionFnOfLearn (n d d' : ℕ) (learn : LearningRule n d d')
    (t : Fin n → E d × Y d') : DecisionFunction d d' :=
  fun ψ => learn t ψ

/-- Paper Assumption 4: continuity in the first argument, pointwise in `y`. -/
def ContinuousLossInPred (d' : ℕ) (loss : LossFunction d') : Prop :=
  ∀ y : Y d', Continuous (fun yhat : Y d' => loss yhat y)

/-- Joint continuity implies the paper's pointwise continuity assumption. -/
lemma ContinuousLoss.continuousLossInPred {d' : ℕ} {loss : LossFunction d'}
    (h : ContinuousLoss d' loss) : ContinuousLossInPred d' loss := by
  intro y
  have h' : Continuous (fun p : Y d' × Y d' => loss p.1 p.2) := by
    simpa [ContinuousLoss] using h
  -- compose with yhat ↦ (yhat, y)
  exact h'.comp (continuous_id.prodMk continuous_const)

/-- Paper Assumption 2, written as a sequential continuity statement. -/
def PaperA2_SequentialContinuity (n d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∀ (tseq : ℕ → Fin n → E d × Y d') (ψseq : ℕ → E d)
    (t : Fin n → E d × Y d') (ψ : E d),
    Tendsto (fun r => (tseq r, ψseq r)) atTop (𝓝 (t, ψ)) →
      Tendsto (fun r => learn (tseq r) (ψseq r)) atTop (𝓝 (learn t ψ))

/-- `ContinuousLearningRule` implies the paper's sequential continuity formulation of A2. -/
lemma ContinuousLearningRule.paperA2 {n d d' : ℕ} {learn : LearningRule n d d'}
    (h : ContinuousLearningRule n d d' learn) :
    PaperA2_SequentialContinuity n d d' learn := by
  intro tseq ψseq t ψ ht
  have hcont : Continuous (fun p : (Fin n → E d × Y d') × E d => learn p.1 p.2) := by
    simpa [ContinuousLearningRule] using h
  -- `ht : Tendsto (fun r => (tseq r, ψseq r)) atTop (𝓝 (t, ψ))`
  -- apply continuity as a `Tendsto` statement and compose.
  exact (hcont.tendsto (t, ψ)).comp ht

/-- Paper Assumption 3 (as stated): every `h ∈ H` has closed, bounded, complete image. -/
def PaperA3_HypothesisClass (d d' : ℕ) (H : Set (DecisionFunction d d')) : Prop :=
  ∀ h ∈ H,
    IsClosed (Set.range h) ∧
    Bornology.IsBounded (Set.range h) ∧
    IsComplete (Set.range h)

/-- A small helper: `BoundedLearningRule` implies boundedness of each induced decision function's image. -/
lemma BoundedLearningRule.isBounded_range (n d d' : ℕ) {learn : LearningRule n d d'}
    (h : BoundedLearningRule n d d' learn) :
    ∀ t, Bornology.IsBounded (Set.range (decisionFnOfLearn n d d' learn t)) := by
  rcases h with ⟨K, hKc, hK⟩
  intro t
  have hsub : Set.range (decisionFnOfLearn n d d' learn t) ⊆ K := by
    intro y hy
    rcases hy with ⟨ψ, rfl⟩
    exact hK t ψ
  exact hKc.isBounded.subset hsub

/-- Risk of a (measurable) decision function `h : E → Y`. -/
def risk_df (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d') (h : DecisionFunction d d') : ℝ :=
  ∫ p, loss (h p.1) p.2 ∂P

/-- Bayes risk over a hypothesis class `H`. (Paper's `R^*_\ell(P_{ψY}, H)`.) -/
def bayesRisk (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d') (H : Set (DecisionFunction d d')) : ℝ :=
  sInf (risk_df (d:=d) (d':=d') P loss '' H)

/-- Appendix-style (expected) consistency: `risk → bayesRisk`. -/
def ConsistentExpected (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d')
    (learn : (n : ℕ) → LearningRule n d d')
    (H : Set (DecisionFunction d d')) : Prop :=
  Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 (bayesRisk d d' P loss H))

/-- Theorem 2, specialized to Bayes risk over a hypothesis class. -/
theorem consistency_transfer_dkps_bayes (d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (H : Set (DecisionFunction d d'))
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))
    (h_bound_learn : ∀ n, BoundedLearningRule n d d' (learn n))
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P)
    (h_consistent : ConsistentExpected d d' P loss learn H) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop
        (𝓝 (bayesRisk d d' P loss H)) := by
  -- instantiate the existing abstract theorem with `L = bayesRisk ...`
  simpa [ConsistentExpected] using
    consistency_transfer_dkps (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss) (psi_hat:=psi_hat)
      (L := bayesRisk d d' P loss H)
      h_meas_psi h_align h_inv h_cont_learn h_bound_learn h_cont_loss h_bound_label h_consistent

/-!
## Suggested local `#check`s

These are intended for a lightweight sanity pass (they should be fast, unlike some `#find`s).

Uncomment in a scratch file if you like:

```
-- #check risk
-- #check risk_est
-- #check DKPSAlignmentConsistency
-- #check InvariantToAffineIsometries
-- #check ContinuousLearningRule
-- #check BoundedLearningRule
-- #check ContinuousLoss
-- #check risk_converges_fixed_n
-- #check diagonal_convergence
-- #check consistency_transfer_dkps
-- #check consistency_transfer_dkps_bayes
-- #check ContinuousLossInPred
-- #check PaperA3_HypothesisClass
```

-/

end PaperFacing



/-! ## Paper-facing names

These are thin aliases/wrappers so that theorems can be read directly against the paper.

Note on assumptions:
- The paper states (A2) and (A4) only for the coordinates that are perturbed in the DKPS
  transfer argument (embeddings in (A2), predictions in (A4)).  In the Lean proofs we package
  the training sample as `(ψ, y)` pairs and therefore assume *joint* continuity of the learning
  rule (`ContinuousLearningRule`) and of the loss (`ContinuousLoss`).  These are standard
  sufficient conditions for the paper’s pointwise continuity statements and are satisfied by
  typical learning rules / losses.
- The paper’s (A3) is phrased as “image set is closed, bounded, and complete”.
  In finite-dimensional Euclidean spaces, this is equivalent to having a compact range, which
  we encode as `BoundedLearningRule`.
- Wherever we use a strengthened hypothesis, the wrapper section below exposes both the
  paper-level predicate and the strengthened predicate actually used by the Lean proofs.
-/




/-! ### Small helper definitions for paper-facing assumptions -/

section PaperFacingHelpers
variable {n d d' : ℕ}

/-- The uncurried map associated to a learning rule (used to state paper A3). -/
def learnUncurried (learn : LearningRule n d d') : (TrainingSet n d d') × E d → Y d' :=
  fun p => learn p.1 p.2

/-- (Paper A3) The image of the (uncurried) decision function is closed, bounded, and complete. -/
def PaperA3_ImageClosedBoundedComplete (learn : LearningRule n d d') : Prop :=
  IsClosed (Set.range (learnUncurried (n:=n) (d:=d) (d':=d') learn)) ∧
  Bornology.IsBounded (Set.range (learnUncurried (n:=n) (d:=d) (d':=d') learn)) ∧
  IsComplete (Set.range (learnUncurried (n:=n) (d:=d) (d':=d') learn))

/-- Abbreviation: the “paper A2” wrappers below currently use the stronger joint continuity assumption. -/
abbrev ContinuousLearn (learn : LearningRule n d d') : Prop :=
  ContinuousLearningRule n d d' learn

/-- Abbreviation: compact-range encoding of boundedness. -/
abbrev BoundedLearn (learn : LearningRule n d d') : Prop :=
  BoundedLearningRule n d d' learn

end PaperFacingHelpers

section PaperAPI

variable {n d d' : ℕ}

/-- Paper Assumption 1 (Appendix A.1): invariance to rigid motions of the embedding space. -/
abbrev Assumption1 (learn : LearningRule n d d') : Prop :=
  InvariantToAffineIsometries n d d' learn

/-- Paper Assumption 2 (Appendix A.2): continuity of the learning rule. -/
abbrev Assumption2 (learn : LearningRule n d d') : Prop :=
  ContinuousLearningRule n d d' learn

/-- Paper Assumption 3 (Appendix A.3), as written: image of each decision function is closed/bounded/complete. -/
abbrev Assumption3 (learn : LearningRule n d d') : Prop :=
  PaperA3_ImageClosedBoundedComplete (n:=n) (d:=d) (d':=d') learn

/-- Compact-range formulation used in the Lean development.
In finite-dimensional Euclidean spaces this is an equivalent rephrasing of the paper's A3
(closed + bounded + complete image), since bounded sets are precompact and we may take a closed ball
containing the range. -/
abbrev Assumption3' (learn : LearningRule n d d') : Prop :=
  BoundedLearningRule n d d' learn

/-- Paper Assumption 4 (Appendix A.4): loss is continuous in the *prediction* argument for each fixed label. -/
abbrev Assumption4 (loss : LossFunction d') : Prop :=
  ContinuousLossInPred d' loss


/-- Strengthened loss regularity used in the Lean proofs (joint continuity). -/
abbrev Assumption4' (loss : LossFunction d') : Prop :=
  ContinuousLoss d' loss

/-- Compact support of labels `y` (paper condition in Theorem 1). -/
abbrev LabelCompactSupport (P : Measure (Z d d')) : Prop :=
  BoundedLabelSupport d d' P

/-- Alignment consistency (paper Eq. (3)) for a fixed `n`. -/
abbrev AlignmentConsistency (P : Measure (Z d d'))
    (psi_hat : ℕ → (Sample n d d') → Fin (n + 1) → E d) : Prop :=
  DKPSAlignmentConsistency n d d' P psi_hat


/-- **Theorem 1 (paper)**: fixed-`n` risk convergence under aligned estimated embeddings. -/
theorem Theorem1 (n d d' : ℕ)
    (P : Measure (Z d d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Sample n d d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_align : AlignmentConsistency (n:=n) (d:=d) (d':=d') (P:=P) psi_hat)
    (h_inv : Assumption1 (n:=n) (d:=d) (d':=d') learn)
    (h_cont_learn : Assumption2 (n:=n) (d:=d) (d':=d') learn)
    (h_bound_learn : Assumption3' (n:=n) (d:=d) (d':=d') learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : LabelCompactSupport (d:=d) (d':=d') P) :
    Tendsto (fun u => Rhatℓ n d d' P learn loss (psi_hat u)) atTop (𝓝 (Rℓ n d d' P learn loss)) := by
  simpa [Rhatℓ, Rℓ, AlignmentConsistency, Assumption1, Assumption2, Assumption3', LabelCompactSupport] using
    (risk_converges_fixed_n (n:=n) (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss)
      (psi_hat:=psi_hat) h_meas_psi h_align h_inv h_cont_learn h_bound_learn h_cont_loss h_bound_label)


/-- **Theorem 2 (paper)**: consistency transfers from true to estimated embeddings along a schedule. -/
theorem Theorem2_bayes (d d' : ℕ)
    (P : Measure (Z d d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Sample n d d') → Fin (n + 1) → E d)
    (H : Set (E d → Y d'))
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))
    (h_bound_learn : ∀ n, BoundedLearningRule n d d' (learn n))
    (h_cont_loss : ContinuousLoss d' loss)
    (h_bound_label : BoundedLabelSupport d d' P)
    (h_consistent : ConsistentExpected d d' P loss learn H) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => Rhatℓ n d d' P (learn n) loss (psi_hat n (phi n))) atTop
        (𝓝 (bayesRisk d d' P loss H)) := by
  simpa [Rhatℓ] using
    (consistency_transfer_dkps_bayes (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss)
      (psi_hat:=psi_hat) (H:=H) h_meas_psi h_align h_inv h_cont_learn h_bound_learn
      h_cont_loss h_bound_label h_consistent)


end PaperAPI

end DKPS
end Helm2025
