/-
Helm 2025 DKPS statistical-inference formalization — internal machinery.

The analysis lemmas behind the two main theorems (convergence of expectations
from convergence in probability, tightness/uniform-continuity helpers, loss
continuity and boundedness, `risk_est` invariance, `transformed_embeddings_converge`,
`diagonal_convergence`) together with the two core results:

* `risk_converges_fixed_n` — Theorem 1 (fixed-`n` risk convergence under aligned
  estimated embeddings);
* `consistency_transfer_dkps` — Theorem 2 (consistency transfers from true to
  estimated embeddings along a budget schedule).

The paper-facing wrappers (`Theorem1`, `Theorem2_bayes`, Assumptions 1-4) live
in `Helm2025.Inference`.

The scaffold of this development was generated by Aristotle
(https://aristotle.harmonic.fun); co-author: Aristotle (Harmonic)
<aristotle-harmonic@harmonic.fun>.
-/
import Mathlib
import Helm2025.Basic
set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

namespace Helm2025
namespace DKPS

open MeasureTheory Filter Topology Metric
open scoped BigOperators

variable {d d' : ℕ}

/-
Lemma: If a sequence of random variables converges in probability to zero and is uniformly bounded, then their expectations converge to zero.
-/
/--
Internal helper (a bounded-convergence / dominated-convergence step used in the proof
of Theorem 1): convergence in probability to zero plus uniform boundedness implies
convergence of the expectations `E|X_u|` to zero. Not stated separately in the paper.
-/
lemma expectation_converges_of_prob_converges_bounded {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X : ℕ → Ω → ℝ) (M : ℝ)
    -- `h_meas`: measurability of each `X u` — an extra (implicit) measurability assumption
    -- beyond the paper, needed to integrate.
    (h_meas : ∀ u, Measurable (X u))
    -- `h_bound`: uniform (in `u`) a.e. bound `|X u| ≤ M` (the dominating constant).
    (h_bound : ∀ u, ∀ᵐ ω ∂P, |X u ω| ≤ M)
    -- `h_conv`: the in-probability convergence to 0.
    (h_conv : ConvergesInProbabilityToZero P X) :
    -- Conclusion: the expectations of `|X_u|` tend to 0.
    Tendsto (fun u => ∫ ω, |X u ω| ∂P) atTop (𝓝 0) := by
      -- By the dominated convergence theorem, it suffices to show that $|X_u|$ converges to $0$ in measure.
      have h_conv_in_measure : Filter.Tendsto (fun u => ∫ ω, |X u ω| ∂P) Filter.atTop (𝓝 0) := by
        have h_conv_in_measure_aux : ∀ ε > 0, ∃ N, ∀ u ≥ N, ∫ ω, |X u ω| ∂P ≤ ε + M * (P {ω | |X u ω| > ε}).toReal := by
          intro ε ε_pos
          have h_integral_le : ∀ u, ∫ ω, |X u ω| ∂P ≤ ∫ ω, ε + M * (if |X u ω| > ε then 1 else 0) ∂P := by
            intro u;
            refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
            · exact Filter.Eventually.of_forall fun ω => abs_nonneg _;
            · refine' MeasureTheory.Integrable.add _ _ <;> norm_num;
              refine' MeasureTheory.Integrable.indicator _ _;
              · norm_num;
              · exact measurableSet_lt measurable_const ( h_meas u |> Measurable.norm );
            · filter_upwards [ h_bound u ] with ω hω using by split_ifs <;> linarith;
          refine' ⟨ 0, fun u _ => le_trans ( h_integral_le u ) _ ⟩;
          rw [ MeasureTheory.integral_add, MeasureTheory.integral_const_mul ] <;> norm_num;
          · erw [ MeasureTheory.integral_indicator ( measurableSet_lt measurable_const ( h_meas u |> Measurable.norm ) ) ] ; aesop;
          · refine' MeasureTheory.Integrable.indicator _ _;
            · norm_num;
            · exact measurableSet_lt measurable_const ( h_meas u |> Measurable.norm )
        rw [ Metric.tendsto_nhds ];
        intro ε hε;
        obtain ⟨ N, hN ⟩ := h_conv_in_measure_aux ( ε / 2 ) ( half_pos hε );
        have := h_conv ( ε / 2 ) ( half_pos hε );
        rw [ ENNReal.tendsto_nhds_zero ] at this;
        filter_upwards [ this ( ENNReal.ofReal ( ε / ( 2 * ( |M| + 1 ) ) ) ) ( ENNReal.ofReal_pos.mpr ( div_pos hε ( by positivity ) ) ), Filter.Ici_mem_atTop N ] with u hu hu';
        rw [ ENNReal.le_ofReal_iff_toReal_le ] at hu <;> norm_num at *;
        · rw [ abs_of_nonneg ( MeasureTheory.integral_nonneg fun _ => abs_nonneg _ ) ];
          rw [ le_div_iff₀ ] at hu <;> cases abs_cases M <;> nlinarith [ hN u hu', show ( P { ω | ε / 2 < |X u ω| } |> ENNReal.toReal ) ≥ 0 by positivity ];
        · positivity;
      convert h_conv_in_measure using 1


/-
Lemma: Tightness of probability measures on second-countable locally compact spaces. For any epsilon > 0, there exists a compact set K such that the probability of Y not being in K is less than epsilon.
-/
/--
Internal helper (tightness): on a second-countable, locally compact, Hausdorff target
space, the law of a measurable random variable `Y` is tight — for any `ε > 0` there is a
compact `K` with `P(Y ∉ K) < ε`. Standard measure theory, not stated in the paper; used to
turn "continuity" into "uniform continuity on a high-probability compact set".
-/
lemma tightness_helper {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    -- Topological side-conditions on the target space `S` (extra structural assumptions
    -- beyond the paper; all satisfied by the Euclidean label/embedding spaces here).
    {S : Type*} [MeasurableSpace S] [TopologicalSpace S] [BorelSpace S]
    [T2Space S] [LocallyCompactSpace S] [SecondCountableTopology S]
    -- `h_meas_Y`: measurability of `Y` — an extra (implicit) measurability assumption.
    (Y : Ω → S) (h_meas_Y : Measurable Y) :
    -- Conclusion: the law of `Y` is tight (compact `K` capturing all but `ε` of the mass).
    ∀ ε : ENNReal, 0 < ε → ∃ K : Set S, IsCompact K ∧ P {ω | Y ω ∉ K} < ε := by
  intro ε ε_pos

  -- pushforward
  let μ : Measure S := Measure.map Y P
  haveI : OpensMeasurableSpace S := by infer_instance
  haveI : IsFiniteMeasure μ := by infer_instance
  haveI : μ.InnerRegular := by infer_instance

  -- handle ε = ⊤ separately (then goal is trivial)
  by_cases htop : ε = ⊤
  · subst htop
    refine ⟨∅, isCompact_empty, ?_⟩
    -- P{ω | Y ω ∉ ∅} = P univ < ⊤
    -- and P univ ≠ ⊤ since P is finite (probability)
    simp [lt_top_iff_ne_top]

  -- tightness of {μ}
  have hT : IsTightMeasureSet ({μ} : Set (Measure S)) :=
    MeasureTheory.isTightMeasureSet_singleton_of_innerRegular (μ := μ)

  have hiff :=
    (MeasureTheory.isTightMeasureSet_iff_exists_isCompact_measure_compl_le
      (S := ({μ} : Set (Measure S))))

  -- positivity of ε/2 (uses your div_pos signature: a≠0 and b≠⊤)
  have half_pos : (0 : ENNReal) < ε / 2 := by
    refine ENNReal.div_pos (ne_of_gt ε_pos) ?_
    norm_num

  obtain ⟨K, hKc, hK⟩ := (hiff.mp hT) (ε / 2) half_pos
  have hμK : μ Kᶜ ≤ ε / 2 := by
    simpa using hK μ (by simp)

  refine ⟨K, hKc, ?_⟩

  have hKmeas : MeasurableSet K := hKc.measurableSet

  -- rewrite μ(Kᶜ) as P{ω | Y ω ∉ K}
  have h_event : μ (Kᶜ) = P (Y ⁻¹' K)ᶜ := by
    have hs : MeasurableSet (Kᶜ) := hKmeas.compl
    have hm : (Measure.map Y P) (Kᶜ) = P (Y ⁻¹' (Kᶜ)) :=
        MeasureTheory.Measure.map_apply (μ := P) (f := Y) h_meas_Y hs
    simpa [μ, Set.preimage_compl] using hm

  have h_le : P {ω | Y ω ∉ K} ≤ ε / 2 := by
    have hset : {ω | Y ω ∉ K} = (Y ⁻¹' K)ᶜ := by
        ext ω; rfl
    -- rewrite hμK using h_event
    have : P (Y ⁻¹' K)ᶜ ≤ ε / 2 := by
        simpa [h_event] using hμK
    simpa [hset] using this  -- prove ε/2 < ε (now we can use htop : ε ≠ ⊤)
  have hb0 : (2 : ENNReal) ≠ 0 := by norm_num
  have hbt : (2 : ENNReal) ≠ ⊤ := by norm_num

  have h_half_lt : ε / 2 < ε := by
    -- div_lt_iff: (c/b < a) ↔ (c < a*b)
    have hdiv :
        (ε / (2 : ENNReal) < ε) ↔ (ε < ε * (2 : ENNReal)) := by
      simpa using
        (ENNReal.div_lt_iff (a := ε) (b := (2 : ENNReal)) (c := ε)
          (h0 := Or.inl hb0) (ht := Or.inl hbt))
    -- show ε < ε*2 via mul strictness on the right
    have h1lt2 : (1 : ENNReal) < (2 : ENNReal) := by norm_num
    have hmul : ε * (1 : ENNReal) < ε * (2 : ENNReal) := by
      -- mul_lt_mul_right: multiply strict inequality on the right by ε
      -- signature in your build: mul_lt_mul_left / left' exist; right should exist per deprecation note.
      simpa [mul_assoc] using (ENNReal.mul_lt_mul_right (a := ε) (h0 := ne_of_gt ε_pos) (hinf := htop) h1lt2)
    have : ε < ε * (2 : ENNReal) := by simpa [mul_one] using hmul
    exact hdiv.mpr this

  -- finish: P(event) ≤ ε/2 < ε
  exact lt_of_le_of_lt h_le h_half_lt


/-
Lemma: If f is uniformly continuous on K with parameters delta and epsilon, then the probability that f(X) and f(Y) are more than epsilon apart is bounded by the probability that X and Y are more than delta apart plus the probability that Y is not in K.
-/
/--
Internal helper: probability bound from uniform continuity on a set.
If `f` maps `δ`-close points to `ε`-close points whenever the second point is in `K`,
then `P(dist(f X, f Y) > ε) ≤ P(dist(X, Y) ≥ δ) + P(Y ∉ K)`. A union-bound step combining
the tightness helper with uniform continuity; not stated in the paper.
-/
lemma prob_bound_of_uniform_continuity {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω)
    {S S' : Type*} [PseudoMetricSpace S] [PseudoMetricSpace S']
    (X Y : Ω → S) (f : S → S') (K : Set S)
    (ε δ : ℝ)
    -- `h_unif`: the (uniform-continuity) modulus relating `δ`-closeness of inputs to
    -- `ε`-closeness of outputs, valid when the reference point lies in `K`.
    (h_unif : ∀ x y, y ∈ K → dist x y < δ → dist (f x) (f y) ≤ ε) :
    -- Conclusion: the "outputs far apart" event is bounded by "inputs far apart" plus "Y ∉ K".
    P {ω | dist (f (X ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X ω) (Y ω) ≥ δ} + P {ω | Y ω ∉ K} := by
      refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
      intro ω hω; contrapose! hω; aesop;

/-
Lemma: Continuous mapping theorem for convergence in probability. If X_u converges to Y in probability and f is continuous, then f(X_u) converges to f(Y) in probability.
-/
/--
Internal helper — continuous mapping theorem for convergence in probability:
if `X_u → Y` in probability and `f` is continuous, then `f(X_u) → f(Y)` in probability.
This is the engine that pushes the in-probability convergence of embeddings through the
(continuous) loss∘learning-rule map in the proof of Theorem 1; not a separate paper result.
-/
lemma continuous_prob_convergence {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    -- Topological/measurability side-conditions on source `S` and target `S'`
    -- (extra structural assumptions beyond the paper; met by the Euclidean spaces here).
    {S S' : Type*}
    [PseudoMetricSpace S] [MeasurableSpace S] [OpensMeasurableSpace S] [SecondCountableTopology S]
    [T2Space S] [LocallyCompactSpace S] [BorelSpace S]
    [PseudoMetricSpace S'] [MeasurableSpace S'] [OpensMeasurableSpace S']
    (X : ℕ → Ω → S) (Y : Ω → S) (f : S → S')
    -- `_h_meas_X` / `h_meas_Y`: measurability of the random variables (extra implicit
    -- measurability assumptions beyond the paper; `_h_meas_X` is currently unused).
    (_h_meas_X : ∀ u, Measurable (X u))
    (h_meas_Y : Measurable Y)
    (h_cont : Continuous f)                                                  -- continuity of the map
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (Y ω))) :  -- `X_u → Y` in prob.
    -- Conclusion: `f(X_u) → f(Y)` in probability.
    ConvergesInProbabilityToZero P (fun u ω => dist (f (X u ω)) (f (Y ω))) := by
      intro ε hε_pos
      have h_tight : ∀ η > 0, ∃ K : Set S, IsCompact K ∧ P {ω | Y ω∉K} < η := by
        exact fun η a ↦ tightness_helper P Y h_meas_Y η a;
      -- Since `f` is continuous and `K` is compact, `f` is uniformly continuous on `K`.
      have h_unif : ∀ K : Set S, IsCompact K → ∀ ε > 0, ∃ δ > 0, ∀ x y, y ∈ K → dist x y < δ → dist (f x) (f y) ≤ ε := by
        intro K hK ε hε_pos;
        have := hK.elim_nhds_subcover;
        -- By the definition of continuity at a point, for each $y \in K$, there exists $\delta_y > 0$ such that if $dist x y < \delta_y$, then $dist (f x) (f y) < \epsilon / 2$.
        have h_cont_at : ∀ y ∈ K, ∃ δ_y > 0, ∀ x, dist x y < δ_y → dist (f x) (f y) < ε / 2 := by
          exact fun y hy => Metric.continuous_iff.mp h_cont y ( ε / 2 ) ( half_pos hε_pos );
        choose! δ hδ_pos hδ using h_cont_at;
        obtain ⟨ t, ht₁, ht₂ ⟩ := this ( fun y => Metric.ball y ( δ y / 2 ) ) fun y hy => Metric.ball_mem_nhds _ ( half_pos ( hδ_pos y hy ) );
        -- Let $\delta = \min_{x \in t} \frac{\delta_x}{2}$.
        obtain ⟨δ_min, hδ_min_pos, hδ_min⟩ : ∃ δ_min > 0, ∀ x ∈ t, δ_min ≤ δ x / 2 := by
          by_cases ht_empty : t.Nonempty;
          · exact ⟨ Finset.min' ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩, by have := Finset.min'_mem ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩ ; aesop, fun x hx => Finset.min'_le _ _ ( Finset.mem_image_of_mem _ hx ) ⟩;
          · exact ⟨ 1, zero_lt_one, fun x hx => False.elim <| ht_empty ⟨ x, hx ⟩ ⟩;
        refine' ⟨ δ_min, hδ_min_pos, fun x y hy hxy => _ ⟩;
        obtain ⟨ z, hz₁, hz₂ ⟩ := Set.mem_iUnion₂.mp ( ht₂ hy );
        have := hδ z ( ht₁ z hz₁ ) x ?_;
        · have := hδ z ( ht₁ z hz₁ ) y ?_;
          · exact le_trans ( dist_triangle_right _ _ _ ) ( by linarith );
          · exact lt_of_lt_of_le hz₂ ( by linarith [ hδ_pos z ( ht₁ z hz₁ ) ] );
        · exact lt_of_le_of_lt ( dist_triangle _ _ _ ) ( by linarith [ hδ_min z hz₁, Metric.mem_ball.mp hz₂ ] );
      -- Fix `ε > 0`. By `tightness_helper`, for any `η > 0`, there exists a compact set `K` such that `P(Y ∉ K) < η`.
      have h_bound : ∀ η > 0, ∃ δ > 0, ∀ u, P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + η := by
        intro η hη_pos
        obtain ⟨K, hK_compact, hK_bound⟩ := h_tight η hη_pos
        obtain ⟨δ, hδ_pos, hδ_unif⟩ := h_unif K hK_compact ε hε_pos
        use δ, hδ_pos
        intro u
        have h_bound : P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + P {ω | Y ω∉K} := by
          refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
          intro ω hω; contrapose! hω; aesop;
        exact le_trans h_bound (add_le_add_right (le_of_lt hK_bound) _)
      -- By `h_conv`, for any `δ > 0`, `P(X u ω, Y ω) ≥ δ` tends to 0 as `u → ∞`.
      have h_conv_zero : ∀ δ > 0, Filter.Tendsto (fun u => P {ω | dist (X u ω) (Y ω) ≥ δ}) Filter.atTop (𝓝 0) := by
        intro δ hδ_pos
        have := h_conv δ hδ_pos
        simp_all +decide [ ConvergesInProbabilityToZero ];
        have := h_conv ( δ / 2 ) ( half_pos hδ_pos );
        rw [ ENNReal.tendsto_nhds_zero ] at *;
        exact fun ε ε_pos => by filter_upwards [ this ε ε_pos ] with u hu using le_trans ( MeasureTheory.measure_mono ( fun ω hω => by exact lt_of_lt_of_le ( half_lt_self hδ_pos ) hω.out ) ) hu;
      rw [ ENNReal.tendsto_nhds_zero ] at *;
      intro η hη_pos; rcases h_bound ( η / 2 ) ( ENNReal.half_pos hη_pos.ne' ) with ⟨ δ, δ_pos, hδ ⟩ ; filter_upwards [ h_conv_zero δ δ_pos |> fun h => h.eventually ( gt_mem_nhds <| ENNReal.half_pos hη_pos.ne' ) ] with u hu; simpa using le_trans ( hδ u ) ( add_le_add hu.le le_rfl ) |> le_trans <| by rw [ ENNReal.add_halves ] ;


/-
Lemma: If f is continuous and K is compact, then for any epsilon > 0, there exists delta > 0 such that if y is in K and x is within delta of y, then f(x) is within epsilon of f(y).
-/
/--
Internal helper: a continuous function is "uniformly continuous near a compact set".
If `f` is continuous and `K` is compact, then for any `ε > 0` there is `δ > 0` such that for
all `y ∈ K` and any `x`, `dist x y < δ → dist (f x) (f y) < ε`. Standard analysis lemma
supporting the continuous-mapping step; not stated in the paper.
-/
lemma uniform_continuity_on_compact_approx {S S' : Type*}
    [PseudoMetricSpace S] [PseudoMetricSpace S']
    (f : S → S') (K : Set S) (h_cont : Continuous f) (h_compact : IsCompact K) :
    -- Conclusion: a uniform-continuity modulus `δ(ε)` valid for reference points `y ∈ K`.
    ∀ ε > 0, ∃ δ > 0, ∀ y ∈ K, ∀ x, dist x y < δ → dist (f x) (f y) < ε := by
      intro ε εpos;
      by_contra! h_contra;
      choose! y hy x hx using h_contra;
      -- Since $K$ is compact, the sequence $\{y_{1/n}\}$ has a convergent subsequence $\{y_{1/n_k}\}$ that converges to some $y \in K$.
      obtain ⟨y', hy', h_subseq⟩ : ∃ y' ∈ K, ∃ (nk : ℕ → ℕ), StrictMono nk ∧ Filter.Tendsto (fun k => y (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        have := h_compact.isSeqCompact fun n => hy ( 1 / ( n + 1 ) ) ( by positivity );
        tauto;
      -- Since $x_{1/n_k}$ converges to $y'$, we have $f(x_{1/n_k}) \to f(y')$ and $f(y_{1/n_k}) \to f(y')$.
      obtain ⟨nk, hnk_mono, hnk_conv⟩ := h_subseq;
      have hx_conv : Filter.Tendsto (fun k => x (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        have hx_conv : Filter.Tendsto (fun k => dist (x (1 / (nk k + 1)) (by positivity)) (y (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds 0) := by
          exact squeeze_zero ( fun _ => dist_nonneg ) ( fun k => le_of_lt ( hx _ ( by positivity ) |>.1 ) ) ( tendsto_one_div_add_atTop_nhds_zero_nat.comp hnk_mono.tendsto_atTop );
        -- show x_k → y' using dist(x_k,y_k) → 0 and y_k → y'
        refine Metric.tendsto_nhds.2 ?_
        intro ε εpos
        -- y_k → y' gives eventually dist(y_k,y') < ε/2
        have hy' : ∀ᶠ k in Filter.atTop,
            dist (y (1 / (nk k + 1)) (by positivity)) y' < ε / 2 := by
          have := (Metric.tendsto_nhds.1 hnk_conv) (ε / 2) (by linarith)
          simpa [Metric.ball, dist_comm] using this
        -- dist(x_k,y_k) → 0 gives eventually dist(x_k,y_k) < ε/2
        have hxy' : ∀ᶠ k in Filter.atTop,
            dist (x (1 / (nk k + 1)) (by positivity))
                 (y (1 / (nk k + 1)) (by positivity)) < ε / 2 := by
          -- your hx_conv was dist(...) → 0; unpack it
          have := (Metric.tendsto_nhds.1 hx_conv) (ε / 2) (by linarith)
          simpa [Metric.ball] using this
        -- combine via triangle inequality
        filter_upwards [hy', hxy'] with k hyk hxyk
        have : dist (x (1 / (nk k + 1)) (by positivity)) y' < ε := by
            -- triangle inequality
            have htri :
                dist (x (1 / (nk k + 1)) (by positivity)) y'
                    ≤ dist (x (1 / (nk k + 1)) (by positivity))
                            (y (1 / (nk k + 1)) (by positivity))
                    + dist (y (1 / (nk k + 1)) (by positivity)) y' :=
                dist_triangle _ _ _
            -- add the two strict bounds
            have hsum :
                dist (x (1 / (nk k + 1)) (by positivity))
                        (y (1 / (nk k + 1)) (by positivity))
                    + dist (y (1 / (nk k + 1)) (by positivity)) y' < ε := by
                have h := add_lt_add hxyk hyk   -- < ε/2 + ε/2
                -- turn ε/2 + ε/2 into ε
                -- (this is pure arithmetic, so nlinarith is safe here)
                have : (ε / 2 : ℝ) + (ε / 2) = ε := by nlinarith
                simpa [this, add_comm, add_left_comm, add_assoc] using h
            exact lt_of_le_of_lt htri hsum
        -- convert to membership in ball
        simpa [Metric.ball] using this

      have hy_conv : Filter.Tendsto (fun k => y (1 / (nk k + 1)) (by positivity)) Filter.atTop (nhds y') := by
        exact hnk_conv;
      have hf_conv : Filter.Tendsto (fun k => f (x (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds (f y')) := by
        exact h_cont.continuousAt.tendsto.comp hx_conv;
      have hf_conv' : Filter.Tendsto (fun k => f (y (1 / (nk k + 1)) (by positivity))) Filter.atTop (nhds (f y')) := by
        exact h_cont.continuousAt.tendsto.comp hy_conv;
      exact absurd ( le_of_tendsto_of_tendsto' tendsto_const_nhds ( Filter.Tendsto.dist hf_conv hf_conv' ) fun k => hx _ _ |>.2 ) ( by simp +decide [ εpos ] )

/-
Lemma: Continuous mapping theorem for convergence in probability. If X_u converges to Y in probability and f is continuous, then f(X_u) converges to f(Y) in probability.
-/
/--
Internal helper — thin restatement/wrapper of `continuous_prob_convergence` (same
continuous-mapping-theorem statement), provided for convenient application elsewhere in the
proof of Theorem 1. Same extra structural/measurability side-conditions as that lemma.
-/
lemma continuous_prob_convergence_lemma {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S S' : Type*}
    [PseudoMetricSpace S] [MeasurableSpace S] [OpensMeasurableSpace S] [SecondCountableTopology S]
    [T2Space S] [LocallyCompactSpace S] [BorelSpace S]
    [PseudoMetricSpace S'] [MeasurableSpace S'] [OpensMeasurableSpace S']
    (X : ℕ → Ω → S) (Y : Ω → S) (f : S → S')
    (_h_meas_X : ∀ u, Measurable (X u))            -- extra implicit measurability assumptions
    (h_meas_Y : Measurable Y)
    (h_cont : Continuous f)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (Y ω))) :
    -- Conclusion: `f(X_u) → f(Y)` in probability.
    ConvergesInProbabilityToZero P (fun u ω => dist (f (X u ω)) (f (Y ω))) := by
      exact continuous_prob_convergence P X Y f _h_meas_X h_meas_Y h_cont h_conv

/-
Lemma: The risk using estimated embeddings is invariant under affine isometries of the embeddings.
-/
/--
Internal helper: the estimated-embedding risk is invariant under applying a single affine
isometry `e` to all estimated embeddings — a direct consequence of A1
(`InvariantToAffineIsometries`). This is the mechanism by which the unknown per-stage
alignment in `DKPSAlignmentConsistency` can be cancelled in the proof of Theorem 1.
-/
lemma risk_est_invariant (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (e : E d ≃ᵃⁱ[ℝ] E d)
    (h_inv : InvariantToAffineIsometries n d d' learn) :  -- Assumption A1 for `learn`
    -- Conclusion: composing the estimated embeddings with `e` leaves the estimated risk unchanged.
    risk_est n d d' P learn loss (fun ω i => e (psi_hat ω i)) = risk_est n d d' P learn loss psi_hat := by
      unfold risk_est;
      simp +decide;
      congr! 2;
      convert rfl using 2;
      exact h_inv e _ _ ▸ rfl

/-
Lemma: The transformed estimated embeddings converge to the true embeddings in probability.
-/
/--
Lemma: under alignment consistency, there *exist* affine isometries `eᵤ` such
that the `eᵤ⁻¹`-transformed estimated embeddings converge to the true embeddings
in probability.  (The existential over the per-stage alignments is load-bearing.)
-/
lemma transformed_embeddings_converge (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat) :  -- alignment consistency (paper Eq. (3))
    -- Conclusion: re-expressing Eq. (3) by pulling the alignment back onto `ψ̂` (using that
    -- `eᵤ` is an isometry), so `eᵤ⁻¹ ψ̂ᵤ → ψ` in probability uniformly over the sample.
    ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
      ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
        (fun u ω => ⨆ i : Fin (n + 1), dist ((e u).symm (psi_hat u ω i)) ((ω i).1)) := by
          obtain ⟨ e, he ⟩ := h_align;
          refine' ⟨ e, fun ε hε => _ ⟩;
          -- Since $e_u$ is an isometry, the distance between $e_u^{-1}(\psi_hat u \omega i)$ and $\omega i$ is equal to the distance between $\psi_hat u \omega i$ and $e_u(\omega i)$.
          have h_dist_eq : ∀ u ω i, dist (((e u).symm : E d → E d) (psi_hat u ω i)) (ω i).1 = dist (psi_hat u ω i) (e u (ω i).1) := by
            intro u ω i; exact (by
            rw [ ← ( e u ).isometry.dist_eq ] ; aesop;);
          simpa [ h_dist_eq ] using he ε hε

/--
Companion to Assumption A4 (paper): the label marginal has compact support — the labels `y`
lie almost surely in a single compact set `K`. Together with `ContinuousLoss` (A4) this makes
the loss almost surely bounded. NOTE: stating support as *compact* is the encoding used here;
it captures the paper's accompanying boundedness side-condition on labels.
-/
def BoundedLabelSupport (d d' : ℕ) (P : Measure (E d × Y d')) : Prop :=
  ∃ K : Set (Y d'), IsCompact K ∧ ∀ᵐ p ∂P, p.2 ∈ K

/--
Internal helper: if `X, Y` lie a.e. in compact sets `K_A, K_B` and `loss` is continuous on
`K_A × K_B`, then `loss(X, Y)` is a.e. bounded (a continuous function on a compact set is
bounded). Supplies the dominating constant for the convergence-of-expectations step; not
stated in the paper.
-/
lemma ae_bounded_of_compact_support {Ω A B : Type*} [MeasurableSpace Ω] [TopologicalSpace A] [TopologicalSpace B]
    (P : Measure Ω)
    (X : Ω → A) (Y : Ω → B)
    (K_A : Set A) (K_B : Set B)
    (loss : A → B → ℝ)
    -- `h_X`, `h_Y`: the two random variables almost surely lie in their compact sets;
    (h_X : ∀ᵐ ω ∂P, X ω ∈ K_A)
    (h_Y : ∀ᵐ ω ∂P, Y ω ∈ K_B)
    -- `h_compact_A`, `h_compact_B`, `h_cont`: compactness and continuity giving boundedness.
    (h_compact_A : IsCompact K_A)
    (h_compact_B : IsCompact K_B)
    (h_cont : ContinuousOn (fun p : A × B => loss p.1 p.2) (K_A ×ˢ K_B)) :
    -- Conclusion: `loss(X, Y)` is almost surely bounded by some constant `M`.
    ∃ M : ℝ, ∀ᵐ ω ∂P, |loss (X ω) (Y ω)| ≤ M := by
      obtain ⟨ M, hM ⟩ := IsCompact.exists_bound_of_continuousOn ( h_compact_A.prod h_compact_B ) h_cont;
      exact ⟨ M, by filter_upwards [ h_X, h_Y ] with ω hω₁ hω₂ using hM ( X ω, Y ω ) ⟨ hω₁, hω₂ ⟩ ⟩

/--
Internal helper (product-measure bookkeeping): if a property holds a.e. for the `i`-th factor
measure, then it holds a.e. (in the `i`-th coordinate) for the product measure. Used to lift
"labels live in `K`" from a single factor to the full `(n+1)`-fold product. Not in the paper.
-/
lemma ae_mem_of_ae_mem_pi {ι : Type*} [Fintype ι] {α : ι → Type*}
    [∀ i, MeasurableSpace (α i)]
    (μ : (i : ι) → Measure (α i)) [∀ i, SigmaFinite (μ i)]  -- σ-finiteness: extra side-condition
    (i : ι) (S : Set (α i)) (hS : ∀ᵐ x ∂(μ i), x ∈ S) :
    -- Conclusion: the coordinate-`i` event holds a.e. under the product measure.
    ∀ᵐ ω ∂(Measure.pi μ), ω i ∈ S := by
      convert hS using 1;
      constructor;
      · exact fun a ↦ (fun {α} {s} {l} ↦ eventually_mem_set.mpr) hS;
      · intro hS;
        rw [ MeasureTheory.ae_iff ] at *;
        -- The set {a | a i ∉ S} is the preimage of {a | a ∉ S} under the projection map π_i.
        have h_preimage : {a : (i : ι) → α i | a i ∉ S} = (fun a => a i) ⁻¹' {a | a ∉ S} := by
          rfl;
        rw [ h_preimage ];
        (expose_names; exact Measure.pi_eval_preimage_null μ hS_1)

/--
Internal helper: the per-sample loss is almost surely bounded by a constant `M` that is
*uniform in the stage `u`*. Combines A3 (`BoundedLearningRule`, predictions in a compact set),
A4 (`ContinuousLoss`), and `BoundedLabelSupport` (labels in a compact set). Provides the
dominating constant used in the convergence-of-expectations step of Theorem 1.
-/
lemma loss_uniformly_bounded (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    -- Hypotheses A3 + A4 + label compactness, which together force a uniform bound:
    (h_bound_learn : BoundedLearningRule n d d' learn)   -- A3: predictions in a compact set
    (h_cont_loss : ContinuousLoss d' loss)               -- A4: loss continuous
    (h_bound_label : BoundedLabelSupport d d' P) :        -- labels in a compact set
    -- Conclusion: a single `M` a.e.-bounds the loss for every stage `u`.
    ∃ M : ℝ, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)),
      |loss (learn (fun i => (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat u ω (Fin.last n))) (ω (Fin.last n)).2| ≤ M := by
        obtain ⟨ K_pred, hK_pred, hK_pred' ⟩ := h_bound_learn;
        obtain ⟨ K_label, hK_label, hK_label' ⟩ := h_bound_label;
        -- Apply ae_mem_of_ae_mem_pi to show label is almost surely in K_label
        have h_label_ae : ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), (ω (Fin.last n)).2 ∈ K_label := by
          refine ae_mem_of_ae_mem_pi (fun _ => P) (Fin.last n) {p | p.2 ∈ K_label} ?_;
          exact hK_label';
        -- Apply ae_bounded_of_compact_support
        let X := fun (u : ℕ) (ω : Fin (n + 1) → E d × Y d') => learn (fun i => (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat u ω (Fin.last n));
        let Y := fun (ω : Fin (n + 1) → E d × Y d') => (ω (Fin.last n)).2;
        -- Since M must be independent of u, we find M first
        obtain ⟨ M, hM ⟩ := IsCompact.exists_bound_of_continuousOn ( hK_pred.prod hK_label ) h_cont_loss.continuousOn;
        use M;
        intro u;
        filter_upwards [ h_label_ae ] with ω hω_label;
        -- Prediction is always in K_pred
        have h_pred : X u ω ∈ K_pred := hK_pred' _ _;
        simpa [Real.norm_eq_abs] using (hM (X u ω, Y ω) ⟨h_pred, hω_label⟩)

/--
Internal helper definition: the end-to-end loss as a single function of all embeddings and
all labels in an `(n+1)`-sample. It splits the embeddings/labels into a training part (first
`n`) and a test part (last one), trains `learn`, evaluates on the test embedding, and scores
against the test label. This is the composite map through which continuity is propagated.
-/
def combined_loss_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    ((Fin (n + 1) → E d) × (Fin (n + 1) → Y d')) → ℝ :=
  fun p =>
    let psis := p.1
    let ys := p.2
    let train := fun i : Fin n => (psis (Fin.castSucc i), ys (Fin.castSucc i))
    let test_psi := psis (Fin.last n)
    let test_y := ys (Fin.last n)
    loss (learn train test_psi) test_y

/-- Internal helper: the combined loss map is continuous, given A2
(`ContinuousLearningRule`) and A4 (`ContinuousLoss`). -/
lemma combined_loss_continuous (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (h_cont_learn : ContinuousLearningRule n d d' learn)  -- A2
    (h_cont_loss : ContinuousLoss d' loss) :              -- A4
    -- Conclusion: the end-to-end `combined_loss_fn` is continuous.
    Continuous (combined_loss_fn n d d' learn loss) := by
      unfold combined_loss_fn;
      unfold ContinuousLearningRule ContinuousLoss at *;
      fun_prop

/-- Internal helper (metric bookkeeping): the distance between two pairs sharing the same
second component equals the distance between their first components. -/
lemma dist_prod_same_snd {α β : Type*} [PseudoMetricSpace α] [PseudoMetricSpace β] (x x' : α) (y : β) :
    dist (x, y) (x', y) = dist x x' := by
      simp +zetaDelta at *

/-- Internal helper: if `X_u → X_true` in probability, then pairing with a fixed `Y` preserves
this, i.e. `(X_u, Y) → (X_true, Y)` in probability (the second coordinate contributes no
distance). Used to feed embedding convergence into the combined-loss map. -/
lemma pair_convergence_in_prob {Ω A B : Type*} [MeasurableSpace Ω]
    (P : Measure Ω)
    [PseudoMetricSpace A] [PseudoMetricSpace B]
    (X : ℕ → Ω → A) (X_true : Ω → A)
    (Y : Ω → B)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (X_true ω))) :
    -- Conclusion: pairing with the fixed `Y` preserves in-probability convergence.
    ConvergesInProbabilityToZero P (fun u ω => dist (X u ω, Y ω) (X_true ω, Y ω)) := by
      simp_all +decide

/--
Internal helper (core continuous-mapping step of Theorem 1): if the estimated embeddings
converge to the true embeddings in probability (uniformly over the sample), then the
end-to-end loss computed from estimated embeddings converges in probability to the loss
computed from true embeddings.
-/
lemma loss_converges_in_prob (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))           -- extra implicit measurability assumption
    -- `h_conv`: estimated embeddings → true embeddings in probability (sup over the sample);
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    (h_cont_learn : ContinuousLearningRule n d d' learn)  -- A2
    (h_cont_loss : ContinuousLoss d' loss) :              -- A4
    -- Conclusion: the estimated-embedding loss → true-embedding loss in probability.
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => dist
        (combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2))
        (combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2))) := by
          -- Apply the continuous mapping theorem to conclude the proof.
          apply continuous_prob_convergence_lemma;
          · fun_prop;
          · fun_prop;
          · exact combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss;
          · simp_all +decide [ dist_eq_norm, Prod.norm_def ];
            convert h_conv using 1;
            ext u ω;
            rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ];
            · exact fun i => by simpa using norm_le_pi_norm ( psi_hat u ω - fun i => ( ω i |>.1 ) ) i;
            · intro w hw;
              contrapose! hw;
              exact pi_norm_le_iff_of_nonneg ( by linarith [ show 0 ≤ w by exact le_trans ( norm_nonneg _ ) ( hw 0 ) ] ) |>.2 hw

/-- Internal helper: when the "estimated" embeddings are taken to be the true embeddings, the
estimated risk reduces to the true risk (definitional sanity check / base case). -/
lemma risk_eq_risk_est_true (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    -- Conclusion: `risk` equals `risk_est` evaluated at the identity (true) embeddings.
    risk n d d' P learn loss = risk_est n d d' P learn loss (fun ω i => (ω i).1) := by
      exact Real.ext_cauchy rfl

/-- Internal helper definition: the per-sample loss at stage `u` using the *estimated*
embeddings `psi_hat u` (with the true labels). Integrating this over the sample gives the
estimated risk. -/
def loss_est_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (u : ℕ) : (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2)

/-- Internal helper definition: the per-sample loss using the *true* embeddings (the first
component of each sample point). Integrating this gives the true risk. -/
def loss_true_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2)

/--
Internal workhorse for Theorem 1: if the estimated embeddings converge *directly* to the true
embeddings in probability (no alignment isometry left to remove), then the estimated risk
converges to the true risk. This packages the whole "continuous mapping (loss converges in
probability) + uniform boundedness (dominating constant) + convergence of expectations"
argument. `risk_converges_fixed_n` reduces to this lemma after using A1 to absorb the alignment.
-/
lemma risk_convergence_of_aligned_embeddings (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))           -- extra implicit measurability assumption
    -- `h_conv`: estimated embeddings → true embeddings in probability (already aligned);
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    -- Assumptions A2 / A3 / A4 / label-support, supplying continuity and the uniform bound:
    (h_cont_learn : ContinuousLearningRule n d d' learn)  -- A2
    (h_bound_learn : BoundedLearningRule n d d' learn)    -- A3
    (h_cont_loss : ContinuousLoss d' loss)                -- A4
    (h_bound_label : BoundedLabelSupport d d' P) :         -- labels in a compact set
    -- Conclusion: the estimated risk converges to the true risk as the budget `u → ∞`.
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
      -- Apply the lemma that states if the loss difference converges in probability to zero, then the risk converges.
      have h_risk_conv : Tendsto (fun u => ∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 (∫ ω, loss_true_fn n d d' learn loss ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)))) := by
        have h_risk_conv : Tendsto (fun u => ∫ ω, loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 0) := by
          have h_risk_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P)) (fun u ω => loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω) := by
            have h_risk_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P)) (fun u ω => dist (loss_est_fn n d d' learn loss psi_hat u ω) (loss_true_fn n d d' learn loss ω)) := by
              exact loss_converges_in_prob n d d' P learn loss psi_hat h_meas_psi h_conv h_cont_learn h_cont_loss
            exact fun ε hε => by simpa [ Real.dist_eq, abs_abs ] using h_risk_conv ε hε;
          have h_risk_conv : ∃ M : ℝ, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), |loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω| ≤ M := by
            obtain ⟨ M₁, hM₁ ⟩ := loss_uniformly_bounded n d d' P learn loss psi_hat h_bound_learn h_cont_loss h_bound_label;
            obtain ⟨ M₂, hM₂ ⟩ := loss_uniformly_bounded n d d' P learn loss ( fun _ => fun ω i => ( ω i ).1 ) h_bound_learn h_cont_loss h_bound_label;
            exact ⟨ M₁ + M₂, fun u => by filter_upwards [ hM₁ u, hM₂ u ] with ω hω₁ hω₂ using abs_le.mpr ⟨ by linarith! [ abs_le.mp hω₁, abs_le.mp hω₂ ], by linarith! [ abs_le.mp hω₁, abs_le.mp hω₂ ] ⟩ ⟩;
          have h_risk_conv : Tendsto (fun u => ∫ ω, |loss_est_fn n d d' learn loss psi_hat u ω - loss_true_fn n d d' learn loss ω| ∂(Measure.pi (fun _ : Fin (n + 1) => P))) atTop (𝓝 0) := by
            obtain ⟨ M, hM ⟩ := h_risk_conv;
            apply_rules [ expectation_converges_of_prob_converges_bounded ];
            intro u;
            apply_rules [ Measurable.sub, Measurable.comp, measurable_const ];
            · apply_rules [ Continuous.measurable, combined_loss_continuous ];
            · fun_prop;
            · apply_rules [ Continuous.measurable, combined_loss_continuous ];
            · fun_prop;
          refine' squeeze_zero_norm ( fun u => MeasureTheory.norm_integral_le_integral_norm _ ) h_risk_conv;
        convert h_risk_conv.add_const ( ∫ ω, loss_true_fn n d d' learn loss ω ∂Measure.pi fun x => P ) using 2 <;> norm_num [ sub_eq_add_neg ];
        rw [ MeasureTheory.integral_add ];
        · rw [ MeasureTheory.integral_neg, add_assoc, neg_add_cancel, add_zero ];
        · -- Since the loss function is bounded, the integral of the loss function over the product measure is finite.
          have h_bounded : ∃ M, ∀ u, ∀ᵐ ω ∂(Measure.pi (fun _ : Fin (n + 1) => P)), |loss_est_fn n d d' learn loss psi_hat u ω| ≤ M := by
            exact
              loss_uniformly_bounded n d d' P learn loss
                (fun u ω ↦ (psi_hat u ω, fun i ↦ (ω i).2).1) h_bound_learn h_cont_loss h_bound_label;
          refine' MeasureTheory.Integrable.mono' _ _ _;
          use fun ω => h_bounded.choose;
          · norm_num [ MeasureTheory.integrable_const_iff ];
          · refine' Measurable.aestronglyMeasurable _;
            refine' Measurable.comp ( show Measurable ( combined_loss_fn n d d' learn loss ) from _ ) _;
            · exact Continuous.measurable ( combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss );
            · exact Measurable.prodMk ( h_meas_psi _ ) ( measurable_pi_lambda _ fun _ => measurable_pi_apply _ |> Measurable.snd );
          · exact h_bounded.choose_spec _;
        · -- The loss function is continuous, hence integrable.
          have h_integrable : Integrable (fun ω => loss_true_fn n d d' learn loss ω) (Measure.pi fun x => P) := by
            obtain ⟨ K, hK_compact, hK_bound ⟩ := h_bound_label;
            obtain ⟨ M, hM ⟩ := loss_uniformly_bounded n d d' P learn loss ( fun _ => fun ω i => ( ω i |>.1 ) ) h_bound_learn h_cont_loss ⟨ K, hK_compact, hK_bound ⟩;
            refine' MeasureTheory.Integrable.mono' _ _ _;
            use fun ω => M;
            · norm_num;
            · refine' Continuous.aestronglyMeasurable _;
              apply_rules [ Continuous.comp, continuous_const ];
              · exact combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss;
              · fun_prop;
            · exact hM 0;
          exact h_integrable.neg;
      exact h_risk_conv

/--
**Theorem 1 (paper, fixed-`n` risk convergence).**
For a fixed sample size `n`, as the embedding-estimation budget `u → ∞`, the risk computed
from *estimated* embeddings `ψ̂_u` converges to the risk computed from the *true* embeddings
`ψ`. The substantive input is alignment consistency (`h_align`, paper Eq. (3)); the proved
content is the transfer — via the continuous-mapping theorem, tightness, and a
dominated/bounded-convergence argument — from in-probability convergence of the embeddings to
convergence of the (integrated) risk. A1 (`h_inv`) removes the unknown per-stage alignment.
For situations where `ψ̂` are good proxies, this says that increasing queries/replicates
improves the performance of decision functions trained on the estimated training set.
-/
theorem risk_converges_fixed_n (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))            -- extra implicit measurability assumption
    -- The substantive statistical input (paper Eq. (3)):
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat)  -- `ψ̂_u → ψ` up to alignment, in probability
    -- The paper's regularity assumptions A1–A4 (+ label support):
    (h_inv : InvariantToAffineIsometries n d d' learn)    -- A1 (cancels the alignment isometry)
    (h_cont_learn : ContinuousLearningRule n d d' learn)  -- A2
    (h_bound_learn : BoundedLearningRule n d d' learn)    -- A3
    (h_cont_loss : ContinuousLoss d' loss)                -- A4
    (h_bound_label : BoundedLabelSupport d d' P) :         -- labels in a compact set
    -- Conclusion: estimated risk → true risk as the estimation budget `u → ∞`.
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
      obtain ⟨ e, he ⟩ := h_align;
      convert risk_convergence_of_aligned_embeddings n d d' P learn loss ( fun u ω i => ( e u ).symm ( psi_hat u ω i ) ) _ _ using 1;
      · constructor <;> intro h;
        · intro h_cont_learn h_bound_learn h_cont_loss h_bound_label;
          convert h using 1;
          exact funext fun u => risk_est_invariant n d d' P learn loss _ _ ( h_inv );
        · convert h h_cont_learn h_bound_learn h_cont_loss h_bound_label using 1;
          ext u;
          convert risk_est_invariant n d d' P learn loss ( fun ω i => ( e u ).symm ( psi_hat u ω i ) ) ( e u ) h_inv using 1;
          simp +decide [ risk_est ];
      · intro u; exact (by
        have h_meas_symm : Measurable (fun x : E d => (e u).symm x) := by
          exact Continuous.measurable ( by exact ( e u ).symm.continuous );
        fun_prop);
      · convert he using 4;
        ext i; simp +decide [ dist_comm ] ;
        rw [ dist_comm, ← ( e _ ).isometry.dist_eq ];
        swap;
        exacts [ ‹ℕ›, by simp +decide ]

/--
Diagonal sequence lemma (the analytic device underlying Theorem 2). If, for each fixed `n`,
`a(n, u) → b(n)` as `u → ∞`, and `b(n) → L` as `n → ∞`, then there is a diagonal schedule
`phi : ℕ → ℕ` with `phi → ∞` along which `a(n, phi(n)) → L`. In Theorem 2, `a(n, u)` is the
estimated risk at sample size `n` and budget `u`, `b(n)` the true risk, and `L` the
consistency limit; the schedule `phi` is exactly the "budget schedule" the paper invokes.
-/
lemma diagonal_convergence {α : Type*} [TopologicalSpace α] [FirstCountableTopology α]
    (a : ℕ → ℕ → α) (b : ℕ → α) (L : α)
    (h_lim_u : ∀ n, Tendsto (fun u => a n u) atTop (𝓝 (b n)))  -- inner limits (each `n`): `a(n,·) → b(n)`
    (h_lim_n : Tendsto b atTop (𝓝 L)) :                        -- outer limit: `b(n) → L`
    -- Conclusion: a diverging diagonal schedule `phi` along which `a(n, phi(n)) → L`.
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧ Tendsto (fun n => a n (phi n)) atTop (𝓝 L) := by
      -- By the first-countability of α, there exists a countable neighborhood basis at L.
      obtain ⟨U, hU⟩ : ∃ U : ℕ → Set α, (∀ k, IsOpen (U k)) ∧ (∀ k, L ∈ U k) ∧ (∀ k, U (k + 1) ⊆ U k) ∧ ∀ S ∈ nhds L, ∃ k, U k ⊆ S := by
        rcases ( nhds_basis_opens L ).exists_antitone_subbasis with ⟨ U, hU₁, hU₂ ⟩;
        exact ⟨ U, fun k => hU₁ k |>.2, fun k => hU₁ k |>.1, fun k => hU₂.2 k.le_succ, fun S hS => by rcases hU₂.mem_iff.mp hS with ⟨ k, hk ⟩ ; exact ⟨ k, hk ⟩ ⟩
      generalize_proofs at *; (
      -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$.
      obtain ⟨phi, hphi⟩ : ∃ phi : ℕ → ℕ, (∀ n, n ≤ phi n) ∧ (∀ k, ∃ N, ∀ n ≥ N, a n (phi n) ∈ U k) := by
        -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$. Use this fact.
        have h_phi : ∀ k, ∃ N, ∀ n ≥ N, ∃ M, ∀ u ≥ M, a n u ∈ U k := by
          intro k
          obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N, b n ∈ U k := by
            exact Filter.eventually_atTop.mp ( h_lim_n ( hU.1 k |> IsOpen.mem_nhds <| hU.2.1 k ) ) |> fun ⟨ N, hN ⟩ => ⟨ N, fun n hn => hN n hn ⟩
          generalize_proofs at *; (
          exact ⟨ N, fun n hn => by rcases Filter.eventually_atTop.mp ( h_lim_u n ( hU.1 k |> IsOpen.mem_nhds <| hN n hn ) ) with ⟨ M, hM ⟩ ; exact ⟨ M, fun u hu => hM u hu ⟩ ⟩)
        generalize_proofs at *; (
        choose N hN using h_phi
        generalize_proofs at *; (
        choose! M hM using hN
        generalize_proofs at *; (
        use fun n => max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1
        generalize_proofs at *; (
        refine' ⟨ fun n => _, fun k => _ ⟩
        generalize_proofs at *; (
        grind);
        use N k + k + 1
        generalize_proofs at *; (
        intro n hn
        specialize hM k n (by linarith) (max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1) (by
        linarith [ Finset.single_le_sum ( fun x _ => Nat.zero_le ( M x n ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), Finset.single_le_sum ( fun x _ => Nat.zero_le ( N x ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), le_max_left n ( M n n ), le_max_right n ( M n n ) ])
        generalize_proofs at *; exact hM)))))
      generalize_proofs at *; (
      refine' ⟨ phi, Filter.tendsto_atTop_mono hphi.1 tendsto_natCast_atTop_atTop, _ ⟩
      generalize_proofs at *; (
      exact fun S hS => by rcases hU.2.2.2 S hS with ⟨ k, hk ⟩ ; rcases hphi.2 k with ⟨ N, hN ⟩ ; exact Filter.eventually_atTop.2 ⟨ N, fun n hn => hk ( hN n hn ) ⟩ ;)))

/--
**Theorem 2 (paper, consistency transfer).**
If the sequence of decision rules is *consistent* using the true embeddings — i.e. the true
risk `R(n)` converges to a limit `L` as the number of models `n → ∞` (`h_consistent`) — then
there exists a schedule of estimation budgets `phi(n) → ∞` along which the *estimated*-embedding
risk also converges to the same `L`. In other words, consistency transfers from the
true training sets `T_n` to the estimated training sets `T̂_n`. The proof applies Theorem 1
(`risk_converges_fixed_n`) at each fixed `n` to get the inner limits, then `diagonal_convergence`
to build the budget schedule. The assumptions A1–A4 (+ alignment, label support) are imposed
uniformly over all `n`.
-/
theorem consistency_transfer_dkps (d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')               -- a learning rule for every sample size `n`
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (L : ℝ)                                                -- the consistency limit
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))         -- extra implicit measurability assumption
    -- The paper's assumptions, imposed uniformly over the sample size `n`:
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))  -- alignment consistency (Eq. (3))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))     -- A1
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))   -- A2
    (h_bound_learn : ∀ n, BoundedLearningRule n d d' (learn n))     -- A3
    (h_cont_loss : ContinuousLoss d' loss)                         -- A4
    (h_bound_label : BoundedLabelSupport d d' P)                    -- labels in a compact set
    -- The hypothesis being transferred: consistency under the *true* embeddings.
    (h_consistent : Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 L)) :
    -- Conclusion: a diverging budget schedule `phi` along which the *estimated*-embedding risk → `L`.
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop (𝓝 L) := by
        -- Apply the diagonal sequence lemma to the sequences $a(n, u)$ and $b(n)$.
        have h_diag : ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧ Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop (𝓝 (L)) := by
          have h_lim_u : ∀ n, Tendsto (fun u => risk_est n d d' P (learn n) loss (psi_hat n u)) atTop (𝓝 (risk n d d' P (learn n) loss)) := by
            exact fun n ↦
              risk_converges_fixed_n n d d' P (learn n) loss (psi_hat n) (h_meas_psi n) (h_align n)
                (h_inv n) (h_cont_learn n) (h_bound_learn n) h_cont_loss h_bound_label
          have h_lim_n : Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 L) := by
            exact h_consistent
          convert diagonal_convergence _ _ _ h_lim_u h_lim_n using 1;
        exact h_diag

end DKPS
end Helm2025
