name = "dkps_quench_icml_2026"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DKPS_Quench_ICML_2026"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "DKPS_Quench_ICML_2026"