/-
# AIQ DKPS ForMathlib full inventory challenge solution file

Imports the project `ForMathlib` staging library. The declarations named in
`comparator/aiq-mathlib-inventory.json` are provided by those imports.
-/
import ForMathlib.MeasureTheory.Measure.Typeclasses.Probability
import ForMathlib.Probability.Moments.Variance
import ForMathlib.Probability.Moments.SampleMean
import ForMathlib.Analysis.Matrix.EntrywiseOpNorm
import ForMathlib.Analysis.InnerProductSpace.Spectrum
import ForMathlib.Analysis.InnerProductSpace.CourantFischer
import ForMathlib.Analysis.InnerProductSpace.DavisKahan
import ForMathlib.Analysis.InnerProductSpace.GramMatrix
import ForMathlib.Analysis.InnerProductSpace.NearIsometry
import ForMathlib.Analysis.Matrix.Spectrum
import ForMathlib.LinearAlgebra.Matrix.PosDef
import ForMathlib.MeasureTheory.CfcMeasurable
import ForMathlib.MeasureTheory.CompactExists
import ForMathlib.MeasureTheory.Function.ConvergenceInMeasure
import ForMathlib.Analysis.Matrix.SpectralFunctionMeasurable
import ForMathlib.Analysis.Matrix.EntrywiseEigenvalue
import ForMathlib.Probability.Moments.MatrixConcentration
import ForMathlib.Probability.Moments.SampleCovariance
import ForMathlib.Topology.ApproxMinimizer
import ForMathlib.Topology.Berge

/-! Axiom audit commands for the inventory declarations. -/
#print axioms ForMathlib.one_sub_measure_compl_le
#print axioms ForMathlib.meas_gt_le_ofReal_integral_sq_div_sq
#print axioms ForMathlib.integral_sq_scaledSum_sub_of_pairwise_indep
#print axioms ForMathlib.integral_norm_sq_average_sub_eq_sum
#print axioms ForMathlib.integral_norm_sq_average_sub_of_iid
#print axioms ForMathlib.integral_norm_sq_average_sub_le_of_bound
#print axioms ForMathlib.sum_norm_le_sqrt_card_mul_norm
#print axioms ForMathlib.norm_toEuclideanLin_le_of_entry_le
#print axioms ForMathlib.inner_eigenvectorBasis_map_sub_eigenvectorBasis
#print axioms ForMathlib.finrank_specSubspace
#print axioms ForMathlib.repr_eq_zero_of_mem_specSubspace
#print axioms ForMathlib.re_inner_map_self_eq_sum_eigenvalues_mul_sq
#print axioms ForMathlib.exists_unit_vector_re_inner_le_eigenvalue
#print axioms ForMathlib.forall_unit_vector_eigenvalue_le_re_inner
#print axioms ForMathlib.abs_eigenvalues_sub_le
#print axioms ForMathlib.sum_norm_inner_eigenvectorBasis_map_sub_sq_le
#print axioms ForMathlib.sum_cross_norm_inner_eigenvectorBasis_sq_le
#print axioms ForMathlib.gap_of_rank_floor
#print axioms ForMathlib.sum_cross_norm_inner_eigenvectorBasis_sq_le_of_rank_floor
#print axioms ForMathlib.spectralProjection_apply
#print axioms ForMathlib.spectralProjection_apply_self
#print axioms ForMathlib.sum_norm_sub_spectralProjection_sq_eq
#print axioms ForMathlib.sum_norm_sub_spectralProjection_sq_le
#print axioms ForMathlib.exists_linearIsometryEquiv_of_inner_eq
#print axioms ForMathlib.Matrix.gram_eq_gram_iff_exists_linearIsometryEquiv
#print axioms ForMathlib.Real.abs_one_sub_inv_sqrt_le
#print axioms ForMathlib.LinearMap.exists_linearIsometryEquiv_norm_sub_le
#print axioms ForMathlib.ContinuousLinearMap.exists_linearIsometryEquiv_norm_sub_le
#print axioms ForMathlib.Matrix.PosSemidef.eigenvalues₀_eq_zero_of_le
#print axioms ForMathlib.Matrix.isHermitian_entry_eq_sum_eigenvalues
#print axioms ForMathlib.Matrix.posSemidef_and_rank_le_iff_exists_conjTranspose_mul_self
#print axioms ForMathlib.measurable_of_iUnion_restrict
#print axioms ForMathlib.measurable_cfc_comp
#print axioms ForMathlib.measurableSet_exists_mem_le
#print axioms ForMathlib.tendstoInMeasure_of_tendsto_measure_rate_lt_edist
#print axioms ForMathlib.tendstoInMeasure_of_tendsto_measure_rate_lt_dist
#print axioms ForMathlib.tendstoInMeasure_of_tendsto_measure_dist_le_rate
#print axioms ForMathlib.Matrix.exists_polynomial_uniform_close
#print axioms ForMathlib.Matrix.abs_coord_le_norm
#print axioms ForMathlib.Matrix.abs_sortedEig_le_of_entry_le
#print axioms ForMathlib.Matrix.pow_mulVec_eigenvector
#print axioms ForMathlib.Matrix.aeval_mulVec_eigenvector
#print axioms ForMathlib.Matrix.mulVec_eigenvectorBasis
#print axioms ForMathlib.Matrix.aeval_entry_eq_sum
#print axioms ForMathlib.Matrix.abs_specTransform_sub_aeval_le
/- `ForMathlib.Matrix.measurable_specTransform` is intentionally excluded from
   the inventory challenge for now; see `ChallengeInventoryConformance.lean`. -/
#print axioms ForMathlib.Matrix.abs_sortedEig_sub_le_of_entry_le
#print axioms ForMathlib.measure_exists_entry_gt_le
#print axioms ForMathlib.measure_forall_abs_sortedEig_sub_le_ge
#print axioms ForMathlib.measure_forall_sortedEig_ge_ge
#print axioms ForMathlib.integral_sq_sampleCovariance_entry_le
#print axioms ForMathlib.isHermitian_sampleCovariance
#print axioms ForMathlib.measure_forall_sampleCovariance_sortedEig_ge_ge
#print axioms ForMathlib.exists_subseq_tendsto_forall_le_of_approxMin
#print axioms ForMathlib.exists_subseq_tendsto_isMinOn_of_approxMinOn
#print axioms ForMathlib.tendsto_eval_sub_of_isCompact
#print axioms ForMathlib.tendsto_subseq_isMinOn_of_isMinOn
#print axioms ForMathlib.upperHemicontinuousAt_isMinOn
#print axioms ForMathlib.continuous_iInf_of_isCompact
#print axioms ForMathlib.exists_modulus_isMinOn_family
#print axioms ForMathlib.exists_modulus_isMinOn
