/-
DKPS / Quench query-efficiency formalization — core definitions.

Types and definitions for the nearest-neighbor query-efficiency result: the
abstract model/perspective types, the NN estimator (`nnIndex`, `hNN_estimator`,
`yNN_paper`), the score targets (`yFull`, `yQ`), the loss/risk (`MSE`, `Risk`),
the paper's query-efficiency predicates (`QQueryEfficient`, `mQueryEfficient`),
and the assumptions (`LipschitzScore`, `HighProbAtTop`).

The scaffold of this development was generated by Aristotle
(https://aristotle.harmonic.fun); co-author: Aristotle (Harmonic)
<aristotle-harmonic@harmonic.fun>.
-/
import Mathlib
set_option linter.mathlibStandardSet false

open scoped BigOperators Real Nat Classical Pointwise Topology
open Filter MeasureTheory

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

universe u v

abbrev ProbMeasure (X : Type u) [MeasurableSpace X] :=
  { μ : Measure X // IsProbabilityMeasure μ }

abbrev Model (Q : Type u) (X : Type v) [MeasurableSpace X] :=
  Q → ProbMeasure X

abbrev Vec (p : ℕ) := EuclideanSpace ℝ (Fin p)

abbrev Mat (m p : ℕ) := Matrix (Fin m) (Fin p) ℝ

noncomputable def frobNorm {m p : ℕ} (A : Mat m p) : ℝ :=
  Real.sqrt (∑ i, ∑ j, (A i j) ^ (2 : ℕ))

noncomputable def meanEmbed {p : ℕ} {X : Type v} [MeasurableSpace X] (μ : ProbMeasure X) (g : X → Vec p) : Vec p :=
  ∫ x, g x ∂ μ.1

noncomputable def XbarMat {Q : Type u} {X : Type v} [MeasurableSpace X] {m p : ℕ} (f : Model Q X) (Qset : Fin m → Q) (g : X → Vec p) :
    Mat m p :=
  fun i j => (meanEmbed (μ := f (Qset i)) g) j

noncomputable def distMatrix {Q : Type u} {X : Type v} [MeasurableSpace X] {n m p : ℕ} (models : Fin n → Model Q X) (Qset : Fin m → Q)
    (g : X → Vec p) : Matrix (Fin n) (Fin n) ℝ :=
  fun i i' => frobNorm (XbarMat (f := models i) Qset g - XbarMat (f := models i') Qset g)

noncomputable def dkpsStress {n d : ℕ} (D : Matrix (Fin n) (Fin n) ℝ) (z : Fin n → Vec d) : ℝ :=
  ∑ i, ∑ i', (‖z i - z i'‖ - D i i') ^ (2 : ℕ)

def IsDKPS {n d : ℕ} (D : Matrix (Fin n) (Fin n) ℝ) (z : Fin n → Vec d) : Prop :=
  ∀ z' : Fin n → Vec d, dkpsStress (D := D) z ≤ dkpsStress (D := D) z'

section Benchmark_Setup

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

variable (Qstar : Finset Q)
variable (score : Model Q X → Finset Q → ℝ)

--def yFull (f : Model Q X) : ℝ := score f Qstar
def ySubset (Qsub : Finset Q) (f : Model Q X) : ℝ := score f Qsub

end Benchmark_Setup

section QueryEfficiency

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

noncomputable def Risk
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (y h : Model Q X → ℝ) : ℝ :=
  ∫ f, ℓ (h f) (y f) ∂ Pf

def QQueryEfficient
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (y : Model Q X → ℝ)
    (h h' : ℕ → Model Q X → ℝ) : Prop :=
  ∃ N : ℕ, ∀ n > N,
    Risk (Q := Q) (X := X) Pf ℓ y (h n) ≤ Risk (Q := Q) (X := X) Pf ℓ y (h' n)

def mQueryEfficient
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (m : ℕ) (y : Model Q X → ℝ)
    (h h' : Finset Q → ℕ → Model Q X → ℝ) : Prop :=
  ∀ Qsub : Finset Q, Qsub.card = m →
    ∃ N : ℕ, ∀ n > N,
      Risk (Q := Q) (X := X) Pf ℓ y (h Qsub n) ≤ Risk (Q := Q) (X := X) Pf ℓ y (h' Qsub n)

end QueryEfficiency

section Assumptions_And_Theorems

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

def HighProbAtTop {Ω : Type} [MeasurableSpace Ω]
    (μ : ℕ → Measure Ω) (hμ : ∀ n, IsProbabilityMeasure (μ n)) (E : ℕ → Set Ω) : Prop :=
  ∀ δ : ENNReal, 0 < δ → ∃ N : ℕ, ∀ n > N, (μ n) (E n) ≥ 1 - δ

def HighProbAtTopDep (Ω : ℕ → Type) (instΩ : ∀ n, MeasurableSpace (Ω n))
    (μ : ∀ n, Measure (Ω n)) (hμ : ∀ n, IsProbabilityMeasure (μ n))
    (E : ∀ n, Set (Ω n)) : Prop :=
  ∀ δ : ENNReal, 0 < δ → ∃ N : ℕ, ∀ n > N, (μ n) (E n) ≥ 1 - δ

def HighProb {Ω : Type} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsProbabilityMeasure μ] (E : Set Ω) (δ : ENNReal) : Prop :=
  μ E ≥ 1 - δ

def LipschitzScore {d : ℕ} (γ : ℝ)
    (Psi : Finset Q → Model Q X → Vec d)
    (y : Model Q X → ℝ) : Prop :=
  ∀ (Qsub : Finset Q) (f f' : Model Q X),
    |y f - y f'| ≤ γ * ‖Psi Qsub f - Psi Qsub f'‖

end Assumptions_And_Theorems

open scoped Topology

noncomputable def applyIso {n d : ℕ} (W : (Vec d) ≃ₗᵢ[ℝ] (Vec d)) (x : Fin n → Vec d) : Fin n → Vec d :=
  fun i => W (x i)

def sqLoss (a b : ℝ) : ℝ := (a - b) ^ (2 : ℕ)

noncomputable def MSE {Q : Type u} {X : Type v} [MeasurableSpace X]
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (y yHat : Model Q X → ℝ) : ℝ :=
  ∫ f, sqLoss (yHat f) (y f) ∂ Pf

section NN_Definitions

variable {d : ℕ}

def IsArgmin {n : ℕ} (f : Fin n → ℝ) (i : Fin n) : Prop :=
  ∀ j : Fin n, f i ≤ f j

noncomputable def nnIndex {n : ℕ} (hn : n > 0)
    (ψHat_ref : Fin n → Vec d)
    (ψHat_target : Vec d) : Fin n :=
  let f := fun i => ‖ψHat_ref i - ψHat_target‖
  have h_exists : ∃ i, IsArgmin f i := by
    haveI : Nonempty (Fin n) := Fin.pos_iff_nonempty.mp hn
    have h_nonempty : (Finset.univ : Finset (Fin n)).Nonempty := Finset.univ_nonempty
    obtain ⟨i, _, hi⟩ := Finset.exists_min_image (Finset.univ : Finset (Fin n)) f h_nonempty
    exact ⟨i, fun j => hi j (Finset.mem_univ j)⟩
  Classical.choose h_exists

noncomputable def hNN_estimator {n : ℕ} (hn : n > 0)
    (ψHat_ref : Fin n → Vec d)
    (ψHat_target : Vec d)
    (y_ref : Fin n → ℝ) : ℝ :=
  y_ref (nnIndex hn ψHat_ref ψHat_target)

end NN_Definitions
