/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: dc86a3dc-5f5e-4ff0-92b5-8ba9219d4e7a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Added 1 fix from GPT5.2 in step6_parameter_choice wrt h_bound
-/

/-
Formalization of DKPS / Quench ICML paper Theorem 2.

We have proven:
1. `Theorem2_part1_v2`: The NN estimator has MSE ≤ ε with high probability, given the necessary assumptions (Lipschitz score, concentration of embeddings, support/denseness). This corresponds to Part 1 of Theorem 2.
2. `Theorem2_part2`: Query efficiency relative to a baseline estimator, derived from Part 1.

We used the following helper lemmas and steps:
- `step1_lipschitz_bound`: Lipschitz condition reduces score error to embedding distance.
- `step2_triangle_inequality`: Triangle inequality decomposition of the error.
- `step3_concentration_bound`: Bounding error on the concentration event.
- `step4_support_bound`: Bounding error using the support (denseness) assumption.
- `step5_pointwise_error`: Combining steps to get a pointwise error bound.
- `step6_parameter_choice`: Choosing parameters ρ and c to meet the target error ε.
- `step7_mse_bound`: Converting pointwise error bound to MSE bound.
- `HighProbAtTop.inter_v3` and `HighProbAtTop.mono_eventually`: Helper lemmas for high-probability event logic.
- `nnIndex_isArgmin`: Property of the nearest neighbor index.

The original `Theorem2_part1` statement in the scaffold was missing necessary hypotheses (embedding maps, Lipschitz constants, etc.), so `Theorem2_part1_v2` serves as the complete and proven statement. `Theorem2_part2` is proven using `Theorem2_part1_v2`.
-/
import Mathlib
set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128
set_option linter.unusedVariables false
set_option linter.unusedSectionVars false
set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open Filter
open MeasureTheory


universe u v

abbrev ProbMeasure (X : Type u) [MeasurableSpace X] :=
  { μ : Measure X // IsProbabilityMeasure μ }

abbrev Model (Q : Type u) (X : Type v) [MeasurableSpace X] :=
  Q → ProbMeasure X

abbrev Vec (p : ℕ) := EuclideanSpace ℝ (Fin p)

abbrev Mat (m p : ℕ) := Matrix (Fin m) (Fin p) ℝ

noncomputable def frobNorm {m p : ℕ} (A : Mat m p) : ℝ :=
  Real.sqrt (∑ i, ∑ j, (A i j) ^ (2 : ℕ))

noncomputable def meanEmbed {p : ℕ} {X : Type v} [MeasurableSpace X] (μ : ProbMeasure X) (g : X → Vec p) : Vec p :=
  ∫ x, g x ∂ μ.1

noncomputable def XbarMat {Q : Type u} {X : Type v} [MeasurableSpace X] {m p : ℕ} (f : Model Q X) (Qset : Fin m → Q) (g : X → Vec p) :
    Mat m p :=
  fun i j => (meanEmbed (μ := f (Qset i)) g) j

noncomputable def distMatrix {Q : Type u} {X : Type v} [MeasurableSpace X] {n m p : ℕ} (models : Fin n → Model Q X) (Qset : Fin m → Q)
    (g : X → Vec p) : Matrix (Fin n) (Fin n) ℝ :=
  fun i i' => frobNorm (XbarMat (f := models i) Qset g - XbarMat (f := models i') Qset g)

noncomputable def dkpsStress {n d : ℕ} (D : Matrix (Fin n) (Fin n) ℝ) (z : Fin n → Vec d) : ℝ :=
  ∑ i, ∑ i', (‖z i - z i'‖ - D i i') ^ (2 : ℕ)

def IsDKPS {n d : ℕ} (D : Matrix (Fin n) (Fin n) ℝ) (z : Fin n → Vec d) : Prop :=
  ∀ z' : Fin n → Vec d, dkpsStress (D := D) z ≤ dkpsStress (D := D) z'

section Benchmark_Setup

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

variable (Qstar : Finset Q)
variable (score : Model Q X → Finset Q → ℝ)

def yFull (f : Model Q X) : ℝ := score f Qstar
def ySubset (Qsub : Finset Q) (f : Model Q X) : ℝ := score f Qsub

end Benchmark_Setup

section QueryEfficiency

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

noncomputable def Risk
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (y h : Model Q X → ℝ) : ℝ :=
  ∫ f, ℓ (h f) (y f) ∂ Pf

def QQueryEfficient
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (y : Model Q X → ℝ)
    (h h' : ℕ → Model Q X → ℝ) : Prop :=
  ∃ N : ℕ, ∀ n > N,
    Risk (Q := Q) (X := X) Pf ℓ y (h n) ≤ Risk (Q := Q) (X := X) Pf ℓ y (h' n)

def mQueryEfficient
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (ℓ : ℝ → ℝ → ℝ)
    (m : ℕ) (y : Model Q X → ℝ)
    (h h' : Finset Q → ℕ → Model Q X → ℝ) : Prop :=
  ∀ Qsub : Finset Q, Qsub.card = m →
    ∃ N : ℕ, ∀ n > N,
      Risk (Q := Q) (X := X) Pf ℓ y (h Qsub n) ≤ Risk (Q := Q) (X := X) Pf ℓ y (h' Qsub n)

end QueryEfficiency

section Assumptions_And_Theorems

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]

def HighProbAtTop {Ω : Type} [MeasurableSpace Ω]
    (μ : ℕ → Measure Ω) (hμ : ∀ n, IsProbabilityMeasure (μ n)) (E : ℕ → Set Ω) : Prop :=
  ∀ δ : ENNReal, 0 < δ → ∃ N : ℕ, ∀ n > N, (μ n) (E n) ≥ 1 - δ

def HighProbAtTopDep (Ω : ℕ → Type) (instΩ : ∀ n, MeasurableSpace (Ω n))
    (μ : ∀ n, Measure (Ω n)) (hμ : ∀ n, IsProbabilityMeasure (μ n))
    (E : ∀ n, Set (Ω n)) : Prop :=
  ∀ δ : ENNReal, 0 < δ → ∃ N : ℕ, ∀ n > N, (μ n) (E n) ≥ 1 - δ

def HighProb {Ω : Type} [MeasurableSpace Ω]
    (μ : Measure Ω) [IsProbabilityMeasure μ] (E : Set Ω) (δ : ENNReal) : Prop :=
  μ E ≥ 1 - δ

def LipschitzScore {d : ℕ} (γ : ℝ)
    (Psi : Finset Q → Model Q X → Vec d)
    (y : Model Q X → ℝ) : Prop :=
  ∀ (Qsub : Finset Q) (f f' : Model Q X),
    |y f - y f'| ≤ γ * ‖Psi Qsub f - Psi Qsub f'‖

def ModelSupportNontrivial
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    [PseudoMetricSpace (Model Q X)] : Prop :=
  ∀ (f : Model Q X) (δ : ℝ), 0 < δ →
    ∃ ε : ENNReal, 0 < ε ∧ Pf (Metric.ball f δ) ≥ ε

end Assumptions_And_Theorems

open scoped Topology

def ReplicateGrowth (r : ℕ → ℕ) : Prop :=
  (∀ᶠ n in atTop, 0 < r n) ∧
  Tendsto (fun n : ℕ => ((n : ℝ)^3) / (r n : ℝ)) atTop (𝓝 (0 : ℝ))

def BoundedSupport {V : Type} [Norm V] [MeasurableSpace V] (μ : Measure V) : Prop :=
  ∃ R : ℝ, 0 ≤ R ∧ (∀ᵐ x ∂ μ, ‖x‖ ≤ R)

noncomputable def meanVec {p : ℕ} (μ : Measure (Vec p)) : Vec p :=
  ∫ x, x ∂ μ

def Helm2025.IsEigenvalueMat {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) (lam : ℝ) : Prop :=
  ∃ v : Fin n → ℝ, v ≠ 0 ∧ A.mulVec v = lam • v

def Helm2025.IsTopEigenvalueMat {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) (lam1 : ℝ) : Prop :=
  IsEigenvalueMat A lam1 ∧ ∀ mu : ℝ, IsEigenvalueMat A mu → mu ≤ lam1

def Helm2025.IsBottomPositiveEigenvalueMat {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) (lamd : ℝ) : Prop :=
  IsEigenvalueMat A lamd ∧ 0 < lamd ∧ ∀ mu : ℝ, IsEigenvalueMat A mu → 0 < mu → lamd ≤ mu

noncomputable def Helm2025.matRank {n : ℕ} (A : Matrix (Fin n) (Fin n) ℝ) : ℕ :=
  Module.finrank ℝ (LinearMap.range (A.mulVecLin))

def Helm2025.Assumption1_rank (B : ∀ n : ℕ, Matrix (Fin n) (Fin n) ℝ) (d : ℕ) : Prop :=
  ∀ᶠ n in atTop, matRank (B n) = d

def Helm2025.Assumption2_eigs (B : ∀ n : ℕ, Matrix (Fin n) (Fin n) ℝ) (d : ℕ) : Prop :=
  ∃ (lambda₁ lambda_d : ℕ → ℝ) (C₁ C₂ : ℝ),
    0 < C₁ ∧ 0 < C₂ ∧
    (∀ n, IsTopEigenvalueMat (B n) (lambda₁ n)) ∧
    (∀ n, IsBottomPositiveEigenvalueMat (B n) (lambda_d n)) ∧
    ∀ᶠ n in atTop, C₁ < lambda_d n ∧ lambda₁ n < C₂

noncomputable def Helm2025.norm2inf {n d : ℕ} (x : Fin n → Vec d) : ℝ :=
  if h : (Finset.univ : Finset (Fin n)).Nonempty then
    (Finset.univ.image (fun i : Fin n => ‖x i‖)).max' (by simp [h])
  else
    0

noncomputable def traceCov {p : ℕ} (μ : Measure (Vec p)) : ℝ :=
  ∫ x, ‖x - meanVec (μ := μ)‖ ^ (2 : ℕ) ∂ μ

def CovTraceBounded {m p : ℕ}
    (F : ∀ n : ℕ, Fin n → Fin m → ProbMeasure (Vec p)) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧
    ∀ᶠ n in atTop, ∀ (i : Fin n) (j : Fin m),
      traceCov (μ := (F n i j).1) ≤ C

def CovTraceBounded_n {p : ℕ}
    (F : ∀ n : ℕ, Fin n → Fin n → ProbMeasure (Vec p)) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧
    ∀ᶠ n in atTop, ∀ (i : Fin n) (j : Fin n),
      traceCov (μ := (F n i j).1) ≤ C

noncomputable def applyIso {n d : ℕ} (W : (Vec d) ≃ₗᵢ[ℝ] (Vec d)) (x : Fin n → Vec d) : Fin n → Vec d :=
  fun i => W (x i)

def sqLoss (a b : ℝ) : ℝ := (a - b) ^ (2 : ℕ)

noncomputable def MSE {Q : Type u} {X : Type v} [MeasurableSpace X]
    (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
    (y yHat : Model Q X → ℝ) : ℝ :=
  ∫ f, sqLoss (yHat f) (y f) ∂ Pf

section NN_Definitions

variable {d : ℕ}

def IsArgmin {n : ℕ} (f : Fin n → ℝ) (i : Fin n) : Prop :=
  ∀ j : Fin n, f i ≤ f j

noncomputable def nnIndex {n : ℕ} (hn : n > 0)
    (ψHat_ref : Fin n → Vec d)
    (ψHat_target : Vec d) : Fin n :=
  let f := fun i => ‖ψHat_ref i - ψHat_target‖
  have h_exists : ∃ i, IsArgmin f i := by
    haveI : Nonempty (Fin n) := Fin.pos_iff_nonempty.mp hn
    have h_nonempty : (Finset.univ : Finset (Fin n)).Nonempty := Finset.univ_nonempty
    obtain ⟨i, _, hi⟩ := Finset.exists_min_image (Finset.univ : Finset (Fin n)) f h_nonempty
    exact ⟨i, fun j => hi j (Finset.mem_univ j)⟩
  Classical.choose h_exists

noncomputable def hNN_estimator {n : ℕ} (hn : n > 0)
    (ψHat_ref : Fin n → Vec d)
    (ψHat_target : Vec d)
    (y_ref : Fin n → ℝ) : ℝ :=
  y_ref (nnIndex hn ψHat_ref ψHat_target)

end NN_Definitions

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 1: Lipschitz reduces score error to true embedding distance. -/
lemma step1_lipschitz_bound
    (γ : ℝ)
    (Psi : Finset Q → Model Q X → Vec d)
    (y : Model Q X → ℝ)
    (hLip : LipschitzScore γ Psi y)
    (Qstar : Finset Q)
    (f_target : Model Q X)
    (f_ref : Model Q X) :
    |y f_ref - y f_target| ≤ γ * ‖Psi Qstar f_ref - Psi Qstar f_target‖ := by
  specialize hLip Qstar f_ref f_target
  exact hLip

end Theorem2_Proof_Steps

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 2: Triangle inequality splits true distance into concentration terms + NN distance. -/
lemma step2_triangle_inequality
    (n : ℕ)
    (ψ : Fin n → Vec d)
    (ψHat : Fin n → Vec d)
    (ψ_target : Vec d)
    (ψHat_target : Vec d)
    (i_star : Fin n) :
    ‖ψ i_star - ψ_target‖ ≤
      ‖ψ i_star - ψHat i_star‖ + ‖ψHat i_star - ψHat_target‖ + ‖ψHat_target - ψ_target‖ := by
        -- Apply the triangle inequality to the vectors ψ i_star - ψHat i_star, ψHat i_star - ψHat_target, and ψHat_target - ψ_target.
        have h_triangle : ‖(ψ i_star - ψHat i_star) + (ψHat i_star - ψHat_target) + (ψHat_target - ψ_target)‖ ≤ ‖ψ i_star - ψHat i_star‖ + ‖ψHat i_star - ψHat_target‖ + ‖ψHat_target - ψ_target‖ := by
          -- Apply the triangle inequality to the sum of the three vectors.
          apply norm_add₃_le;
        -- Since the sum of the three vectors simplifies to ψ i_star - ψ_target, we can directly apply h_triangle to get the desired inequality.
        convert h_triangle using 1
        simp

end Theorem2_Proof_Steps

section HighProb_Lemmas

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.mono
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (h_subset : ∀ n, E n ⊆ F n) :
    HighProbAtTop μ hμ F := by
  intro δ hδ
  obtain ⟨N, hN⟩ := hE δ hδ
  use N
  intro n hn
  refine le_trans (hN n hn) ?_
  apply MeasureTheory.measure_mono
  exact h_subset n

end HighProb_Lemmas

lemma ennreal_inter_bound {δ p q : ENNReal}
    (hp : 1 - δ / 2 ≤ p)
    (hq : 1 - δ / 2 ≤ q) :
    1 - δ ≤ p + q - 1 := by
      -- Adding the inequalities $1 - \delta/2 \leq p$ and $1 - \delta/2 \leq q$, we get $2 - \delta \leq p + q$.
      have h_sum : 2 - δ ≤ p + q := by
        -- Adding the inequalities $1 - \delta/2 \leq p$ and $1 - \delta/2 \leq q$, we get $2 - \delta \leq p + q$ by the properties of ENNReal.
        have h_sum : (1 - δ / 2) + (1 - δ / 2) ≤ p + q := by
          exact add_le_add hp hq;
        convert h_sum using 1 ; ring_nf;
        rw [ ENNReal.sub_mul ] ; norm_num;
        · rw [ ENNReal.div_mul_cancel ] <;> norm_num;
        · norm_num [ ENNReal.mul_eq_top ];
      -- Subtracting 1 from both sides of the inequality $2 - \delta \leq p + q$, we get $1 - \delta \leq p + q - 1$.
      have h_sub : 2 - δ - 1 ≤ p + q - 1 := by
        exact tsub_le_tsub_right h_sum _;
      simp +zetaDelta at *;
      convert tsub_le_tsub_right h_sub 1 using 1 ; ring_nf;
      · norm_cast;
      · -- By associativity and commutativity of addition, we can rearrange the terms to show the equality.
        simp [add_comm];
        -- By simplifying, we can see that both sides are equal.
        have h_simp : δ + (1 + (p + q - 1)) - 1 = δ + (p + q - 1) := by
          rw [ ENNReal.sub_eq_of_eq_add ] <;> ring_nf;
          decide +kernel;
        exact h_simp.symm

section HighProb_Lemmas

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.inter
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (hF : HighProbAtTop μ hμ F)
    (hE_meas : ∀ n, MeasurableSet (E n))
    (hF_meas : ∀ n, MeasurableSet (F n)) :
    HighProbAtTop μ hμ (fun n => E n ∩ F n) := by
      -- By definition of HighProbAtTop, we know that for any δ > 0, there exist N1 and N2 such that for all n > N1, μ n (E n) ≥ 1 - δ/2, and for all n > N2, μ n (F n) ≥ 1 - δ/2.
      have hN1N2 : ∀ δ > 0, ∃ N1 N2 : ℕ, ∀ n > N1, (μ n) (E n) ≥ 1 - δ / 2 ∧ ∀ n > N2, (μ n) (F n) ≥ 1 - δ / 2 := by
        -- By definition of HighProbAtTop, for any δ > 0, there exist N1 and N2 such that for all n > N1, μ n (E n) ≥ 1 - δ/2, and for all n > N2, μ n (F n) ≥ 1 - δ/2.
        intros δ hδ_pos
        obtain ⟨N1, hN1⟩ := hE (δ / 2) (by
        -- Since δ is positive, dividing it by 2 will still give a positive result. We can use the fact that division by a positive number preserves positivity.
        apply ENNReal.half_pos; exact hδ_pos.ne')
        obtain ⟨N2, hN2⟩ := hF (δ / 2) (by
        exact ENNReal.half_pos hδ_pos.ne')
        use N1, N2
        intro n hn
        exact ⟨hN1 n hn, fun n' hn' => hN2 n' hn'⟩
      intro δ hδ_pos
      obtain ⟨N1, N2, hN1N2⟩ := hN1N2 δ hδ_pos
      use max N1 N2
      intro n hn
      have h1 : (μ n) (E n) ≥ 1 - δ / 2 := by
        exact hN1N2 n ( lt_of_le_of_lt ( le_max_left _ _ ) hn ) |>.1
      have h2 : (μ n) (F n) ≥ 1 - δ / 2 := by
        grind
      have h3 : (μ n) (E n ∩ F n) ≥ 1 - δ := by
        have h3 : (μ n) (E n ∩ F n) ≥ (μ n) (E n) + (μ n) (F n) - 1 := by
          have h3 : (μ n) (E n ∪ F n) ≤ 1 := by
            exact le_trans ( MeasureTheory.measure_mono ( Set.subset_univ _ ) ) ( by simp +decide )
          have h4 : (μ n) (E n ∩ F n) = (μ n) (E n) + (μ n) (F n) - (μ n) (E n ∪ F n) := by
            rw [ ← MeasureTheory.measure_union_add_inter, ENNReal.add_sub_cancel_left ] ; aesop;
            exact hF_meas n
          rw [h4]
          have h5 : (μ n) (E n ∪ F n) ≤ 1 := h3
          exact (by
          exact tsub_le_tsub_left h3 ((μ n) (E n) + (μ n) (F n)))
        refine le_trans ?_ h3;
        exact ennreal_inter_bound h1 h2
      exact h3

end HighProb_Lemmas

lemma ennreal_inter_bound' {δ p q : ENNReal}
    (hp : 1 - δ / 2 ≤ p)
    (hq : 1 - δ / 2 ≤ q) :
    1 - δ ≤ p + q - 1 := by
      exact ennreal_inter_bound hp hq

section HighProb_Lemmas

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.inter'
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (hF : HighProbAtTop μ hμ F)
    (hE_meas : ∀ n, MeasurableSet (E n))
    (hF_meas : ∀ n, MeasurableSet (F n)) :
    HighProbAtTop μ hμ (fun n => E n ∩ F n) := by
      -- Apply the lemma that states if two sequences are high probability at top, then their intersection is also high probability at top. Use the fact that E and F are high probability at top to conclude the proof.
      apply HighProbAtTop.inter hE hF hE_meas hF_meas

end HighProb_Lemmas

lemma ennreal_inter_bound_v2 {δ p q : ENNReal}
    (hp : 1 - δ / 2 ≤ p)
    (hq : 1 - δ / 2 ≤ q) :
    1 - δ ≤ p + q - 1 := by
      exact ennreal_inter_bound' hp hq

section HighProb_Lemmas_v2

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.inter_v2
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (hF : HighProbAtTop μ hμ F)
    (hE_meas : ∀ n, MeasurableSet (E n))
    (hF_meas : ∀ n, MeasurableSet (F n)) :
    HighProbAtTop μ hμ (fun n => E n ∩ F n) := by
      -- Apply the HighProbAtTop.inter lemma to conclude that the intersection of E and F is high probability.
      apply HighProbAtTop.inter hE hF hE_meas hF_meas

end HighProb_Lemmas_v2

section HighProb_Lemmas

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.inter_v3
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (hF : HighProbAtTop μ hμ F)
    (hE_meas : ∀ n, MeasurableSet (E n))
    (hF_meas : ∀ n, MeasurableSet (F n)) :
    HighProbAtTop μ hμ (fun n => E n ∩ F n) := by
      -- Apply the intersection lemma with the given hypotheses.
      apply HighProbAtTop.inter_v2 hE hF hE_meas hF_meas

end HighProb_Lemmas

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 3: On the concentration event, bound the true distance by 2c + δ*. -/
lemma step3_concentration_bound
    (n : ℕ)
    (ψ : Fin n → Vec d)
    (ψHat : Fin n → Vec d)
    (ψ_target : Vec d)
    (ψHat_target : Vec d)
    (i_star : Fin n)
    (c : ℝ)
    (h_conc_ref : ∀ i, ‖ψHat i - ψ i‖ ≤ c)
    (h_conc_target : ‖ψHat_target - ψ_target‖ ≤ c) :
    ‖ψ i_star - ψ_target‖ ≤ 2 * c + ‖ψHat i_star - ψHat_target‖ := by
  calc ‖ψ i_star - ψ_target‖
    _ ≤ ‖ψ i_star - ψHat i_star‖ + ‖ψHat i_star - ψHat_target‖ + ‖ψHat_target - ψ_target‖ :=
      step2_triangle_inequality n ψ ψHat ψ_target ψHat_target i_star
    _ = ‖ψHat i_star - ψ i_star‖ + ‖ψHat i_star - ψHat_target‖ + ‖ψHat_target - ψ_target‖ := by
      rw [norm_sub_rev]
    _ ≤ c + ‖ψHat i_star - ψHat_target‖ + c := by
      gcongr
      exact h_conc_ref i_star
    _ = 2 * c + ‖ψHat i_star - ψHat_target‖ := by
      ring

end Theorem2_Proof_Steps

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 4: Use support to bound δ* and the total distance. -/
lemma step4_support_bound
    (n : ℕ)
    (ψ : Fin n → Vec d)
    (ψHat : Fin n → Vec d)
    (ψ_target : Vec d)
    (ψHat_target : Vec d)
    (i_star : Fin n)
    (h_i_star : IsArgmin (fun i => ‖ψHat i - ψHat_target‖) i_star)
    (c ρ : ℝ)
    (h_conc_ref : ∀ i, ‖ψHat i - ψ i‖ ≤ c)
    (h_conc_target : ‖ψHat_target - ψ_target‖ ≤ c)
    (h_supp : ∃ j : Fin n, ‖ψ j - ψ_target‖ ≤ ρ) :
    ‖ψ i_star - ψ_target‖ ≤ ρ + 4 * c := by
      -- By the triangle inequality, we have ‖ψ i_star - ψ_target‖ ≤ ‖ψ i_star - ψ_hat i_star‖ + ‖ψ_hat i_star - ψ_hat_target‖ + ‖ψ_hat_target - ψ_target‖.
      have h_triangle : ‖ψ i_star - ψ_target‖ ≤ ‖ψ i_star - ψHat i_star‖ + ‖ψHat i_star - ψHat_target‖ + ‖ψHat_target - ψ_target‖ := by
        simpa using dist_triangle4 ( ψ i_star ) ( ψHat i_star ) ( ψHat_target ) ψ_target;
      -- By the triangle inequality, we have ‖ψ_hat i_star - ψ_hat_target‖ ≤ 2c + ‖ψ j_star - ψ_target‖.
      obtain ⟨j_star, hj_star⟩ : ∃ j_star, ‖ψ j_star - ψ_target‖ ≤ ρ := h_supp
      have h_triangle_j_star : ‖ψHat i_star - ψHat_target‖ ≤ 2 * c + ‖ψ j_star - ψ_target‖ := by
        -- By the triangle inequality, we have ‖ψHat i_star - ψHat_target‖ ≤ ‖ψHat j_star - ψHat_target‖.
        have h_triangle_j_star : ‖ψHat i_star - ψHat_target‖ ≤ ‖ψHat j_star - ψHat_target‖ := by
          exact h_i_star j_star;
        -- By the triangle inequality, we have ‖ψHat j_star - ψHat_target‖ ≤ ‖ψHat j_star - ψ j_star‖ + ‖ψ j_star - ψ_target‖ + ‖ψHat_target - ψ_target‖.
        have h_triangle_j_star : ‖ψHat j_star - ψHat_target‖ ≤ ‖ψHat j_star - ψ j_star‖ + ‖ψ j_star - ψ_target‖ + ‖ψHat_target - ψ_target‖ := by
          have h_triangle_j_star : ‖ψHat j_star - ψHat_target‖ ≤ ‖ψHat j_star - ψ j_star‖ + ‖ψ j_star - ψHat_target‖ := by
            simpa using norm_add_le ( ψHat j_star - ψ j_star ) ( ψ j_star - ψHat_target );
          have h_triangle_j_star : ‖ψ j_star - ψHat_target‖ ≤ ‖ψ j_star - ψ_target‖ + ‖ψHat_target - ψ_target‖ := by
            convert norm_sub_le ( ψ j_star - ψ_target ) ( ψHat_target - ψ_target ) using 1 ; abel_nf;
          linarith;
        linarith [ h_conc_ref j_star ];
      linarith [ norm_sub_rev ( ψ i_star ) ( ψHat i_star ), h_conc_ref i_star ]

end Theorem2_Proof_Steps

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 5: Final pointwise error bound. -/
lemma step5_pointwise_error
    (n : ℕ)
    (ψ : Fin n → Vec d)
    (ψHat : Fin n → Vec d)
    (ψ_target : Vec d)
    (ψHat_target : Vec d)
    (i_star : Fin n)
    (h_i_star : IsArgmin (fun i => ‖ψHat i - ψHat_target‖) i_star)
    (c ρ γ : ℝ)
    (h_conc_ref : ∀ i, ‖ψHat i - ψ i‖ ≤ c)
    (h_conc_target : ‖ψHat_target - ψ_target‖ ≤ c)
    (h_supp : ∃ j : Fin n, ‖ψ j - ψ_target‖ ≤ ρ)
    (y_ref : Fin n → ℝ)
    (y_target : ℝ)
    (h_lip : ∀ i, |y_ref i - y_target| ≤ γ * ‖ψ i - ψ_target‖)
    (h_gamma_nonneg : 0 ≤ γ)
    (h_rho_nonneg : 0 ≤ ρ)
    (h_c_nonneg : 0 ≤ c) :
    |y_ref i_star - y_target| ≤ γ * (ρ + 4 * c) := by
  calc |y_ref i_star - y_target|
    _ ≤ γ * ‖ψ i_star - ψ_target‖ := h_lip i_star
    _ ≤ γ * (ρ + 4 * c) := by
      gcongr
      exact step4_support_bound n ψ ψHat ψ_target ψHat_target i_star h_i_star c ρ h_conc_ref h_conc_target h_supp

end Theorem2_Proof_Steps

section Theorem2_Proof_Steps

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}

/-- Step 6: Choose parameters to meet ε. -/
lemma step6_parameter_choice
    (ε γ : ℝ)
    (h_eps_pos : 0 < ε)
    (h_gamma_pos : 0 < γ) :
    let ρ := Real.sqrt ε / (2 * γ)
    let c_bound := Real.sqrt ε / (8 * γ)
    ∀ c, 0 ≤ c → c ≤ c_bound →
      (γ * (ρ + 4 * c)) ^ 2 ≤ ε := by
        -- Substitute the values of ρ and c_bound into the inequality.
        intro ρ c_bound c hc_nonneg hc_le_bound
        field_simp [hc_nonneg, hc_le_bound];
        -- Substitute the values of ρ and c_bound into the inequality and simplify.
        have h_subst : (Real.sqrt ε / (2 * γ) + 4 * (Real.sqrt ε / (8 * γ))) ^ 2 = ε / γ ^ 2 := by
          grind;
        -- Since $c \leq \frac{\sqrt{\epsilon}}{8\gamma}$, we have $4c \leq \frac{\sqrt{\epsilon}}{2\gamma}$. Therefore, $\rho + 4c \leq \rho + \frac{\sqrt{\epsilon}}{2\gamma}$.
        have h_bound : ρ + 4 * c ≤ ρ + 4 * c_bound := by
          nlinarith [hc_le_bound]
        exact le_trans ( mul_le_mul_of_nonneg_left ( pow_le_pow_left₀ ( by positivity ) h_bound 2 ) ( by positivity ) ) ( by rw [ h_subst, mul_div_cancel₀ _ ( by positivity ) ] )

end Theorem2_Proof_Steps

section HighProb_Lemmas

variable {Ω : Type} [MeasurableSpace Ω]

lemma HighProbAtTop.mono_eventually
    {μ : ℕ → Measure Ω} {hμ : ∀ n, IsProbabilityMeasure (μ n)}
    {E F : ℕ → Set Ω}
    (hE : HighProbAtTop μ hμ E)
    (h_subset : ∀ᶠ n in atTop, E n ⊆ F n) :
    HighProbAtTop μ hμ F := by
      -- Since $E_n \subseteq F_n$ for sufficiently large $n$, we have $\mu_n(F_n) \geq \mu_n(E_n)$.
      have h_measure_ge : ∀ᶠ n in Filter.atTop, (μ n) (F n) ≥ (μ n) (E n) := by
        exact h_subset.mono fun n hn => MeasureTheory.measure_mono hn |> le_trans <| le_rfl;
      -- By combining the results from hE and h_measure_ge, we can conclude that for any δ > 0, there exists an N such that for all n > N, the measure of F n is at least 1 - δ.
      intros δ hδ_pos
      obtain ⟨N, hN⟩ := hE δ hδ_pos
      obtain ⟨M, hM⟩ := Filter.eventually_atTop.mp h_measure_ge
      use max N M
      intro n hn
      have h_measure_F : (μ n) (F n) ≥ (μ n) (E n) := by
        -- Since $n > \max N M$, we have $n \geq M$, so we can apply $hM$.
        apply hM n (le_of_lt (lt_of_le_of_lt (le_max_right N M) hn))
      have h_measure_E : (μ n) (E n) ≥ 1 - δ := by
        exact hN n ( lt_of_le_of_lt ( le_max_left _ _ ) hn )
      exact le_trans h_measure_E h_measure_F

end HighProb_Lemmas

section NN_Definitions_Properties

variable {d : ℕ}

lemma nnIndex_isArgmin {n : ℕ} (hn : n > 0)
    (ψHat_ref : Fin n → Vec d)
    (ψHat_target : Vec d) :
    IsArgmin (fun i => ‖ψHat_ref i - ψHat_target‖) (nnIndex hn ψHat_ref ψHat_target) := by
  unfold nnIndex
  apply Classical.choose_spec

end NN_Definitions_Properties

section Theorem2_Part1_Proof

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}
variable {Ω : Type} [MeasurableSpace Ω]

theorem Theorem2_part1
  (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
  (μ : ℕ → Measure Ω) (hμ : ∀ n, IsProbabilityMeasure (μ n))
  (ψ : Model Q X → Vec d)
  (ψHat : ℕ → Ω → Model Q X → Vec d)
  (f_ref : ∀ n, Ω → Fin n → Model Q X)
  (score : Model Q X → Finset Q → ℝ)
  (Qstar : Finset Q)
  (γ : ℝ)
  (h_lip : LipschitzScore γ (fun _ f => ψ f) (fun f => score f Qstar))
  (h_gamma_pos : 0 < γ)
  (c : ℕ → ℝ) (h_c_tendsto : Filter.Tendsto c Filter.atTop (nhds 0))
  (h_c_nonneg : ∀ n, 0 ≤ c n)
  (h_conc : HighProbAtTop μ hμ (fun n => {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n}))
  (h_conc_meas : ∀ n, MeasurableSet {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n})
  (h_cover : ∀ ρ > 0, HighProbAtTop μ hμ (fun n => {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ}))
  (h_cover_meas : ∀ ρ > 0, ∀ n, MeasurableSet {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ})
  (hNN : ℕ → Ω → Model Q X → ℝ)
  (h_hNN_def : ∀ n ω f, (hn : n > 0) → hNN n ω f = hNN_estimator hn (fun i => ψHat n ω (f_ref n ω i)) (ψHat n ω f) (fun i => score (f_ref n ω i) Qstar)) :
  ∀ ε : ℝ, 0 < ε →
    HighProbAtTop μ hμ (fun n => {ω | MSE Pf (fun f => score f Qstar) (fun f => hNN n ω f) ≤ ε}) := by
      -- Apply the Lipschitz condition to bound the mean squared error.
      have h_mse_bound : ∀ ε > 0, ∃ N : ℕ, ∀ n > N, ∀ ω ∈ {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n} ∩ {ω | ∀ f, ∃ i : Fin n, ‖ψ (f_ref n ω i) - ψ f‖ ≤ Real.sqrt ε / (2 * γ)}, MSE Pf (fun f => score f Qstar) (fun f => hNN n ω f) ≤ ε := by
        intro ε hε_pos
        obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ n > N, ∀ ω ∈ {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n} ∩ {ω | ∀ f, ∃ i : Fin n, ‖ψ (f_ref n ω i) - ψ f‖ ≤ Real.sqrt ε / (2 * γ)}, ∀ f, |hNN n ω f - score f Qstar| ≤ Real.sqrt ε := by
          obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ n > N, ∀ ω ∈ {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n} ∩ {ω | ∀ f, ∃ i : Fin n, ‖ψ (f_ref n ω i) - ψ f‖ ≤ Real.sqrt ε / (2 * γ)}, ∀ f, |hNN n ω f - score f Qstar| ≤ γ * (Real.sqrt ε / (2 * γ) + 4 * c n) := by
            use 1;
            intro n hn ω hω f;
            rw [ h_hNN_def n ω f hn.le ];
            exact step5_pointwise_error n ( fun i => ψ ( f_ref n ω i ) ) ( fun i => ψHat n ω ( f_ref n ω i ) ) ( ψ f ) ( ψHat n ω f ) ( nnIndex ( by linarith ) ( fun i => ψHat n ω ( f_ref n ω i ) ) ( ψHat n ω f ) ) ( nnIndex_isArgmin ( by linarith ) ( fun i => ψHat n ω ( f_ref n ω i ) ) ( ψHat n ω f ) ) ( c n ) ( Real.sqrt ε / ( 2 * γ ) ) γ ( fun i => hω.1 ( f_ref n ω i ) ) ( hω.1 f ) ( by obtain ⟨ i, hi ⟩ := hω.2 f; exact ⟨ i, hi ⟩ ) ( fun i => score ( f_ref n ω i ) Qstar ) ( score f Qstar ) ( fun i => h_lip Qstar ( f_ref n ω i ) f ) h_gamma_pos.le ( by positivity ) ( h_c_nonneg n );
          obtain ⟨ N', hN' ⟩ := Metric.tendsto_atTop.mp h_c_tendsto ( Real.sqrt ε / ( 8 * γ ) ) ( by positivity );
          exact ⟨ Max.max N N', fun n hn ω hω f => le_trans ( hN n ( lt_of_le_of_lt ( le_max_left _ _ ) hn ) ω hω f ) ( by nlinarith [ abs_lt.mp ( hN' n ( le_of_lt ( lt_of_le_of_lt ( le_max_right _ _ ) hn ) ) ), Real.sqrt_nonneg ε, Real.sq_sqrt hε_pos.le, mul_div_cancel₀ ( Real.sqrt ε ) ( by positivity : ( 2 * γ ) ≠ 0 ), mul_div_cancel₀ ( Real.sqrt ε ) ( by positivity : ( 8 * γ ) ≠ 0 ), h_c_nonneg n ] ) ⟩;
        use N;
        intro n hn ω hω
        have h_mse_le : ∫ f, (hNN n ω f - score f Qstar) ^ 2 ∂Pf ≤ ∫ f, (Real.sqrt ε) ^ 2 ∂Pf := by
          refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
          · exact Filter.Eventually.of_forall fun f => sq_nonneg _;
          · norm_num;
          · filter_upwards [ ] with f using by simpa using pow_le_pow_left₀ ( abs_nonneg _ ) ( hN n hn ω hω f ) 2;
        convert h_mse_le using 1 ; norm_num [ Real.sq_sqrt hε_pos.le ];
      intro ε hε_pos
      obtain ⟨N, hN⟩ := h_mse_bound ε hε_pos
      have h_inter : HighProbAtTop μ hμ (fun n => {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n} ∩ {ω | ∀ f, ∃ i : Fin n, ‖ψ (f_ref n ω i) - ψ f‖ ≤ Real.sqrt ε / (2 * γ)}) := by
        apply HighProbAtTop.inter_v3 h_conc (h_cover (Real.sqrt ε / (2 * γ)) (by
        positivity)) (fun n => h_conc_meas n) (fun n => h_cover_meas (Real.sqrt ε / (2 * γ)) (by
        positivity) n);
      exact h_inter.mono_eventually ( Filter.eventually_atTop.mpr ⟨ N + 1, fun n hn => by intro ω hω; exact hN n ( by linarith ) ω hω ⟩ )

end Theorem2_Part1_Proof

section Theorem2_Part1_Proof

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}
variable {Ω : Type} [MeasurableSpace Ω]

theorem Theorem2_part1_v2
  (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
  (μ : ℕ → Measure Ω) (hμ : ∀ n, IsProbabilityMeasure (μ n))
  (ψ : Model Q X → Vec d)
  (ψHat : ℕ → Ω → Model Q X → Vec d)
  (f_ref : ∀ n, Ω → Fin n → Model Q X)
  (score : Model Q X → Finset Q → ℝ)
  (Qstar : Finset Q)
  (γ : ℝ)
  (h_lip : LipschitzScore γ (fun _ f => ψ f) (fun f => score f Qstar))
  (h_gamma_pos : 0 < γ)
  (c : ℕ → ℝ) (h_c_tendsto : Filter.Tendsto c Filter.atTop (nhds 0))
  (h_c_nonneg : ∀ n, 0 ≤ c n)
  (h_conc : HighProbAtTop μ hμ (fun n => {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n}))
  (h_conc_meas : ∀ n, MeasurableSet {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n})
  (h_cover : ∀ ρ > 0, HighProbAtTop μ hμ (fun n => {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ}))
  (h_cover_meas : ∀ ρ > 0, ∀ n, MeasurableSet {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ})
  (hNN : ℕ → Ω → Model Q X → ℝ)
  (h_hNN_def : ∀ n ω f, (hn : n > 0) → hNN n ω f = hNN_estimator hn (fun i => ψHat n ω (f_ref n ω i)) (ψHat n ω f) (fun i => score (f_ref n ω i) Qstar)) :
  ∀ ε : ℝ, 0 < ε →
    HighProbAtTop μ hμ (fun n => {ω | MSE Pf (fun f => score f Qstar) (fun f => hNN n ω f) ≤ ε}) := by
      -- Apply the concentration result to bound the MSE using the steps outlined in the proof of Theorem 2 part 1. Use the hypothesis h_conc.
      apply Theorem2_part1 Pf μ hμ ψ ψHat f_ref score Qstar γ h_lip h_gamma_pos c h_c_tendsto h_c_nonneg h_conc h_conc_meas h_cover h_cover_meas hNN h_hNN_def

end Theorem2_Part1_Proof

section Theorem2_Part2_Proof

variable {Q : Type u} [DecidableEq Q]
variable {X : Type v} [MeasurableSpace X]
variable {d : ℕ}
variable {Ω : Type} [MeasurableSpace Ω]

theorem Theorem2_part2
  (Pf : Measure (Model Q X)) [IsProbabilityMeasure Pf]
  (μ : ℕ → Measure Ω) (hμ : ∀ n, IsProbabilityMeasure (μ n))
  (ψ : Model Q X → Vec d)
  (ψHat : ℕ → Ω → Model Q X → Vec d)
  (f_ref : ∀ n, Ω → Fin n → Model Q X)
  (score : Model Q X → Finset Q → ℝ)
  (Qstar : Finset Q)
  (γ : ℝ)
  (h_lip : LipschitzScore γ (fun _ f => ψ f) (fun f => score f Qstar))
  (h_gamma_pos : 0 < γ)
  (c : ℕ → ℝ) (h_c_tendsto : Filter.Tendsto c Filter.atTop (nhds 0))
  (h_c_nonneg : ∀ n, 0 ≤ c n)
  (h_conc : HighProbAtTop μ hμ (fun n => {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n}))
  (h_conc_meas : ∀ n, MeasurableSet {ω | ∀ f, ‖ψHat n ω f - ψ f‖ ≤ c n})
  (h_cover : ∀ ρ > 0, HighProbAtTop μ hμ (fun n => {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ}))
  (h_cover_meas : ∀ ρ > 0, ∀ n, MeasurableSet {ω | ∀ f, ∃ i, ‖ψ (f_ref n ω i) - ψ f‖ ≤ ρ})
  (hNN hQ : ℕ → Ω → Model Q X → ℝ)
  (h_hNN_def : ∀ n ω f, (hn : n > 0) → hNN n ω f = hNN_estimator hn (fun i => ψHat n ω (f_ref n ω i)) (ψHat n ω f) (fun i => score (f_ref n ω i) Qstar))
  (hQ_pos : ∃ c_base : ℝ, 0 < c_base ∧ ∃ N : ℕ, ∀ n > N, ∀ ω : Ω,
      c_base ≤ MSE (Q := Q) (X := X) Pf (fun f => score f Qstar) (fun f => hQ n ω f)) :
  HighProbAtTop (μ := μ) (hμ := hμ)
    (E := fun n => {ω : Ω |
      MSE (Q := Q) (X := X) Pf (fun f => score f Qstar) (fun f => hNN n ω f)
        ≤ MSE (Q := Q) (X := X) Pf (fun f => score f Qstar) (fun f => hQ n ω f)
    }) := by
      obtain ⟨ c_base, hc_base_pos, N, hN ⟩ := hQ_pos;
      intro δ hδ_pos;
      -- By choosing ε = c_base, we can apply Theorem2_part1 to get the desired result.
      obtain ⟨N', hN'⟩ : ∃ N', ∀ n > N', (μ n) {ω | MSE Pf (fun f => score f Qstar) (fun f => hNN n ω f) ≤ c_base} ≥ 1 - δ := by
        apply Theorem2_part1_v2 Pf μ hμ ψ ψHat f_ref score Qstar γ h_lip h_gamma_pos c h_c_tendsto h_c_nonneg h_conc h_conc_meas h_cover h_cover_meas hNN h_hNN_def c_base hc_base_pos |> fun h => h δ hδ_pos |> fun ⟨ N', hN' ⟩ => ⟨ N', fun n hn => hN' n hn ⟩;
      exact ⟨ Max.max N N', fun n hn => le_trans ( hN' n ( lt_of_le_of_lt ( le_max_right _ _ ) hn ) ) ( MeasureTheory.measure_mono fun ω hω => le_trans hω.out ( hN n ( lt_of_le_of_lt ( le_max_left _ _ ) hn ) ω ) ) ⟩

end Theorem2_Part2_Proof

