/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 349433ba-3916-4e93-9645-d242cbfa2934
To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/
/-
Formalization of Helm et al. (2025),
"Statistical inference on black-box generative models in the data kernel perspective space".

Main results:
* Theorem 1 (`risk_converges_fixed_n`): for fixed sample size `n`, the risk computed from estimated
  embeddings converges to the risk computed from true embeddings.
* Theorem 2 (`consistency_transfer_dkps`): consistency of the learning rule transfers from true
  embeddings to estimated embeddings along a suitable diagonal budget schedule.
* `diagonal_convergence`: a diagonal subsequence lemma used in Theorem 2.

Paper ↔ Lean notation:
* true embeddings ψᵢ live in the sample `ω` as `(ω i).1`
* estimated embeddings ψ̂ᵢ are `psi_hat`
* learning rule h is `learn`
* loss ℓ is `loss`
* risk Rℓ is `risk` / `risk_est`
* DKPS alignment consistency (Eq. 3) is `DKPSAlignmentConsistency`
  (in the paper, Eq. 3 is derived from boundedness of the embedding map `g`; here we assume Eq. 3).

Assumptions (paper / appendix):
* A1: `InvariantToAffineIsometries`
* A2: `ContinuousLearningRule`
* A3: `UniformlyBoundedPredictions` (bounded image of each learned decision function)
* A4: `ContinuousLoss`
* A5: `LossEnvelopeIntegrable` (integrable loss envelope on bounded prediction sets)
-/
import Mathlib
set_option linter.mathlibStandardSet false
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
set_option relaxedAutoImplicit false
set_option autoImplicit false
noncomputable section
/-
Definitions of the DKPS setting: Euclidean spaces for embeddings and labels, LearningRule type, LossFunction type, risk functional, and a helper to transform training data.
-/
open MeasureTheory Filter Topology Metric
open scoped BigOperators
variable {d d' : ℕ}
-- Paper objects:
-- True (population) model proxy embeddings: ψ_i ∈ ℝ^d.
-- Labels/covariates: y_i ∈ ℝ^{d'} (could be ℝ, {0,1}, etc).
abbrev E (d : ℕ) := EuclideanSpace ℝ (Fin d)
abbrev Y (d' : ℕ) := EuclideanSpace ℝ (Fin d')
-- A learning algorithm / decision rule: h, which predicts y for a new ψ using the training set.
-- learn : (Fin n → (E × Y)) → E → Y
def LearningRule (n : ℕ) (d d' : ℕ) := (Fin n → E d × Y d') → E d → Y d'
-- Loss ℓ : Y × Y → ℝ≥0.
def LossFunction (d' : ℕ) := Y d' → Y d' → ℝ
-- Risk (expected loss) under the distribution P_{ψY}:
-- Rℓ(P_{ψY}, h(·;T_n)) = E[ ℓ( h(ψ_{n+1}; T_n), y_{n+1} ) ]
-- where (ψ_i, y_i) are i.i.d. from P_{ψY} for i=1..n+1.
variable {n : ℕ}
/--
The risk of a learning rule `learn` under distribution `P` with loss `loss`.
We integrate over the product measure of `n+1` samples.
The first `n` samples are the training set, the `n+1`-th is the test point.
-/
def risk (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => ω (Fin.castSucc i)) (ω (Fin.last n)).1) (ω (Fin.last n)).2 ∂P_prod
/--
Helper to transform the training set by applying an affine isometry to the embeddings.
-/
def transform_training (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') : Fin n → E d × Y d' :=
  fun i => (e (t i).1, (t i).2)
/-
Definition of risk_est, the risk using estimated embeddings.
-/
/--
The risk of a learning rule `learn` using estimated embeddings `psi_hat`.
`psi_hat` takes the full sample `ω` (training + test) and returns estimated embeddings for all points.
The learning rule is trained on `(psi_hat_train, y_train)` and evaluated on `psi_hat_test`.
The loss is computed against the true label `y_test`.
-/
def risk_est (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : ℝ :=
  let P_prod := Measure.pi (fun _ : Fin (n + 1) => P)
  ∫ ω, loss (learn (fun i : Fin n => (psi_hat ω (Fin.castSucc i), (ω (Fin.castSucc i)).2)) (psi_hat ω (Fin.last n))) (ω (Fin.last n)).2 ∂P_prod
/-
Assumption A1: The learning rule is invariant to affine isometries.
-/
/--
Assumption A1: The learning rule is invariant to affine isometries.
For any affine isometry `e`, applying `e` to the training embeddings and the test embedding
does not change the prediction.
-/
def InvariantToAffineIsometries (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∀ (e : E d ≃ᵃⁱ[ℝ] E d) (t : Fin n → E d × Y d') (ψ : E d),
    learn (transform_training e t) (e ψ) = learn t ψ
/-
Definitions of assumptions and basic probabilistic convergence.
-/
/--
Assumption A2: The learning rule is continuous.
We assume standard continuity with respect to the product topology on inputs.
-/
def ContinuousLearningRule (n : ℕ) (d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  Continuous (fun (p : (Fin n → E d × Y d') × E d) => learn p.1 p.2)

/-
Assumption A3 (as stated in the paper): for each fixed training set, the image of the learned decision
function is closed, bounded, and complete.

We keep this definition for completeness, but the main development below uses `LossEnvelopeIntegrable` (Assumption A5)
 to justify the expectation step.
-/
def PaperA3_ImageClosedBoundedComplete (n d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∀ t : Fin n → E d × Y d',
    IsClosed (Set.range (learn t)) ∧
    Bornology.IsBounded (Set.range (learn t)) ∧
    IsComplete (Set.range (learn t))
/--
Assumption A4: The loss function is continuous.
-/
def ContinuousLoss (d' : ℕ) (loss : LossFunction d') : Prop :=
  Continuous (fun (p : Y d' × Y d') => loss p.1 p.2)
/-
Assumption A3 (uniform version, per authors' intent): predictions of the learning rule live in a fixed
bounded (in fact compact) subset of the label space.
-/

-- Predictions of the learning rule are contained in a fixed compact set (uniformly in training set/test point).
def UniformlyBoundedPredictions (n d d' : ℕ) (learn : LearningRule n d d') : Prop :=
  ∃ K : Set (Y d'), IsCompact K ∧ ∀ (t : Fin n → E d × Y d') (ψ : E d), learn t ψ ∈ K

/-
Assumption A5 (envelope integrability): for each bounded prediction set `K`, the loss admits an integrable
envelope as a function of the (random) label `y` under `P`.

This is equivalent in spirit to: `y ↦ sup_{ŷ∈K} |loss ŷ y|` is integrable.
We phrase it in a way that avoids `sSup` existence/measurability issues.
-/
def LossEnvelopeIntegrable (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (loss : LossFunction d') : Prop :=
  let μ : Measure (Fin (n + 1) → E d × Y d') := Measure.pi (fun _ : Fin (n + 1) => P)
  ∀ K : Set (Y d'), Bornology.IsBounded K →
    ∃ g : Y d' → ℝ,
      Integrable (fun ω : (Fin (n + 1) → E d × Y d') => g ((ω (Fin.last n)).2)) μ ∧
      (∀ y, 0 ≤ g y) ∧
      (∀ yhat ∈ K, ∀ y, |loss yhat y| ≤ g y)

/--
Convergence in probability to zero for a sequence of real-valued random variables `X u`.

We use the standard event-definition: for every `ε>0`, the probability of `{ |X u| > ε }` tends to `0`.
-/
def ConvergesInProbabilityToZero {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : ℕ → Ω → ℝ) : Prop :=
  ∀ ε > 0, Tendsto (fun u => P {ω | |X u ω| > ε}) atTop (𝓝 0)

/-
Helper lemma (Vitali / dominated convergence in probability):

If `X_u → 0` in probability and `|X_u| ≤ G` a.s. for an integrable dominating function `G`,
then `E|X_u| → 0`.

Mathlib has results of this form (via uniform integrability / convergence in measure). In this development we
treat it as a packaged lemma.
-/
axiom expectation_converges_of_prob_converges_dominated {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X : ℕ → Ω → ℝ) (G : Ω → ℝ)
    (h_meas : ∀ u, Measurable (X u))
    (h_dom  : ∀ u, ∀ᵐ ω ∂P, |X u ω| ≤ G ω)
    (hG_int : Integrable G P)
    (h_conv : ConvergesInProbabilityToZero P X) :
    Tendsto (fun u => ∫ ω, |X u ω| ∂P) atTop (𝓝 0)
/-
Assumption: DKPS alignment consistency. There exists a sequence of affine isometries such that the estimated embeddings converge to the transformed true embeddings in probability.
-/
/--
Assumption: DKPS alignment consistency.
There exists a sequence of affine isometries `e_u` such that the estimated embeddings `psi_hat`
converge to `e_u(psi_true)` uniformly over the training and test set, in probability.
-/
def DKPSAlignmentConsistency (n : ℕ) (d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d) : Prop :=
  ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) (e u (ω i).1))
/--
Lemma: Tightness of probability measures on second-countable locally compact spaces.
For any `ε > 0`, there exists a compact set `K` such that `P(Kᶜ) < ε`.
-/
lemma tightness_helper {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S : Type*} [MeasurableSpace S] [TopologicalSpace S] [BorelSpace S]
    [T2Space S] [LocallyCompactSpace S] [SecondCountableTopology S]
    (Y : Ω → S) (h_meas_Y : Measurable Y) :
    ∀ ε : ENNReal, 0 < ε → ∃ K : Set S, IsCompact K ∧ P {ω | Y ω ∉ K} < ε := by
  classical
  intro ε ε_pos
  -- pushforward
  let μ : Measure S := Measure.map Y P
  haveI : OpensMeasurableSpace S := by infer_instance
  haveI : IsFiniteMeasure μ := by infer_instance
  haveI : μ.InnerRegular := by infer_instance
  -- handle ε = ⊤ separately (then goal is trivial)
  by_cases htop : ε = ⊤
  · subst htop
    refine ⟨∅, isCompact_empty, ?_⟩
    -- P{ω | Y ω ∉ ∅} = P univ < ⊤
    -- and P univ ≠ ⊤ since P is finite (probability)
    simp [lt_top_iff_ne_top]
  -- tightness of {μ}
  have hT : IsTightMeasureSet ({μ} : Set (Measure S)) :=
    MeasureTheory.isTightMeasureSet_singleton_of_innerRegular (μ := μ)
  have hiff :=
    (MeasureTheory.isTightMeasureSet_iff_exists_isCompact_measure_compl_le
      (S := ({μ} : Set (Measure S))))
  -- positivity of ε/2 (uses your div_pos signature: a≠0 and b≠⊤)
  have half_pos : (0 : ENNReal) < ε / 2 := by
    refine ENNReal.div_pos (ne_of_gt ε_pos) ?_
    norm_num
  obtain ⟨K, hKc, hK⟩ := (hiff.mp hT) (ε / 2) half_pos
  have hμK : μ Kᶜ ≤ ε / 2 := by
    simpa using hK μ (by simp)
  refine ⟨K, hKc, ?_⟩
  have hKmeas : MeasurableSet K := hKc.measurableSet
  -- rewrite μ(Kᶜ) as P{ω | Y ω ∉ K}
  have h_event : μ (Kᶜ) = P (Y ⁻¹' K)ᶜ := by
    have hs : MeasurableSet (Kᶜ) := hKmeas.compl
    have hm : (Measure.map Y P) (Kᶜ) = P (Y ⁻¹' (Kᶜ)) :=
        MeasureTheory.Measure.map_apply (μ := P) (f := Y) h_meas_Y hs
    simpa [μ, Set.preimage_compl] using hm
  have h_le : P {ω | Y ω ∉ K} ≤ ε / 2 := by
    have hset : {ω | Y ω ∉ K} = (Y ⁻¹' K)ᶜ := by
        ext ω; rfl
    -- rewrite hμK using h_event
    have : P (Y ⁻¹' K)ᶜ ≤ ε / 2 := by
        simpa [h_event] using hμK
    simpa [hset] using this  -- prove ε/2 < ε (now we can use htop : ε ≠ ⊤)
  have hb0 : (2 : ENNReal) ≠ 0 := by norm_num
  have hbt : (2 : ENNReal) ≠ ⊤ := by norm_num
  have h_half_lt : ε / 2 < ε := by
    -- div_lt_iff: (c/b < a) ↔ (c < a*b)
    have hdiv :
        (ε / (2 : ENNReal) < ε) ↔ (ε < ε * (2 : ENNReal)) := by
      simpa using
        (ENNReal.div_lt_iff (a := ε) (b := (2 : ENNReal)) (c := ε)
          (h0 := Or.inl hb0) (ht := Or.inl hbt))
    -- show ε < ε*2 via mul strictness on the right
    have h1lt2 : (1 : ENNReal) < (2 : ENNReal) := by norm_num
    have hmul : ε * (1 : ENNReal) < ε * (2 : ENNReal) := by
      -- mul_lt_mul_right: multiply strict inequality on the right by ε
      -- signature in your build: mul_lt_mul_left / left' exist; right should exist per deprecation note.
      simpa [mul_assoc] using (ENNReal.mul_lt_mul_right (a := ε) (h0 := ne_of_gt ε_pos) (hinf := htop) h1lt2)
    have : ε < ε * (2 : ENNReal) := by simpa [mul_one] using hmul
    exact hdiv.mpr this
  -- finish: P(event) ≤ ε/2 < ε
  exact lt_of_le_of_lt h_le h_half_lt
lemma continuous_prob_convergence {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    {S S' : Type*}
    [PseudoMetricSpace S] [MeasurableSpace S] [OpensMeasurableSpace S] [SecondCountableTopology S]
    [T2Space S] [LocallyCompactSpace S] [BorelSpace S]
    [PseudoMetricSpace S'] [MeasurableSpace S'] [OpensMeasurableSpace S']
    (X : ℕ → Ω → S) (Y : Ω → S) (f : S → S')
        (h_meas_Y : Measurable Y)
    (h_cont : Continuous f)
    (h_conv : ConvergesInProbabilityToZero P (fun u ω => dist (X u ω) (Y ω))) :
    ConvergesInProbabilityToZero P (fun u ω => dist (f (X u ω)) (f (Y ω))) := by
      intro ε hε_pos
      have h_tight : ∀ η > 0, ∃ K : Set S, IsCompact K ∧ P {ω | Y ω∉K} < η := by
        exact fun η a ↦ tightness_helper P Y h_meas_Y η a;
      -- Since `f` is continuous and `K` is compact, `f` is uniformly continuous on `K`.
      have h_unif : ∀ K : Set S, IsCompact K → ∀ ε > 0, ∃ δ > 0, ∀ x y, y ∈ K → dist x y < δ → dist (f x) (f y) ≤ ε := by
        intro K hK ε hε_pos;
        have := hK.elim_nhds_subcover;
        -- By the definition of continuity at a point, for each $y \in K$, there exists $\delta_y > 0$ such that if $dist x y < \delta_y$, then $dist (f x) (f y) < \epsilon / 2$.
        have h_cont_at : ∀ y ∈ K, ∃ δ_y > 0, ∀ x, dist x y < δ_y → dist (f x) (f y) < ε / 2 := by
          exact fun y hy => Metric.continuous_iff.mp h_cont y ( ε / 2 ) ( half_pos hε_pos );
        choose! δ hδ_pos hδ using h_cont_at;
        obtain ⟨ t, ht₁, ht₂ ⟩ := this ( fun y => Metric.ball y ( δ y / 2 ) ) fun y hy => Metric.ball_mem_nhds _ ( half_pos ( hδ_pos y hy ) );
        -- Let $\delta = \min_{x \in t} \frac{\delta_x}{2}$.
        obtain ⟨δ_min, hδ_min_pos, hδ_min⟩ : ∃ δ_min > 0, ∀ x ∈ t, δ_min ≤ δ x / 2 := by
          by_cases ht_empty : t.Nonempty;
          · exact ⟨ Finset.min' ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩, by have := Finset.min'_mem ( t.image fun x => δ x / 2 ) ⟨ _, Finset.mem_image_of_mem _ ht_empty.choose_spec ⟩ ; aesop, fun x hx => Finset.min'_le _ _ ( Finset.mem_image_of_mem _ hx ) ⟩;
          · exact ⟨ 1, zero_lt_one, fun x hx => False.elim <| ht_empty ⟨ x, hx ⟩ ⟩;
        refine' ⟨ δ_min, hδ_min_pos, fun x y hy hxy => _ ⟩;
        obtain ⟨ z, hz₁, hz₂ ⟩ := Set.mem_iUnion₂.mp ( ht₂ hy );
        have := hδ z ( ht₁ z hz₁ ) x ?_;
        · have := hδ z ( ht₁ z hz₁ ) y ?_;
          · exact le_trans ( dist_triangle_right _ _ _ ) ( by linarith );
          · exact lt_of_lt_of_le hz₂ ( by linarith [ hδ_pos z ( ht₁ z hz₁ ) ] );
        · exact lt_of_le_of_lt ( dist_triangle _ _ _ ) ( by linarith [ hδ_min z hz₁, Metric.mem_ball.mp hz₂ ] );
      -- Fix `ε > 0`. By `tightness_helper`, for any `η > 0`, there exists a compact set `K` such that `P(Y ∉ K) < η`.
      have h_bound : ∀ η > 0, ∃ δ > 0, ∀ u, P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + η := by
        intro η hη_pos
        obtain ⟨K, hK_compact, hK_bound⟩ := h_tight η hη_pos
        obtain ⟨δ, hδ_pos, hδ_unif⟩ := h_unif K hK_compact ε hε_pos
        use δ, hδ_pos
        intro u
        have h_bound : P {ω | dist (f (X u ω)) (f (Y ω)) > ε} ≤ P {ω | dist (X u ω) (Y ω) ≥ δ} + P {ω | Y ω∉K} := by
          refine' le_trans ( MeasureTheory.measure_mono _ ) ( MeasureTheory.measure_union_le _ _ );
          intro ω hω; contrapose! hω; aesop;
        exact le_trans h_bound (add_le_add_right (le_of_lt hK_bound) _)
      -- By `h_conv`, for any `δ > 0`, `P(X u ω, Y ω) ≥ δ` tends to 0 as `u → ∞`.
      have h_conv_zero : ∀ δ > 0, Filter.Tendsto (fun u => P {ω | dist (X u ω) (Y ω) ≥ δ}) Filter.atTop (𝓝 0) := by
        intro δ hδ_pos
        have := h_conv δ hδ_pos
        simp_all +decide [ ConvergesInProbabilityToZero ];
        have := h_conv ( δ / 2 ) ( half_pos hδ_pos );
        rw [ ENNReal.tendsto_nhds_zero ] at *;
        exact fun ε ε_pos => by filter_upwards [ this ε ε_pos ] with u hu using le_trans ( MeasureTheory.measure_mono ( fun ω hω => by exact lt_of_lt_of_le ( half_lt_self hδ_pos ) hω.out ) ) hu;
      rw [ ENNReal.tendsto_nhds_zero ] at *;
      intro η hη_pos; rcases h_bound ( η / 2 ) ( ENNReal.half_pos hη_pos.ne' ) with ⟨ δ, δ_pos, hδ ⟩ ; filter_upwards [ h_conv_zero δ δ_pos |> fun h => h.eventually ( gt_mem_nhds <| ENNReal.half_pos hη_pos.ne' ) ] with u hu; simpa using le_trans ( hδ u ) ( add_le_add hu.le le_rfl ) |> le_trans <| by rw [ ENNReal.add_halves ] ;
/--
Lemma: The risk using estimated embeddings is invariant under affine isometries of the embeddings.
-/
lemma risk_est_invariant (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (e : E d ≃ᵃⁱ[ℝ] E d)
    (h_inv : InvariantToAffineIsometries n d d' learn) :
    risk_est n d d' P learn loss (fun ω i => e (psi_hat ω i)) = risk_est n d d' P learn loss psi_hat := by
      unfold risk_est;
      simp +decide;
      congr! 2;
      convert rfl using 2;
      exact h_inv e _ _ ▸ rfl
/--
Lemma: The transformed estimated embeddings converge to the true embeddings in probability.
-/
lemma transformed_embeddings_converge (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat) :
    ∃ (e : ℕ → E d ≃ᵃⁱ[ℝ] E d),
      ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
        (fun u ω => ⨆ i : Fin (n + 1), dist ((e u).symm (psi_hat u ω i)) ((ω i).1)) := by
          obtain ⟨ e, he ⟩ := h_align;
          refine' ⟨ e, fun ε hε => _ ⟩;
          -- Since $e_u$ is an isometry, the distance between $e_u^{-1}(\psi_hat u \omega i)$ and $\omega i$ is equal to the distance between $\psi_hat u \omega i$ and $e_u(\omega i)$.
          have h_dist_eq : ∀ u ω i, dist (((e u).symm : E d → E d) (psi_hat u ω i)) (ω i).1 = dist (psi_hat u ω i) (e u (ω i).1) := by
            intro u ω i; exact (by
            rw [ ← ( e u ).isometry.dist_eq ] ; aesop;);
          simpa [ h_dist_eq ] using he ε hε
/-
Assumption that the labels y are almost surely contained in a compact set.
-/
def combined_loss_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    ((Fin (n + 1) → E d) × (Fin (n + 1) → Y d')) → ℝ :=
  fun p =>
    let psis := p.1
    let ys := p.2
    let train := fun i : Fin n => (psis (Fin.castSucc i), ys (Fin.castSucc i))
    let test_psi := psis (Fin.last n)
    let test_y := ys (Fin.last n)
    loss (learn train test_psi) test_y
lemma combined_loss_continuous (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss) :
    Continuous (combined_loss_fn n d d' learn loss) := by
      unfold combined_loss_fn;
      unfold ContinuousLearningRule ContinuousLoss at *;
      fun_prop
/-
Lemma: The loss using estimated embeddings converges in probability to the loss using true embeddings.
-/
lemma loss_converges_in_prob (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss) :
    ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => dist
        (combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2))
        (combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2))) := by
          -- Apply the continuous mapping theorem to conclude the proof.
          apply continuous_prob_convergence;
          · fun_prop;
          · exact combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss;
          · simp_all +decide [ dist_eq_norm, Prod.norm_def ];
            convert h_conv using 1;
            ext u ω;
            rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ];
            · exact fun i => by simpa using norm_le_pi_norm ( psi_hat u ω - fun i => ( ω i |>.1 ) ) i;
            · intro w hw;
              contrapose! hw;
              exact pi_norm_le_iff_of_nonneg ( by linarith [ show 0 ≤ w by exact le_trans ( norm_nonneg _ ) ( hw 0 ) ] ) |>.2 hw
/-
Lemma: The risk is equal to the estimated risk when the estimated embeddings are the true embeddings.
-/
lemma risk_eq_risk_est_true (n d d' : ℕ)
    (P : Measure (E d × Y d'))
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    risk n d d' P learn loss = risk_est n d d' P learn loss (fun ω i => (ω i).1) := by
  simp [risk, risk_est]
/-

Definitions of the loss functions for estimated and true embeddings.
-/
def loss_est_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (u : ℕ) : (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (psi_hat u ω, fun i => (ω i).2)
def loss_true_fn (n d d' : ℕ)
    (learn : LearningRule n d d')
    (loss : LossFunction d') :
    (Fin (n + 1) → E d × Y d') → ℝ :=
  fun ω => combined_loss_fn n d d' learn loss (fun i => (ω i).1, fun i => (ω i).2)
/-
Lemma: If estimated embeddings converge to true embeddings in probability, then the risk converges.
-/
lemma risk_convergence_of_aligned_embeddings (n d d' : ℕ)    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_conv : ConvergesInProbabilityToZero (Measure.pi (fun _ : Fin (n + 1) => P))
      (fun u ω => ⨆ i : Fin (n + 1), dist (psi_hat u ω i) ((ω i).1)))
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_pred : UniformlyBoundedPredictions n d d' learn)
    (h_env : LossEnvelopeIntegrable n d d' P loss) :
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
  -- Abbreviate the product measure.
  let μ : Measure (Fin (n + 1) → E d × Y d') := Measure.pi (fun _ : Fin (n + 1) => P)

  -- Loss (as a function of ω) converges in probability when embeddings converge in probability.
  have h_loss_dist :
      ConvergesInProbabilityToZero μ
        (fun u ω => dist (loss_est_fn n d d' learn loss psi_hat u ω)
                          (loss_true_fn n d d' learn loss ω)) := by
    simpa [μ] using
      (loss_converges_in_prob (n:=n) (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss)
        (psi_hat:=psi_hat) h_meas_psi h_conv h_cont_learn h_cont_loss)

  -- Turn the `dist` statement into convergence in probability of the real-valued difference.
  have h_diff_prob :
      ConvergesInProbabilityToZero μ
        (fun u ω => loss_est_fn n d d' learn loss psi_hat u ω -
                    loss_true_fn n d d' learn loss ω) := by
    intro ε hε
    have h0 := h_loss_dist ε hε
    -- For reals: `dist a b = |a - b|`.
    simpa [μ, dist_eq_norm, Real.norm_eq_abs, abs_abs, sub_eq_add_neg] using h0

  -- Obtain a global compact prediction set `K` from A3.
  rcases h_pred with ⟨K, hK_comp, hK⟩
  have hK_bdd : Bornology.IsBounded K := hK_comp.isBounded

  -- Obtain an integrable envelope `g` for `|loss yhat y|` over `yhat ∈ K`.
  rcases (h_env K hK_bdd) with ⟨g, hg_int, hg_nonneg, hg_dom⟩

  -- Define a dominating function on Ω: `G(ω) = 2 * g(y_test)`.
  let G : (Fin (n + 1) → E d × Y d') → ℝ := fun ω => 2 * g ((ω (Fin.last n)).2)

  have h_dom :
      ∀ u, ∀ᵐ ω ∂μ,
        |loss_est_fn n d d' learn loss psi_hat u ω -
          loss_true_fn n d d' learn loss ω| ≤ G ω := by
    intro u
    refine Filter.Eventually.of_forall (fun ω => ?_)
    -- Both predictions lie in K by `hK`.
    have hyhat_est : learn
        (fun i : Fin n =>
          (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2))
        (psi_hat u ω (Fin.last n)) ∈ K := by
      exact hK _ _
    have hyhat_true :
        learn (fun i : Fin n => ω (Fin.castSucc i)) (ω (Fin.last n)).1 ∈ K := by
      exact hK _ _
    -- Dominate each loss by `g(y_test)`.
    have h_est : |loss_est_fn n d d' learn loss psi_hat u ω| ≤ g ((ω (Fin.last n)).2) := by
      -- unfold and apply envelope domination
      simpa [loss_est_fn, combined_loss_fn] using
        (hg_dom _ hyhat_est _)
    have h_true : |loss_true_fn n d d' learn loss ω| ≤ g ((ω (Fin.last n)).2) := by
      simpa [loss_true_fn, combined_loss_fn] using
        (hg_dom _ hyhat_true _)
    -- Triangle inequality.
    have h_sub :
        |loss_est_fn n d d' learn loss psi_hat u ω -
          loss_true_fn n d d' learn loss ω|
        ≤ |loss_est_fn n d d' learn loss psi_hat u ω| +
          |loss_true_fn n d d' learn loss ω| := by
      simpa [sub_eq_add_neg, Real.norm_eq_abs] using
        (norm_add_le (loss_est_fn n d d' learn loss psi_hat u ω)
          (-(loss_true_fn n d d' learn loss ω)))
    -- Combine and simplify to `2 * g(...)`.
    have : |loss_est_fn n d d' learn loss psi_hat u ω -
              loss_true_fn n d d' learn loss ω|
          ≤ g ((ω (Fin.last n)).2) + g ((ω (Fin.last n)).2) := by
      exact le_trans h_sub (add_le_add h_est h_true)
    simpa [G, two_mul, add_comm, add_left_comm, add_assoc] using this

  -- Measurability of the difference (unchanged from the bounded-loss proof).
  have h_meas_diff :
      ∀ u, Measurable (fun ω =>
        loss_est_fn n d d' learn loss psi_hat u ω -
        loss_true_fn n d d' learn loss ω) := by
    intro u
    have h_loss : Measurable (combined_loss_fn n d d' learn loss) := by
      exact (combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss).measurable
    have h_lbl : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
        (fun i : Fin (n + 1) => (ω i).2)) := by
      classical
      refine measurable_pi_iff.2 ?_
      intro i
      exact measurable_snd.comp (measurable_pi_apply i)
    have h_pair_est : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
        (psi_hat u ω, (fun i : Fin (n + 1) => (ω i).2))) := by
      exact Measurable.prodMk (h_meas_psi u) h_lbl
    have h_meas_est : Measurable (loss_est_fn n d d' learn loss psi_hat u) := by
      simpa [loss_est_fn] using h_loss.comp h_pair_est
    have h_x : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
        (fun i : Fin (n + 1) => (ω i).1)) := by
      classical
      refine measurable_pi_iff.2 ?_
      intro i
      exact measurable_fst.comp (measurable_pi_apply i)
    have h_pair_true : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
        ((fun i : Fin (n + 1) => (ω i).1), (fun i : Fin (n + 1) => (ω i).2))) := by
      exact Measurable.prodMk h_x h_lbl
    have h_meas_true : Measurable (loss_true_fn n d d' learn loss) := by
      simpa [loss_true_fn] using h_loss.comp h_pair_true
    simpa using h_meas_est.sub h_meas_true

  -- L1 convergence of the absolute difference from dominated convergence in probability.
  have h_L1 :
      Tendsto (fun u =>
        ∫ ω, |loss_est_fn n d d' learn loss psi_hat u ω -
              loss_true_fn n d d' learn loss ω| ∂μ) atTop (𝓝 0) := by
    -- Apply the dominated convergence lemma to `X_u = loss_est - loss_true` and `G`.
    have hG_int : Integrable G μ := by
      -- `G` integrable under μ by A5 (`hg_int`), since `G = 2 * g(y_test)`.
      simpa [G, μ, mul_assoc, mul_left_comm, mul_comm] using (hg_int.mul_const (2:ℝ))
    exact expectation_converges_of_prob_converges_dominated (P:=μ)
      (X:=fun u ω =>
        loss_est_fn n d d' learn loss psi_hat u ω -
        loss_true_fn n d d' learn loss ω)
      (G:=G)
      h_meas_diff h_dom hG_int h_diff_prob

  -- Hence the integral of the difference tends to 0.
  have h_int_diff0 :
      Tendsto (fun u =>
        ∫ ω, (loss_est_fn n d d' learn loss psi_hat u ω -
              loss_true_fn n d d' learn loss ω) ∂μ) atTop (𝓝 0) := by
    refine squeeze_zero_norm (fun u => ?_) h_L1
    simpa using (MeasureTheory.norm_integral_le_integral_norm
      (f := fun ω =>
        loss_est_fn n d d' learn loss psi_hat u ω -
        loss_true_fn n d d' learn loss ω) (μ:=μ))

  -- Rewrite the integral of the difference as a difference of integrals, and conclude.
  have h_sub0 :
      Tendsto (fun u =>
        (∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂μ) -
        (∫ ω, loss_true_fn n d d' learn loss ω ∂μ)) atTop (𝓝 0) := by
    -- Use `h_int_diff0` and rewrite pointwise.
    refine h_int_diff0.congr' ?_
    refine Filter.Eventually.of_forall (fun u => by
      -- Integrability of both terms follows from the envelope `g(y_test)`.
      have h_loss : Measurable (combined_loss_fn n d d' learn loss) := by
        exact (combined_loss_continuous n d d' learn loss h_cont_learn h_cont_loss).measurable
      have h_lbl : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
          (fun i : Fin (n + 1) => (ω i).2)) := by
        classical
        refine measurable_pi_iff.2 ?_
        intro i
        exact measurable_snd.comp (measurable_pi_apply i)
      have h_x : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
          (fun i : Fin (n + 1) => (ω i).1)) := by
        classical
        refine measurable_pi_iff.2 ?_
        intro i
        exact measurable_fst.comp (measurable_pi_apply i)
      have h_pair_true : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
          ((fun i : Fin (n + 1) => (ω i).1), (fun i : Fin (n + 1) => (ω i).2))) := by
        exact Measurable.prodMk h_x h_lbl
      have h_meas_true : Measurable (loss_true_fn n d d' learn loss) := by
        simpa [loss_true_fn] using h_loss.comp h_pair_true
      have h_pair_est : Measurable (fun ω : (Fin (n + 1) → E d × Y d') =>
          (psi_hat u ω, (fun i : Fin (n + 1) => (ω i).2))) := by
        exact Measurable.prodMk (h_meas_psi u) h_lbl
      have h_meas_est : Measurable (loss_est_fn n d d' learn loss psi_hat u) := by
        simpa [loss_est_fn] using h_loss.comp h_pair_est

      have hI2 : Integrable (loss_true_fn n d d' learn loss) μ := by
        have h_as : AEStronglyMeasurable (loss_true_fn n d d' learn loss) μ :=
          Measurable.aestronglyMeasurable h_meas_true
        have h_bound :
            ∀ᵐ ω : (Fin (n + 1) → E d × Y d') ∂μ,
              ‖loss_true_fn n d d' learn loss ω‖ ≤ g ((ω (Fin.last n)).2) := by
          refine Filter.Eventually.of_forall (fun ω => ?_)
          have hyhat_true :
              learn (fun i : Fin n => ω (Fin.castSucc i)) (ω (Fin.last n)).1 ∈ K := by
            exact hK _ _
          have habs : |loss_true_fn n d d' learn loss ω| ≤ g ((ω (Fin.last n)).2) := by
            -- envelope domination, with `yhat ∈ K`
            simpa [loss_true_fn, combined_loss_fn, Prod.eta] using (hg_dom _ hyhat_true _)
          simpa [Real.norm_eq_abs] using habs
        exact hg_int.mono' h_as h_bound

      have hI1 : Integrable (loss_est_fn n d d' learn loss psi_hat u) μ := by
        have h_as : AEStronglyMeasurable (loss_est_fn n d d' learn loss psi_hat u) μ :=
          Measurable.aestronglyMeasurable h_meas_est
        have h_bound :
            ∀ᵐ ω : (Fin (n + 1) → E d × Y d') ∂μ,
              ‖loss_est_fn n d d' learn loss psi_hat u ω‖ ≤ g ((ω (Fin.last n)).2) := by
          refine Filter.Eventually.of_forall (fun ω => ?_)
          have hyhat_est :
              learn
                (fun i : Fin n =>
                  (psi_hat u ω (Fin.castSucc i), (ω (Fin.castSucc i)).2))
                (psi_hat u ω (Fin.last n)) ∈ K := by
            exact hK _ _
          have habs : |loss_est_fn n d d' learn loss psi_hat u ω| ≤ g ((ω (Fin.last n)).2) := by
            simpa [loss_est_fn, combined_loss_fn] using (hg_dom _ hyhat_est _)
          simpa [Real.norm_eq_abs] using habs
        exact hg_int.mono' h_as h_bound

      -- Rewrite `∫ (f - g)` using linearity.
      calc
        (∫ ω, (loss_est_fn n d d' learn loss psi_hat u ω -
                loss_true_fn n d d' learn loss ω) ∂μ)
            = (∫ ω, (loss_est_fn n d d' learn loss psi_hat u ω +
                      (-(loss_true_fn n d d' learn loss ω))) ∂μ) := by
                simp [sub_eq_add_neg]
        _ = (∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂μ) +
            (∫ ω, (-(loss_true_fn n d d' learn loss ω)) ∂μ) := by
                simpa using
                  (MeasureTheory.integral_add (μ:=μ)
                    (f := fun ω => loss_est_fn n d d' learn loss psi_hat u ω)
                    (g := fun ω => -(loss_true_fn n d d' learn loss ω))
                    hI1 (hI2.neg))
        _ = (∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂μ) -
              (∫ ω, loss_true_fn n d d' learn loss ω ∂μ) := by
                simp [MeasureTheory.integral_neg, sub_eq_add_neg]
      )

  have h_risk :
      Tendsto (fun u => ∫ ω, loss_est_fn n d d' learn loss psi_hat u ω ∂μ) atTop
        (𝓝 (∫ ω, loss_true_fn n d d' learn loss ω ∂μ)) := by
    have h := h_sub0.add_const (∫ ω, loss_true_fn n d d' learn loss ω ∂μ)
    simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using h

  -- Translate back to `risk` / `risk_est`.
  simpa [risk, risk_est, loss_est_fn, loss_true_fn, combined_loss_fn, μ] using h_risk

/-
Theorem 1 (paper): For fixed `n`, the risk computed using estimated embeddings converges to the risk computed
using true embeddings, assuming DKPS alignment consistency and invariance to affine isometries.
-/
theorem risk_converges_fixed_n (n d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (h_meas_psi : ∀ u, Measurable (psi_hat u))
    (h_align : DKPSAlignmentConsistency n d d' P psi_hat)
    (h_inv : InvariantToAffineIsometries n d d' learn)
    (h_cont_learn : ContinuousLearningRule n d d' learn)
    (h_cont_loss : ContinuousLoss d' loss)
    (h_pred : UniformlyBoundedPredictions n d d' learn)
    (h_env : LossEnvelopeIntegrable n d d' P loss) :
    Tendsto (fun u => risk_est n d d' P learn loss (psi_hat u)) atTop (𝓝 (risk n d d' P learn loss)) := by
  -- Use alignment consistency to pick a sequence of affine isometries so that the transformed estimates
  -- converge (in probability) to the true embeddings.
  obtain ⟨e, he⟩ := transformed_embeddings_converge (n:=n) (d:=d) (d':=d') (P:=P)
    (psi_hat:=psi_hat) h_align
  -- Apply the risk convergence lemma to the transformed embeddings.
  have h_tendsto_trans :
      Tendsto (fun u =>
        risk_est n d d' P learn loss (fun ω i => (e u).symm (psi_hat u ω i)))
        atTop (𝓝 (risk n d d' P learn loss)) := by
    refine risk_convergence_of_aligned_embeddings (n:=n) (d:=d) (d':=d') (P:=P)
      (learn:=learn) (loss:=loss)
      (psi_hat:=fun u ω i => (e u).symm (psi_hat u ω i))
      ?_ ?_ h_cont_learn h_cont_loss h_pred h_env
    · intro u
      -- measurability: composition of measurable `psi_hat u` with continuous `(e u).symm`.
      have h_meas_symm : Measurable (fun x : E d => (e u).symm x) := by
        exact Continuous.measurable (by exact (e u).symm.continuous)
      fun_prop
    · -- convergence already provided by `he`, after rewriting the `dist`.
      -- `he` is exactly the statement for the transformed embeddings.
      simpa using he
  -- Invariance to affine isometries lets us remove the transformation.
  have h_eq :
      ∀ u,
        risk_est n d d' P learn loss (psi_hat u) =
        risk_est n d d' P learn loss (fun ω i => (e u).symm (psi_hat u ω i)) := by
    intro u
    -- `risk_est_invariant` says `risk_est (e ∘ ψ) = risk_est ψ`.
    -- Apply it with `ψ := (e u)⁻¹ ∘ psi_hat u` so that `e u ∘ ψ = psi_hat u`.
    simpa using
      (risk_est_invariant (n:=n) (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss)
        (psi_hat:=fun ω i => (e u).symm (psi_hat u ω i)) (e:=e u) h_inv)
  -- Transfer the limit along the pointwise equality.
  refine h_tendsto_trans.congr' ?_
  refine Filter.Eventually.of_forall (fun u => (h_eq u).symm)
/-
Diagonal sequence lemma: If a(n, u) -> b(n) as u -> infinity for each n, and b(n) -> L as n -> infinity, then there exists a diagonal sequence phi(n) -> infinity such that a(n, phi(n)) -> L.
-/
lemma diagonal_convergence {α : Type*} [TopologicalSpace α] [FirstCountableTopology α]
    (a : ℕ → ℕ → α) (b : ℕ → α) (L : α)
    (h_lim_u : ∀ n, Tendsto (fun u => a n u) atTop (𝓝 (b n)))
    (h_lim_n : Tendsto b atTop (𝓝 L)) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧ Tendsto (fun n => a n (phi n)) atTop (𝓝 L) := by
      -- By the first-countability of α, there exists a countable neighborhood basis at L.
      obtain ⟨U, hU⟩ : ∃ U : ℕ → Set α, (∀ k, IsOpen (U k)) ∧ (∀ k, L ∈ U k) ∧ (∀ k, U (k + 1) ⊆ U k) ∧ ∀ S ∈ nhds L, ∃ k, U k ⊆ S := by
        rcases ( nhds_basis_opens L ).exists_antitone_subbasis with ⟨ U, hU₁, hU₂ ⟩;
        exact ⟨ U, fun k => hU₁ k |>.2, fun k => hU₁ k |>.1, fun k => hU₂.2 k.le_succ, fun S hS => by rcases hU₂.mem_iff.mp hS with ⟨ k, hk ⟩ ; exact ⟨ k, hk ⟩ ⟩
      generalize_proofs at *; (
      -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$.
      obtain ⟨phi, hphi⟩ : ∃ phi : ℕ → ℕ, (∀ n, n ≤ phi n) ∧ (∀ k, ∃ N, ∀ n ≥ N, a n (phi n) ∈ U k) := by
        -- By the definition of $U$, we can find a sequence $\phi(n)$ such that $a(n, \phi(n)) \in U_k$ for all $n \geq N_k$. Use this fact.
        have h_phi : ∀ k, ∃ N, ∀ n ≥ N, ∃ M, ∀ u ≥ M, a n u ∈ U k := by
          intro k
          obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N, b n ∈ U k := by
            exact Filter.eventually_atTop.mp ( h_lim_n ( hU.1 k |> IsOpen.mem_nhds <| hU.2.1 k ) ) |> fun ⟨ N, hN ⟩ => ⟨ N, fun n hn => hN n hn ⟩
          generalize_proofs at *; (
          exact ⟨ N, fun n hn => by rcases Filter.eventually_atTop.mp ( h_lim_u n ( hU.1 k |> IsOpen.mem_nhds <| hN n hn ) ) with ⟨ M, hM ⟩ ; exact ⟨ M, fun u hu => hM u hu ⟩ ⟩)
        generalize_proofs at *; (
        choose N hN using h_phi
        generalize_proofs at *; (
        choose! M hM using hN
        generalize_proofs at *; (
        use fun n => max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1
        generalize_proofs at *; (
        refine' ⟨ fun n => _, fun k => _ ⟩
        generalize_proofs at *; (
        grind);
        use N k + k + 1
        generalize_proofs at *; (
        intro n hn
        specialize hM k n (by linarith) (max n (M n n) + ∑ k ∈ Finset.range (n + 1), M k n + ∑ k ∈ Finset.range (n + 1), N k + 1) (by
        linarith [ Finset.single_le_sum ( fun x _ => Nat.zero_le ( M x n ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), Finset.single_le_sum ( fun x _ => Nat.zero_le ( N x ) ) ( Finset.mem_range.mpr ( by linarith : k < n + 1 ) ), le_max_left n ( M n n ), le_max_right n ( M n n ) ])
        generalize_proofs at *; exact hM)))))
      generalize_proofs at *; (
      refine' ⟨ phi, Filter.tendsto_atTop_mono hphi.1 tendsto_natCast_atTop_atTop, _ ⟩
      generalize_proofs at *; (
      exact fun S hS => by rcases hU.2.2.2 S hS with ⟨ k, hk ⟩ ; rcases hphi.2 k with ⟨ N, hN ⟩ ; exact Filter.eventually_atTop.2 ⟨ N, fun n hn => hk ( hN n hn ) ⟩ ;)))
/-
Theorem 2 (paper): Consistency transfer. If the learning rule is consistent under the true embeddings,
then there exists a schedule of estimation budgets such that it is consistent under the estimated embeddings.
-/
theorem consistency_transfer_dkps (d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (L : ℝ)
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))
    (h_cont_loss : ContinuousLoss d' loss)
    (h_pred : ∀ n, UniformlyBoundedPredictions n d d' (learn n))
    (h_env : ∀ n, LossEnvelopeIntegrable n d d' P loss)
    (h_consistent : Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 L)) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop (𝓝 L) := by
  -- Apply the diagonal sequence lemma to the sequences `a(n,u)` and `b(n)`.
  have h_lim_u :
      ∀ n,
        Tendsto (fun u => risk_est n d d' P (learn n) loss (psi_hat n u)) atTop
          (𝓝 (risk n d d' P (learn n) loss)) := by
    intro n
    exact risk_converges_fixed_n (n:=n) (d:=d) (d':=d') (P:=P) (learn:=learn n) (loss:=loss)
      (psi_hat:=psi_hat n) (h_meas_psi:=h_meas_psi n) (h_align:=h_align n) (h_inv:=h_inv n)
      (h_cont_learn:=h_cont_learn n) (h_cont_loss:=h_cont_loss) (h_pred:=h_pred n) (h_env:=h_env n)
  -- Now diagonalize to match the `n → ∞` limit.
  exact diagonal_convergence
    (a := fun n u => risk_est n d d' P (learn n) loss (psi_hat n u))
    (b := fun n => risk n d d' P (learn n) loss)
    (L := L)
    h_lim_u
    h_consistent
/-- Risk of a (measurable) decision function `h : E → Y`. -/
def risk_df (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d') (h : E d → Y d') : ℝ :=
  ∫ p, loss (h p.1) p.2 ∂P
/-- Bayes risk over a hypothesis class `H`. (Paper's `R^*_\ell(PψY,H)`.) -/
def bayesRisk (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d') (H : Set (E d → Y d')) : ℝ :=
  sInf (risk_df (d:=d) (d':=d') P loss '' H)
/-- Appendix-A style "consistency": expected risk tends to Bayes risk. -/
def ConsistentExpected (d d' : ℕ) (P : Measure (E d × Y d'))
    (loss : LossFunction d')
    (learn : (n : ℕ) → LearningRule n d d')
    (H : Set (E d → Y d')) : Prop :=
  Tendsto (fun n => risk n d d' P (learn n) loss) atTop (𝓝 (bayesRisk d d' P loss H))
theorem consistency_transfer_dkps_bayes (d d' : ℕ)
    (P : Measure (E d × Y d')) [IsProbabilityMeasure P]
    (learn : (n : ℕ) → LearningRule n d d')
    (loss : LossFunction d')
    (psi_hat : (n : ℕ) → ℕ → (Fin (n + 1) → E d × Y d') → Fin (n + 1) → E d)
    (H : Set (E d → Y d'))
    (h_meas_psi : ∀ n u, Measurable (psi_hat n u))
    (h_align : ∀ n, DKPSAlignmentConsistency n d d' P (psi_hat n))
    (h_inv : ∀ n, InvariantToAffineIsometries n d d' (learn n))
    (h_cont_learn : ∀ n, ContinuousLearningRule n d d' (learn n))
    (h_cont_loss : ContinuousLoss d' loss)
    (h_pred : ∀ n, UniformlyBoundedPredictions n d d' (learn n))
    (h_env : ∀ n, LossEnvelopeIntegrable n d d' P loss)
    (h_consistent : ConsistentExpected d d' P loss learn H) :
    ∃ phi : ℕ → ℕ, Tendsto phi atTop atTop ∧
      Tendsto (fun n => risk_est n d d' P (learn n) loss (psi_hat n (phi n))) atTop
        (𝓝 (bayesRisk d d' P loss H)) := by
  -- Instantiate Theorem 2 with `L = bayesRisk ...`.
  simpa [ConsistentExpected] using
    (consistency_transfer_dkps (d:=d) (d':=d') (P:=P) (learn:=learn) (loss:=loss) (psi_hat:=psi_hat)
      (L := bayesRisk d d' P loss H)
      h_meas_psi h_align h_inv h_cont_learn h_cont_loss h_pred h_env h_consistent)
