/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: be061c37-56c1-444d-830a-b8989b1fa34a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the main theorem from the Quench paper.
We define the DKPS nearest-neighbor predictor and the baseline subset-score predictor.
We prove that under the DKPS concentration hypothesis and a denseness assumption on the model distribution,
the MSE of the DKPS predictor converges to 0 in probability as the number of reference models and responses increases.
Consequently, if the baseline predictor has strictly positive MSE, the DKPS predictor eventually achieves strictly lower MSE with high probability, establishing query efficiency.
-/



import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the nearest neighbor index in the estimated perspective space.
It selects the index i such that the distance between the estimated perspective of the reference model i and the target model is minimized.
-/
open Metric MeasureTheory ProbabilityTheory Classical

noncomputable def nn_index {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) : Fin n :=
  let s : Finset (Fin n) := Finset.univ
  let f := fun i => dist (ψhat (refs i)) (ψhat target)
  haveI : Nonempty (Fin n) := Fin.pos_iff_nonempty.1 (NeZero.pos n)
  Classical.choose (Finset.exists_min_image s f Finset.univ_nonempty)

/-
Property of the nearest neighbor index: it minimizes the distance in the estimated perspective space.
-/
theorem nn_index_spec {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) :
    let i_star := nn_index n refs target ψhat
    ∀ j : Fin n, dist (ψhat (refs i_star)) (ψhat target) ≤ dist (ψhat (refs j)) (ψhat target) := by
  convert Classical.choose_spec ( Finset.exists_min_image Finset.univ ( fun i => Dist.dist ( ψhat ( refs i ) ) ( ψhat target ) ) Finset.univ_nonempty ) |> fun h => h.2;
  simp +decide [ nn_index ]

/-
The nearest neighbor predictor predicts the score of the target model to be the score of the reference model with the closest estimated perspective.
-/
noncomputable def nn_predictor {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) : ℝ :=
  y (refs (nn_index n refs target ψhat))

/-
Deterministic error bound for the nearest neighbor predictor.
If the estimated perspectives are within c of the true perspectives, and there exists a reference model within ε' of the target in the true perspective space,
then the nearest neighbor predictor (selected using estimated perspectives) has error at most γ * (4c + ε'), where γ is the Lipschitz constant.
-/
theorem deterministic_error_bound
  {F : Type*} {d : ℕ}
  (n : ℕ) [NeZero n]
  (refs : Fin n → F) (target : F)
  (ψ : F → EuclideanSpace ℝ (Fin d)) (ψhat : F → EuclideanSpace ℝ (Fin d))
  (y : F → ℝ)
  (c ε' γ : ℝ)
  (h_nonneg_γ : 0 ≤ γ)
  (h_conc_refs : ∀ i, dist (ψhat (refs i)) (ψ (refs i)) ≤ c)
  (h_conc_target : dist (ψhat target) (ψ target) ≤ c)
  (h_close : ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε')
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f')) :
  |nn_predictor n refs target ψhat y - y target| ≤ γ * (4 * c + ε') := by
  have h_dist : dist (ψ (refs (nn_index n refs target ψhat))) (ψ target) ≤ 4 * c + ε' := by
    obtain ⟨ j, hj ⟩ := h_close;
    -- Using the triangle inequality and the given bounds, we can show that the distance between the nearest neighbor's estimated perspective and the target's true perspective is at most $4c + \epsilon'$.
    have h_dist : dist (ψhat (refs (nn_index n refs target ψhat))) (ψhat target) ≤ 2 * c + ε' := by
      have h_dist : dist (ψhat (refs (nn_index n refs target ψhat))) (ψhat target) ≤ dist (ψhat (refs j)) (ψhat target) := by
        exact nn_index_spec n refs target ψhat j;
      refine' le_trans h_dist ( le_trans ( dist_triangle4_right _ _ _ _ ) _ );
      exacts [ ψ ( refs j ), ψ target, by linarith [ h_conc_refs j, h_conc_target, hj, dist_comm ( ψhat ( refs j ) ) ( ψ ( refs j ) ), dist_comm ( ψhat target ) ( ψ target ), dist_comm ( ψ ( refs j ) ) ( ψ target ) ] ];
    have h_dist : dist (ψ (refs (nn_index n refs target ψhat))) (ψhat (refs (nn_index n refs target ψhat))) ≤ c := by
      simpa only [ dist_comm ] using h_conc_refs _;
    exact le_trans ( dist_triangle4 _ _ _ _ ) ( by linarith );
  exact le_trans ( h_lip _ _ ) ( mul_le_mul_of_nonneg_left h_dist h_nonneg_γ )

/-
If p is a probability strictly between 0 and 1, then (1-p)^n can be made arbitrarily small by choosing n large enough.
-/
theorem prob_failure_decay (p : ℝ) (hp : 0 < p) (hp1 : p ≤ 1) (η : ℝ) (hη : 0 < η) :
    ∃ N, ∀ n ≥ N, (1 - p) ^ n ≤ η := by
  simpa using ( tendsto_pow_atTop_nhds_zero_of_lt_one ( sub_nonneg.2 hp1 ) ( sub_lt_self _ hp ) ) |> fun h => h.eventually ( ge_mem_nhds hη )

/-
The probability that at least one reference model is within distance ε of the target is 1 - (1 - p)^n, where p is the probability that a single random model is within distance ε.
-/
theorem prob_exists_close_bound
    {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
    {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
    (target : F) (ε : ℝ) (n : ℕ) :
    let S := {f | dist (ψ f) (ψ target) ≤ ε}
    let p := Pf S
    (Measure.pi (fun _ : Fin n => Pf)) { refs | ∃ i, dist (ψ (refs i)) (ψ target) ≤ ε } = 1 - (1 - p) ^ n := by
  -- Let's simplify the set {refs : Fin n → F | ∃ i, dist (ψ (refs i)) (ψ target) ≤ ε}.
  set S := {f : F | dist (ψ f) (ψ target) ≤ ε}
  have hSet_eq : {refs : Fin n → F | ∃ i, dist (ψ (refs i)) (ψ target) ≤ ε} = Set.univ \ {refs : Fin n → F | ∀ i, dist (ψ (refs i)) (ψ target) > ε} := by
    ext; aesop;
  -- The set {refs : Fin n → F | ∀ i, dist (ψ (refs i)) (ψ target) > ε} is the product of the complements of S.
  have hSet_compl_eq : {refs : Fin n → F | ∀ i, dist (ψ (refs i)) (ψ target) > ε} = Set.pi Set.univ fun i : Fin n => Sᶜ := by
    aesop;
  simp_all +decide [ MeasureTheory.measure_compl ];
  rw [ MeasureTheory.measure_diff ] <;> norm_num;
  · rw [ MeasureTheory.measure_compl ] <;> norm_num;
    exact measurableSet_le ( hψ.dist measurable_const ) measurable_const;
  · exact MeasurableSet.nullMeasurableSet ( MeasurableSet.univ_pi fun _ => MeasurableSet.compl ( measurableSet_le ( hψ.dist measurable_const ) measurable_const ) )

/-
DKPS concentration hypothesis: for any number of reference models n and any error tolerance ε, there exists a minimum number of responses R such that for any r ≥ R, the probability that the estimated perspectives of all reference models and the target model are within ε of their true perspectives is at least 1 - ε.
-/
open Metric MeasureTheory ProbabilityTheory

/-- DKPS concentration hypothesis: for any n and ε, there exists R such that for r ≥ R,
    the estimation error is within ε with probability at least 1 - ε. -/
def DKPS_concentration_hypothesis
  {F : Type*} {d : ℕ}
  (ψ : F → EuclideanSpace ℝ (Fin d))
  (Ω_est : Type*) [MeasurableSpace Ω_est] (P_est : Measure Ω_est)
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d)) : Prop :=
  ∀ (n : ℕ) (ε : ℝ), 0 < ε →
    ∃ R, ∀ r ≥ R, ∀ (refs : Fin n → F) (target : F),
      P_est { ω | (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ ε) ∧
                  dist (ψhat r ω target) (ψ target) ≤ ε } ≥ ENNReal.ofReal (1 - ε)

/-
Model distribution denseness assumption: for every model f and every ε > 0, the probability of the set of models f' such that the distance between their perspectives ψ(f') and ψ(f) is at most ε is strictly positive.
-/
open Metric MeasureTheory ProbabilityTheory

/-- Model distribution denseness: every neighborhood of every model has positive probability. -/
def Model_distribution_denseness
  {F : Type*} [MeasurableSpace F] (Pf : Measure F)
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) : Prop :=
  ∀ f : F, ∀ ε > 0, Pf { f' | dist (ψ f') (ψ f) ≤ ε } > 0

/-
A safe version of the nearest neighbor predictor that handles the case n=0 by returning 0.
-/
open Metric MeasureTheory ProbabilityTheory

noncomputable def nn_predictor_safe {F : Type*} {d : ℕ} (n : ℕ) (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) : ℝ :=
  if h : n = 0 then 0 else
  haveI : NeZero n := ⟨h⟩
  nn_predictor n refs target ψhat y

/-
If n is not zero, the safe nearest neighbor predictor is equal to the standard nearest neighbor predictor.
-/
open Metric MeasureTheory ProbabilityTheory

theorem nn_predictor_safe_eq_nn_predictor {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) :
    nn_predictor_safe n refs target ψhat y = nn_predictor n refs target ψhat y := by
  exact dif_neg ( NeZero.ne n )

/-
The probability that there exists a reference model close to the target tends to 1 as the number of reference models n goes to infinity, assuming the model distribution is dense.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

variable {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
variable {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d))

def GoodRefs (n : ℕ) (ε' : ℝ) (refs : Fin n → F) (target : F) : Prop :=
  ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε'

theorem prob_GoodRefs_tendsto_one
  (hψ : Measurable ψ)
  (h_dense : Model_distribution_denseness Pf ψ)
  (ε' : ℝ) (hε' : 0 < ε') :
  Tendsto (fun n => (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x | GoodRefs ψ n ε' x.1 x.2 }) atTop (nhds 1) := by
  simp +decide only [GoodRefs];
  -- Let's simplify the expression inside the limit.
  suffices h_suff : Filter.Tendsto (fun n => ∫⁻ (target : F), (∫⁻ (refs : Fin n → F), if ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε' then 1 else 0 ∂MeasureTheory.Measure.pi (fun _ => Pf)) ∂Pf) Filter.atTop (𝓝 1) by
    convert h_suff using 2;
    erw [ MeasureTheory.lintegral_lintegral_swap ];
    · erw [ MeasureTheory.Measure.prod_apply ];
      · congr! 2;
        rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
        exact?;
        · simp +decide [ Set.preimage ];
          exact Measurable.exists fun i => measurableSet_le ( measurable_const.dist ( hψ ) ) measurable_const |> MeasurableSet.mem;
        · filter_upwards [ ] with x using by simp +decide [ Set.indicator ] ;
      · simp +decide only [Set.setOf_exists];
        exact MeasurableSet.iUnion fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_fst ) |> Measurable.sub <| hψ.comp measurable_snd ) ) measurable_const;
    · refine' Measurable.aemeasurable _;
      refine' Measurable.ite _ measurable_const measurable_const;
      simp +decide only [Set.setOf_exists];
      exact MeasurableSet.iUnion fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_snd ) |> Measurable.sub <| hψ.comp measurable_fst ) ) measurable_const;
  -- By the properties of the measure, we can rewrite the inner integral as $1 - (1 - p(target))^n$.
  have h_inner : ∀ n : ℕ, ∀ target : F, ∫⁻ (refs : Fin n → F), (if ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε' then 1 else 0) ∂MeasureTheory.Measure.pi (fun _ => Pf) = 1 - (1 - Pf {f' | dist (ψ f') (ψ target) ≤ ε'}) ^ n := by
    intro n target
    have h_inner_eq : ∫⁻ (refs : Fin n → F), (if ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε' then 1 else 0) ∂MeasureTheory.Measure.pi (fun _ => Pf) = (MeasureTheory.Measure.pi (fun _ : Fin n => Pf)) { refs : Fin n → F | ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε' } := by
      rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
      exact?;
      · simp +decide only [Set.setOf_exists];
        exact MeasurableSet.iUnion fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i ) |> Measurable.sub <| measurable_const ) ) measurable_const;
      · norm_num [ Filter.EventuallyEq, Set.indicator ];
    have := @prob_exists_close_bound F _ Pf _ d ψ hψ target ε' n; aesop;
  -- By the Dominated Convergence Theorem, we can interchange the limit and the integral.
  have h_dominated : Filter.Tendsto (fun n => ∫⁻ (target : F), (1 - (1 - Pf {f' | dist (ψ f') (ψ target) ≤ ε'}) ^ n) ∂Pf) Filter.atTop (𝓝 (∫⁻ (target : F), 1 ∂Pf)) := by
    refine' MeasureTheory.tendsto_lintegral_of_dominated_convergence _ _ _ _ _;
    refine' fun target => 1;
    · intro n;
      refine' Measurable.sub measurable_const _;
      refine' Measurable.pow_const _ _;
      refine' Measurable.sub measurable_const _;
      convert measurable_measure_prodMk_right _;
      rotate_left;
      exact?;
      exact { p : F × F | Dist.dist ( ψ p.1 ) ( ψ p.2 ) ≤ ε' };
      · exact measurableSet_le ( measurable_norm.comp ( hψ.comp measurable_fst |> Measurable.sub <| hψ.comp measurable_snd ) ) measurable_const;
      · rfl;
    · exact fun n => Filter.Eventually.of_forall fun target => tsub_le_self;
    · simp +decide;
    · refine' Filter.Eventually.of_forall fun target => _;
      have h_lim : Filter.Tendsto (fun n => (1 - Pf {f' | dist (ψ f') (ψ target) ≤ ε'}) ^ n) Filter.atTop (𝓝 0) := by
        have h_lim : 1 - Pf {f' | dist (ψ f') (ψ target) ≤ ε'} < 1 := by
          rw [ ENNReal.sub_lt_self_iff ] <;> norm_num;
          exact h_dense target ε' hε';
        exact?;
      convert ENNReal.Tendsto.sub tendsto_const_nhds h_lim using 1 ; norm_num;
      swap;
      exact 1;
      norm_num [ ENNReal.tendsto_nhds ];
  aesop

/-
If the concentration bound holds for every fixed set of reference models and target model with probability at least 1 - ε over the estimation randomness, then it holds with probability at least 1 - ε over the joint distribution of reference models, target model, and estimation randomness.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

theorem prob_concentration_product
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d))
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (n : ℕ) (r : ℕ) (ε : ℝ)
  (h_conc : ∀ (refs : Fin n → F) (target : F),
      P_est { ω | (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ ε) ∧
                  dist (ψhat r ω target) (ψ target) ≤ ε } ≥ ENNReal.ofReal (1 - ε)) :
  let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  μ { x | let refs := x.1
          let target := x.2.1
          let ω := x.2.2
          (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ ε) ∧
          dist (ψhat r ω target) (ψ target) ≤ ε } ≥ ENNReal.ofReal (1 - ε) := by
  -- Applying Fubini's theorem, we can interchange the order of integration.
  have h_fubini : ∀ {E : Set ((Fin n → F) × F × Ω_est)}, MeasurableSet E → (MeasureTheory.Measure.prod (MeasureTheory.Measure.pi fun _ => Pf) (MeasureTheory.Measure.prod Pf P_est)) E = ∫⁻ x, ∫⁻ y, ∫⁻ z, (if (x, y, z) ∈ E then 1 else 0) ∂P_est ∂Pf ∂MeasureTheory.Measure.pi (fun _ : Fin n => Pf) := by
    intro E hE;
    erw [ MeasureTheory.Measure.prod_apply hE ];
    congr! 2;
    erw [ MeasureTheory.Measure.prod_apply ];
    · congr! 2;
      erw [ MeasureTheory.lintegral_indicator ] ; aesop;
      exact measurableSet_preimage ( measurable_const.prodMk ( measurable_const.prodMk measurable_id' ) ) hE;
    · exact hE.preimage ( measurable_prodMk_left );
  by_cases hε : 0 ≤ 1 - ε <;> simp_all +decide [ MeasureTheory.lintegral_const ];
  · by_contra h_contra;
    obtain ⟨E, hE⟩ : ∃ E : Set ((Fin n → F) × F × Ω_est), MeasurableSet E ∧ {x : (Fin n → F) × F × Ω_est | (∀ i, Dist.dist (ψhat r x.2.2 (x.1 i)) (ψ (x.1 i)) ≤ ε) ∧ Dist.dist (ψhat r x.2.2 x.2.1) (ψ x.2.1) ≤ ε} ⊆ E ∧ (MeasureTheory.Measure.prod (MeasureTheory.Measure.pi fun _ => Pf) (MeasureTheory.Measure.prod Pf P_est)) E < ENNReal.ofReal (1 - ε) := by
      exact ⟨ MeasureTheory.toMeasurable ( MeasureTheory.Measure.prod ( MeasureTheory.Measure.pi fun _ => Pf ) ( MeasureTheory.Measure.prod Pf P_est ) ) { x : ( Fin n → F ) × F × Ω_est | ( ∀ i, Dist.dist ( ψhat r x.2.2 ( x.1 i ) ) ( ψ ( x.1 i ) ) ≤ ε ) ∧ Dist.dist ( ψhat r x.2.2 x.2.1 ) ( ψ x.2.1 ) ≤ ε }, MeasureTheory.measurableSet_toMeasurable _ _, MeasureTheory.subset_toMeasurable _ _, by simpa only [ MeasureTheory.measure_toMeasurable ] using lt_of_not_ge h_contra ⟩;
    have h_fubini : ∫⁻ x, ∫⁻ y, ∫⁻ z, (if (x, y, z) ∈ E then 1 else 0) ∂P_est ∂Pf ∂MeasureTheory.Measure.pi (fun _ : Fin n => Pf) ≥ ENNReal.ofReal (1 - ε) := by
      have h_fubini : ∀ x : Fin n → F, ∫⁻ y, ∫⁻ z, (if (x, y, z) ∈ E then 1 else 0) ∂P_est ∂Pf ≥ ENNReal.ofReal (1 - ε) := by
        intro x
        have h_fubini : ∀ y : F, ∫⁻ z, (if (x, y, z) ∈ E then 1 else 0) ∂P_est ≥ ENNReal.ofReal (1 - ε) := by
          intro y
          have h_fubini : ∫⁻ z, (if (x, y, z) ∈ E then 1 else 0) ∂P_est ≥ P_est {z | (x, y, z) ∈ E} := by
            rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
            change ∫⁻ z in { z : Ω_est | ( x, y, z ) ∈ E }, 1 ∂P_est ≥ P_est { z : Ω_est | ( x, y, z ) ∈ E };
            · simp +decide [ MeasureTheory.lintegral_const ];
            · exact measurableSet_preimage ( measurable_const.prodMk ( measurable_const.prodMk measurable_id' ) ) hE.1;
            · norm_num [ Filter.EventuallyEq, Set.indicator ]
          generalize_proofs at *; (
          exact le_trans ( h_conc x y ) ( h_fubini.trans' ( MeasureTheory.measure_mono fun z hz => hE.2.1 hz ) ))
        generalize_proofs at *; (
        refine' le_trans _ ( MeasureTheory.lintegral_mono fun y => h_fubini y ) ; simp +decide [ hε ]);
      refine' le_trans _ ( MeasureTheory.lintegral_mono fun x => h_fubini x );
      simp +decide [ MeasureTheory.Measure.pi_univ ];
    exact h_fubini.not_lt ( by simpa only [ * ] using hE.2.2 );
  · simp +decide [ ENNReal.ofReal_eq_zero.mpr ( sub_nonpos.mpr hε.le ) ]

/-
If the concentration bound holds for every fixed set of reference models and target model with probability at least 1 - ε over the estimation randomness, then it holds with probability at least 1 - ε over the joint distribution of reference models, target model, and estimation randomness.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

theorem prob_concentration_product_v2
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d))
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (n : ℕ) (r : ℕ) (ε : ℝ)
  (h_conc : ∀ (refs : Fin n → F) (target : F),
      P_est { ω | (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ ε) ∧
                  dist (ψhat r ω target) (ψ target) ≤ ε } ≥ ENNReal.ofReal (1 - ε)) :
  let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  μ { x | let refs := x.1
          let target := x.2.1
          let ω := x.2.2
          (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ ε) ∧
          dist (ψhat r ω target) (ψ target) ≤ ε } ≥ ENNReal.ofReal (1 - ε) := by
  convert prob_concentration_product Pf ψ P_est ψhat n r ε h_conc using 1

/-
Probability intersection bound: P(A ∩ B) ≥ 1 - (δ1 + δ2) given P(A) ≥ 1 - δ1 and P(B) ≥ 1 - δ2.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma prob_inter_bound
  {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
  {A B : Set Ω} (hA : MeasurableSet A) (hB : MeasurableSet B)
  (δ1 δ2 : ℝ)
  (hP_A : P A ≥ ENNReal.ofReal (1 - δ1))
  (hP_B : P B ≥ ENNReal.ofReal (1 - δ2))
  (hδ1 : 0 ≤ δ1) (hδ2 : 0 ≤ δ2) (h_sum : δ1 + δ2 ≤ 1) :
  P (A ∩ B) ≥ ENNReal.ofReal (1 - (δ1 + δ2)) := by
  -- By the properties of probability measures, we have P(A ∩ B) = P(A) + P(B) - P(A ∪ B).
  have h_inter : P (A ∩ B) = P A + P B - P (A ∪ B) := by
    rw [ ← MeasureTheory.measure_union_add_inter A hB, ENNReal.add_sub_cancel_left ( MeasureTheory.measure_ne_top _ _ ) ];
  refine' le_trans _ ( h_inter.symm ▸ tsub_le_tsub_right ( add_le_add hP_A hP_B ) _ );
  refine' le_trans _ ( tsub_le_tsub_left ( MeasureTheory.measure_mono ( show A ∪ B ⊆ Set.univ from Set.subset_univ _ ) ) _ );
  rw [ ← ENNReal.ofReal_add ] <;> norm_num <;> try linarith;
  rw [ show 1 - ( δ1 + δ2 ) = ( 1 - δ1 + ( 1 - δ2 ) ) - 1 by ring, ENNReal.ofReal_sub ] <;> norm_num

/-
Lemma: If the conditions for the deterministic error bound are met, and the bound is less than the square root of ε, then the squared error of the predictor is at most ε.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

theorem deterministic_implication
  {F : Type*} {d : ℕ}
  (n : ℕ) [NeZero n]
  (refs : Fin n → F) (target : F)
  (ψ : F → EuclideanSpace ℝ (Fin d)) (ψhat : F → EuclideanSpace ℝ (Fin d))
  (y : F → ℝ)
  (c ε' γ ε : ℝ)
  (h_nonneg_γ : 0 ≤ γ)
  (h_good_refs : ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε')
  (h_conc_refs : ∀ i, dist (ψhat (refs i)) (ψ (refs i)) ≤ c)
  (h_conc_target : dist (ψhat target) (ψ target) ≤ c)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_bound : γ * (4 * c + ε') ≤ Real.sqrt ε)
  (h_eps : 0 ≤ ε) :
  (nn_predictor_safe n refs target ψhat y - y target) ^ 2 ≤ ε := by
    -- Apply the deterministic error bound result.
    have deterministic_bound : |(nn_predictor n refs target ψhat y) - y target| ≤ γ * (4 * c + ε') := by
      apply deterministic_error_bound n refs target ψ ψhat y c ε' γ h_nonneg_γ h_conc_refs h_conc_target h_good_refs h_lip;
    rw [ nn_predictor_safe_eq_nn_predictor ];
    nlinarith [ abs_le.mp deterministic_bound, Real.mul_self_sqrt h_eps ]

/-
The measure of a cylinder set {x | x.1 ∈ S} in a product measure μ1 × μ2 (where μ2 is a probability measure) is equal to μ1(S).
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma measure_cylinder
  {Ω1 Ω2 : Type*} [MeasurableSpace Ω1] [MeasurableSpace Ω2]
  (μ1 : Measure Ω1) (μ2 : Measure Ω2) [IsProbabilityMeasure μ2]
  (S : Set Ω1) (hS : MeasurableSet S) :
  (μ1.prod μ2) { x | x.1 ∈ S } = μ1 S := by
  have h_prod : { x : Ω1 × Ω2 | x.1 ∈ S } = S ×ˢ Set.univ := by ext; simp
  rw [h_prod, Measure.prod_prod]
  simp [measure_univ]

/-
Theorem: Under the DKPS concentration and model denseness assumptions, for any ε > 0, there exist sufficiently large n (number of reference models) and r (number of responses) such that the squared prediction error of the DKPS-NN predictor is at most ε with probability at least 1 - ε.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

theorem dkps_nn_consistency
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ ε > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    μ { x | let refs := x.1
            let target := x.2.1
            let ω := x.2.2
            (nn_predictor_safe n refs target (ψhat r ω) y - y target) ^ 2 ≤ ε } ≥ ENNReal.ofReal (1 - ε) := by
  intro ε hε_pos
  set ε_sqrt := Real.sqrt ε
  set ε' := ε_sqrt / (2 * γ)
  set c := ε_sqrt / (8 * γ);
  -- Use `prob_GoodRefs_tendsto_one` to find $N$ such that for $n \ge N$, the probability of `GoodRefs n ε'` is at least $1 - ε / 2$.
  obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ n ≥ N, (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x : (Fin n → F) × F | GoodRefs ψ n ε' x.1 x.2 } ≥ ENNReal.ofReal (1 - ε / 2) := by
    have hN : Filter.Tendsto (fun n => (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x : (Fin n → F) × F | GoodRefs ψ n ε' x.1 x.2 }) Filter.atTop (nhds 1) := by
      convert prob_GoodRefs_tendsto_one Pf ψ hψ h_dense ε' ( div_pos ( Real.sqrt_pos.mpr hε_pos ) ( mul_pos zero_lt_two hγ ) ) using 1;
    rw [ ENNReal.tendsto_atTop ] at hN;
    · obtain ⟨ N, hN ⟩ := hN ( ENNReal.ofReal ( ε / 2 ) ) ( ENNReal.ofReal_pos.mpr ( half_pos hε_pos ) );
      refine' ⟨ N, fun n hn => le_trans _ ( hN n hn |>.1 ) ⟩;
      rw [ ENNReal.ofReal_sub ] <;> norm_num ; linarith;
    · norm_num;
  use N + 1;
  intro n hn
  obtain ⟨R, hR⟩ : ∃ R : ℕ, ∀ r ≥ R, let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est);
    μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
      (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c } ≥ ENNReal.ofReal (1 - ε / 2) := by
        obtain ⟨ R, hR ⟩ := h_conc n ( Min.min c ( ε / 2 ) ) ( lt_min ( div_pos ( Real.sqrt_pos.mpr hε_pos ) ( by positivity ) ) ( half_pos hε_pos ) );
        refine' ⟨ R, fun r hr => _ ⟩;
        -- Apply the concentration hypothesis to get the desired probability bound.
        have h_conc_bound : let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est);
          μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
            (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ min c (ε / 2)) ∧ dist (ψhat r ω target) (ψ target) ≤ min c (ε / 2) } ≥ ENNReal.ofReal (1 - min c (ε / 2)) := by
              convert prob_concentration_product_v2 Pf ψ P_est ψhat n r ( Min.min c ( ε / 2 ) ) ( hR r hr ) using 1;
        refine' le_trans _ ( h_conc_bound.trans _ );
        · exact ENNReal.ofReal_le_ofReal ( sub_le_sub_left ( min_le_right _ _ ) _ );
        · refine' MeasureTheory.measure_mono _;
          exact fun x hx => ⟨ fun i => le_trans ( hx.1 i ) ( min_le_left _ _ ), le_trans ( hx.2 ) ( min_le_left _ _ ) ⟩;
  use R;
  intro r hr
  let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  have h_inter : μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
    (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c ∧ GoodRefs ψ n ε' x.1 x.2.1 } ≥ ENNReal.ofReal (1 - ε) := by
      have h_inter : μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
        (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c } ≥ ENNReal.ofReal (1 - ε / 2) ∧
        μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
        GoodRefs ψ n ε' x.1 x.2.1 } ≥ ENNReal.ofReal (1 - ε / 2) := by
          refine' ⟨ hR r hr, _ ⟩;
          convert hN n ( by linarith ) using 1;
          erw [ MeasureTheory.Measure.prod_apply ];
          · erw [ MeasureTheory.Measure.prod_apply ];
            · congr! 2;
              erw [ MeasureTheory.Measure.prod_apply ];
              · rw [ MeasureTheory.lintegral_congr_ae, MeasureTheory.lintegral_indicator ];
                exact?;
                · simp +decide [ GoodRefs ];
                  exact Measurable.exists fun i => measurableSet_le ( measurable_const.dist ( hψ ) ) measurable_const |> MeasurableSet.mem;
                · filter_upwards [ ] with x ; by_cases hx : GoodRefs ψ n ε' ‹_› x <;> simp +decide [ hx ];
              · simp +decide [ GoodRefs ];
                exact Measurable.exists fun _ => measurableSet_le ( measurable_const.dist ( hψ.comp measurable_fst ) ) measurable_const |> MeasurableSet.mem;
            · simp +decide [ GoodRefs ];
              exact Measurable.exists fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_fst ) |> Measurable.sub <| hψ.comp measurable_snd ) ) measurable_const |> MeasurableSet.mem;
          · simp +decide [ GoodRefs ];
            exact Measurable.exists fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_fst ) |> Measurable.sub <| hψ.comp measurable_snd.fst ) ) measurable_const |> MeasurableSet.mem;
      have h_inter : μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
        (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c } + μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
        GoodRefs ψ n ε' x.1 x.2.1 } ≤ μ Set.univ + μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
        (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c ∧ GoodRefs ψ n ε' x.1 x.2.1 } := by
          rw [ ← MeasureTheory.measure_union_add_inter ];
          · refine' add_le_add _ _;
            · exact MeasureTheory.measure_mono ( Set.subset_univ _ );
            · exact MeasureTheory.measure_mono fun x hx => by aesop;
          · simp +decide [ GoodRefs ];
            exact Measurable.exists fun i => measurableSet_le ( measurable_norm.comp ( hψ.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_fst ) |> Measurable.sub <| hψ.comp measurable_snd.fst ) ) measurable_const |> MeasurableSet.mem;
      simp +zetaDelta at *;
      by_cases hε : ε ≤ 2;
      · have h_inter : ENNReal.ofReal (1 - ε / 2) + ENNReal.ofReal (1 - ε / 2) ≤ 1 + μ { x : (Fin n → F) × F × Ω_est | let refs := x.1; let target := x.2.1; let ω := x.2.2;
          (∀ i, dist (ψhat r ω (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat r ω target) (ψ target) ≤ c ∧ GoodRefs ψ n ε' x.1 x.2.1 } := by
            exact le_trans ( add_le_add ( by tauto ) ( by tauto ) ) h_inter;
        rw [ ← ENNReal.ofReal_add ] at * <;> try linarith;
        rw [ ENNReal.ofReal_le_iff_le_toReal ] at * <;> norm_num at *;
        rw [ ENNReal.toReal_add ] at * <;> norm_num at *;
        linarith;
      · rw [ ENNReal.ofReal_eq_zero.mpr ( by linarith ) ] ; norm_num;
  refine' le_trans h_inter ( MeasureTheory.measure_mono _ );
  rintro ⟨ refs, target, ω ⟩ ⟨ h₁, h₂, h₃ ⟩;
  have h_bound : γ * (4 * c + ε') ≤ Real.sqrt ε := by
    nlinarith [ Real.sqrt_nonneg ε, Real.sq_sqrt hε_pos.le, mul_div_cancel₀ ( Real.sqrt ε ) ( by positivity : ( 8 * γ ) ≠ 0 ), mul_div_cancel₀ ( Real.sqrt ε ) ( by positivity : ( 2 * γ ) ≠ 0 ) ];
  convert deterministic_implication n refs target ψ ( ψhat r ω ) y c ε' γ ε _ _ _ _ _ _ _ using 1;
  any_goals positivity;
  any_goals assumption;
  exact ⟨ by linarith ⟩

/-
For any ε' > 0 and δ > 0, there exists N such that for all n ≥ N, the probability of GoodRefs is at least 1 - δ.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma exists_N_good_refs
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  (h_dense : Model_distribution_denseness Pf ψ)
  (ε' : ℝ) (hε' : 0 < ε') (δ : ℝ) (hδ : 0 < δ) :
  ∃ N, ∀ n ≥ N, (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x | GoodRefs ψ n ε' x.1 x.2 } ≥ ENNReal.ofReal (1 - δ) := by
    have h_prob_GoodRefs_tendsto_one : Filter.Tendsto (fun n => (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x : (Fin n → F) × F | GoodRefs ψ n ε' x.1 x.2 }) Filter.atTop (nhds 1) := by
      apply_rules [ prob_GoodRefs_tendsto_one ];
    convert h_prob_GoodRefs_tendsto_one.eventually ( le_mem_nhds _ ) using 1;
    exact?;
    exact ENNReal.ofReal_lt_one.mpr ( by linarith )

/-
Theorem: Under the DKPS concentration and model denseness assumptions, for any ε > 0, there exist sufficiently large n (number of reference models) and r (number of responses) such that the squared prediction error of the DKPS-NN predictor is at most ε with probability at least 1 - ε.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

theorem dkps_nn_consistency_thm
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ ε > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    μ { x | let refs := x.1
            let target := x.2.1
            let ω := x.2.2
            (nn_predictor_safe n refs target (ψhat r ω) y - y target) ^ 2 ≤ ε } ≥ ENNReal.ofReal (1 - ε) := by
              exact?

/-
Lemma: For any n and ε_conc > 0, there exists R such that for all r ≥ R, the probability of the concentration event in the product space is at least 1 - ε_conc.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma exists_R_concentration
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d))
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (n : ℕ) (ε_conc : ℝ) (h_conc_pos : 0 < ε_conc) :
  ∃ R, ∀ r ≥ R,
    let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    μ { x | (∀ i, dist (ψhat r x.2.2 (x.1 i)) (ψ (x.1 i)) ≤ ε_conc) ∧
            dist (ψhat r x.2.2 x.2.1) (ψ x.2.1) ≤ ε_conc } ≥ ENNReal.ofReal (1 - ε_conc) := by
  obtain ⟨R, hR⟩ := h_conc n ε_conc h_conc_pos
  use R
  intro r hr
  specialize hR r hr
  apply prob_concentration_product_v2 Pf ψ P_est ψhat n r ε_conc hR

/-
The set of (refs, target) pairs satisfying GoodRefs is measurable.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma measurable_good_refs
  {F : Type*} [MeasurableSpace F]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  (n : ℕ) (ε' : ℝ) :
  MeasurableSet { x : (Fin n → F) × F | GoodRefs ψ n ε' x.1 x.2 } := by
    convert MeasurableSet.iUnion fun i => measurableSet_le ( show Measurable fun x : ( Fin n → F ) × F => dist ( ψ ( x.1 i ) ) ( ψ ( x.2 ) ) from ?_ ) measurable_const using 1;
    exact?;
    fun_prop

/-
The probability of GoodRefs in the product space (including the estimation randomness) is the same as in the space without it, since GoodRefs does not depend on the estimation randomness.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

lemma prob_good_refs_lift
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (n : ℕ) (ε' : ℝ) :
  let μ := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  let μ_small := (Measure.pi (fun _ : Fin n => Pf)).prod Pf
  μ { x | GoodRefs ψ n ε' x.1 x.2.1 } = μ_small { y | GoodRefs ψ n ε' y.1 y.2 } := by
    simp +decide [ MeasureTheory.Measure.prod_apply, MeasureTheory.Measure.pi ];
    rw [ MeasureTheory.Measure.prod_apply, MeasureTheory.Measure.prod_apply ];
    · simp +decide [ Set.preimage, MeasureTheory.Measure.prod_apply ];
      congr! 2;
      erw [ show { x : F × Ω_est | GoodRefs ψ n ε' _ x.1 } = ( { x : F | GoodRefs ψ n ε' _ x } ×ˢ Set.univ ) by ext ; aesop, MeasureTheory.Measure.prod_prod ] ; simp +decide;
    · exact?;
    · have h_measurable : MeasurableSet { x : (Fin n → F) × F | GoodRefs ψ n ε' x.1 x.2 } := by
        exact?;
      convert h_measurable.preimage ( measurable_fst.prodMk measurable_snd.fst ) using 1

/-
Definitions of Mean Squared Error (MSE) for the baseline predictor and the DKPS predictor.
MSE_baseline is the expected squared difference between the subset score and the full score.
MSE_DKPS is the expected squared difference between the DKPS nearest neighbor prediction and the full score, conditional on the reference models and estimation randomness.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/-- Mean Squared Error of a deterministic predictor -/
noncomputable def MSE_baseline
  {F : Type*} [MeasurableSpace F] (Pf : Measure F)
  (yQ : F → ℝ) (y : F → ℝ) : ℝ :=
  ∫ f, (yQ f - y f)^2 ∂Pf

/-- Mean Squared Error of the DKPS predictor given fixed references and estimation randomness -/
noncomputable def MSE_DKPS
  {F : Type*} [MeasurableSpace F] (Pf : Measure F)
  {d : ℕ}
  (n : ℕ) (refs : Fin n → F)
  (target_y : F → ℝ)
  (ψhat_slice : F → EuclideanSpace ℝ (Fin d)) : ℝ :=
  ∫ f, (nn_predictor_safe n refs f ψhat_slice target_y - target_y f)^2 ∂Pf

/-
If a non-negative random variable X is bounded by B and is less than or equal to ε with probability at least 1 - δ, then its expectation is at most ε + B * δ.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: If a random variable X is bounded by B almost everywhere and P(X ≤ ε) ≥ 1 - δ, then E[X] ≤ ε + B * δ.
-/
lemma expectation_bound_of_high_prob_bound
  {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
  (X : Ω → ℝ) (hX_meas : Measurable X)
  (B : ℝ) (hB : 0 ≤ B)
  (hX_bound : ∀ᵐ ω ∂P, 0 ≤ X ω ∧ X ω ≤ B)
  (ε δ : ℝ) (hε : 0 ≤ ε) (hδ : 0 ≤ δ)
  (h_prob : P {ω | X ω ≤ ε} ≥ ENNReal.ofReal (1 - δ)) :
  ∫ ω, X ω ∂P ≤ ε + B * δ := by
    -- Split the integral into two parts: one over the set {X ≤ ε} and one over {X > ε}.
    have h_split_integral : ∫ ω, X ω ∂P = (∫ ω in {ω | X ω ≤ ε}, X ω ∂P) + (∫ ω in {ω | X ω > ε}, X ω ∂P) := by
      rw [ ← MeasureTheory.setIntegral_union ] <;> norm_num;
      · rw [ show { ω | X ω ≤ ε } ∪ { ω | ε < X ω } = Set.univ by ext ω; by_cases h : X ω ≤ ε <;> aesop ] ; simp +decide [ hX_bound ] ;
      · exact Set.disjoint_left.mpr fun ω hω₁ hω₂ => hω₁.out.not_lt hω₂.out;
      · exact measurableSet_Ioi.mem.comp hX_meas;
      · refine' MeasureTheory.Integrable.mono' _ _ _;
        exacts [ fun ω => B, MeasureTheory.integrable_const _, hX_meas.aestronglyMeasurable, Filter.eventually_of_mem ( MeasureTheory.ae_restrict_of_ae hX_bound ) fun ω hω => abs_le.mpr ⟨ by linarith [ hω.1 ], by linarith [ hω.2 ] ⟩ ];
      · refine' MeasureTheory.Integrable.mono' _ _ _;
        exacts [ fun ω => B, MeasureTheory.integrable_const _, hX_meas.aestronglyMeasurable, Filter.eventually_of_mem ( MeasureTheory.ae_restrict_of_ae hX_bound ) fun ω hω => abs_le.mpr ⟨ by linarith [ hω.1 ], by linarith [ hω.2 ] ⟩ ];
    -- On the set {X ≤ ε}, the integral is bounded by ε * P(X ≤ ε) ≤ ε.
    have h_integral_le_ε : ∫ ω in {ω | X ω ≤ ε}, X ω ∂P ≤ ε * (P {ω | X ω ≤ ε}).toReal := by
      refine' le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _;
      refine' fun ω => ε;
      · filter_upwards [ MeasureTheory.ae_restrict_of_ae hX_bound ] with ω hω using hω.1;
      · norm_num;
      · filter_upwards [ MeasureTheory.ae_restrict_mem ( show MeasurableSet { ω | X ω ≤ ε } from measurableSet_le hX_meas measurable_const ) ] with ω hω using hω;
      · simp +decide [ mul_comm, MeasureTheory.measureReal_def ];
    -- On the set {X > ε}, the integral is bounded by B * P(X > ε).
    have h_integral_gt_ε : ∫ ω in {ω | X ω > ε}, X ω ∂P ≤ B * (P {ω | X ω > ε}).toReal := by
      refine' le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _;
      refine' fun ω => B;
      · filter_upwards [ MeasureTheory.ae_restrict_of_ae hX_bound ] with ω hω using hω.1;
      · norm_num;
      · filter_upwards [ MeasureTheory.ae_restrict_of_ae hX_bound ] with ω hω using hω.2;
      · simp +decide [ mul_comm ];
        rfl;
    -- Since $P(X \leq \epsilon) \geq 1 - \delta$, we have $P(X > \epsilon) \leq \delta$.
    have h_prob_gt_ε : (P {ω | X ω > ε}).toReal ≤ δ := by
      have h_prob_gt_ε : (P {ω | X ω > ε}).toReal = 1 - (P {ω | X ω ≤ ε}).toReal := by
        rw [ show { ω | X ω > ε } = ( Set.univ \ { ω | X ω ≤ ε } ) by ext; simp +decide, MeasureTheory.measure_diff ] <;> norm_num;
        · rw [ ENNReal.toReal_sub_of_le ] <;> norm_num;
          exact le_trans ( MeasureTheory.measure_mono ( Set.subset_univ _ ) ) ( by norm_num );
        · exact measurableSet_le hX_meas measurable_const |> MeasurableSet.nullMeasurableSet;
      rw [ h_prob_gt_ε, sub_le_comm ];
      contrapose! h_prob;
      rw [ ENNReal.lt_ofReal_iff_toReal_lt ] <;> aesop;
    nlinarith [ show ( P { ω | X ω ≤ ε } |> ENNReal.toReal ) ≤ 1 by exact le_trans ( ENNReal.toReal_mono ( MeasureTheory.measure_ne_top _ _ ) ( MeasureTheory.measure_mono ( Set.subset_univ _ ) ) ) ( by norm_num ) ]

/-
Definitions of canonical nearest neighbor index, predictor, and MSE.
The canonical index uses `List.argmin` to ensure deterministic tie-breaking and measurability.
The specification theorem states that it indeed minimizes the distance.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Canonical nearest neighbor index using List.argmin on the list of indices.
Selects the index i that minimizes the distance, breaking ties by choosing the first one in the list (which is sorted for Fin n).
-/
noncomputable def nn_index_canonical {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) : Fin n :=
  let l := (Finset.univ : Finset (Fin n)).toList
  let f := fun i => dist (ψhat (refs i)) (ψhat target)
  match l.argmin f with
  | some i => i
  | none => Fin.mk 0 (NeZero.pos n)

/--
The canonical nearest neighbor index minimizes the distance.
-/
theorem nn_index_canonical_spec {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) :
    let i_star := nn_index_canonical n refs target ψhat
    ∀ j : Fin n, dist (ψhat (refs i_star)) (ψhat target) ≤ dist (ψhat (refs j)) (ψhat target) := by
      convert Classical.choose_spec ( Finset.exists_min_image Finset.univ ( fun i => dist ( ψhat ( refs i ) ) ( ψhat target ) ) Finset.univ_nonempty ) using 1;
      unfold nn_index_canonical;
      cases h' : List.argmin ( fun i => dist ( ψhat ( refs i ) ) ( ψhat target ) ) ( Finset.univ.toList ) <;> simp_all +decide;
      · exact absurd h' ( Finset.Nonempty.ne_empty ⟨ 0, Finset.mem_univ _ ⟩ );
      · rw [ List.argmin_eq_some_iff ] at h';
        simp +zetaDelta at *;
        exact iff_of_true h'.1 ( Classical.choose_spec ( Finset.exists_min_image Finset.univ ( fun i => dist ( ψhat ( refs i ) ) ( ψhat target ) ) Finset.univ_nonempty ) |> fun h => by aesop )

/--
Canonical nearest neighbor predictor.
-/
noncomputable def nn_predictor_canonical {F : Type*} {d : ℕ} (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) : ℝ :=
  y (refs (nn_index_canonical n refs target ψhat))

/--
Safe version of the canonical predictor.
-/
noncomputable def nn_predictor_canonical_safe {F : Type*} {d : ℕ} (n : ℕ) (refs : Fin n → F) (target : F) (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) : ℝ :=
  if h : n = 0 then 0 else
  haveI : NeZero n := ⟨h⟩
  nn_predictor_canonical n refs target ψhat y

/--
MSE of the canonical DKPS predictor.
-/
noncomputable def MSE_DKPS_canonical
  {F : Type*} [MeasurableSpace F] (Pf : Measure F)
  {d : ℕ}
  (n : ℕ) (refs : Fin n → F)
  (target_y : F → ℝ)
  (ψhat_slice : F → EuclideanSpace ℝ (Fin d)) : ℝ :=
  ∫ f, (nn_predictor_canonical_safe n refs f ψhat_slice target_y - target_y f)^2 ∂Pf

/-
If the estimated perspectives are close to the true perspectives (within c), and there is a reference model close to the target (within ε'), then the canonical nearest neighbor predictor has error at most γ * (4c + ε').
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Deterministic error bound for the canonical predictor.
-/
theorem deterministic_error_bound_canonical
  {F : Type*} {d : ℕ}
  (n : ℕ) [NeZero n]
  (refs : Fin n → F) (target : F)
  (ψ : F → EuclideanSpace ℝ (Fin d)) (ψhat : F → EuclideanSpace ℝ (Fin d))
  (y : F → ℝ)
  (c ε' γ : ℝ)
  (h_nonneg_γ : 0 ≤ γ)
  (h_conc_refs : ∀ i, dist (ψhat (refs i)) (ψ (refs i)) ≤ c)
  (h_conc_target : dist (ψhat target) (ψ target) ≤ c)
  (h_close : ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε')
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f')) :
  |nn_predictor_canonical n refs target ψhat y - y target| ≤ γ * (4 * c + ε') := by
    obtain ⟨ j, hj ⟩ := h_close;
    have h_dist : dist (ψhat (refs (nn_index_canonical n refs target ψhat))) (ψhat target) ≤ ε' + 2 * c := by
      have h_dist : dist (ψhat (refs (nn_index_canonical n refs target ψhat))) (ψhat target) ≤ dist (ψhat (refs j)) (ψhat target) := by
        -- By definition of `nn_index_canonical`, we know that `dist (ψhat (refs (nn_index_canonical n refs target ψhat))) (ψhat target) ≤ dist (ψhat (refs j)) (ψhat target)` because `nn_index_canonical` is the index that minimizes this distance.
        apply nn_index_canonical_spec;
      have h_dist : dist (ψhat (refs j)) (ψhat target) ≤ dist (ψhat (refs j)) (ψ (refs j)) + dist (ψ (refs j)) (ψ target) + dist (ψ (target)) (ψhat target) := by
        exact dist_triangle4 _ _ _ _;
      linarith [ h_conc_refs j, h_conc_target, dist_comm ( ψ target ) ( ψhat target ) ];
    have h_dist : dist (ψ (refs (nn_index_canonical n refs target ψhat))) (ψ target) ≤ ε' + 4 * c := by
      have h_dist : dist (ψ (refs (nn_index_canonical n refs target ψhat))) (ψ target) ≤ dist (ψ (refs (nn_index_canonical n refs target ψhat))) (ψhat (refs (nn_index_canonical n refs target ψhat))) + dist (ψhat (refs (nn_index_canonical n refs target ψhat))) (ψhat target) + dist (ψhat target) (ψ target) := by
        exact dist_triangle4 _ _ _ _;
      linarith [ h_conc_refs ( nn_index_canonical n refs target ψhat ), dist_comm ( ψ ( refs ( nn_index_canonical n refs target ψhat ) ) ) ( ψhat ( refs ( nn_index_canonical n refs target ψhat ) ) ) ];
    exact le_trans ( h_lip _ _ ) ( by nlinarith )

/-
For any ε' > 0 and δ > 0, if the model distribution is dense, then for sufficiently large n, the probability (over references and target) that there exists a reference close to the target is at least 1 - δ.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
The event that the estimated perspectives are concentrated around the true perspectives.
-/
def Event_Concentration
  {F : Type*} {d : ℕ}
  (ψ : F → EuclideanSpace ℝ (Fin d))
  (ψhat : F → EuclideanSpace ℝ (Fin d))
  (n : ℕ) (refs : Fin n → F) (target : F)
  (c : ℝ) : Prop :=
  (∀ i, dist (ψhat (refs i)) (ψ (refs i)) ≤ c) ∧ dist (ψhat target) (ψ target) ≤ c

/--
The event that there exists a reference model close to the target in the true perspective space.
-/
def Event_GoodRef
  {F : Type*} {d : ℕ}
  (ψ : F → EuclideanSpace ℝ (Fin d))
  (n : ℕ) (refs : Fin n → F) (target : F)
  (ε' : ℝ) : Prop :=
  ∃ j, dist (ψ (refs j)) (ψ target) ≤ ε'

/--
Lemma: Probability of GoodRef is high for large n.
-/
lemma prob_Event_GoodRef_high
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  (h_dense : Model_distribution_denseness Pf ψ)
  (ε' : ℝ) (hε' : 0 < ε')
  (δ : ℝ) (hδ : 0 < δ) :
  ∃ N, ∀ n ≥ N,
    (Measure.pi (fun _ : Fin n => Pf)).prod Pf { x | Event_GoodRef ψ n x.1 x.2 ε' } ≥ ENNReal.ofReal (1 - δ) := by
      convert exists_N_good_refs Pf ψ hψ h_dense ε' hε' δ hδ

/-
The function that maps (references, target, estimation randomness) to the nearest neighbor index is measurable.
This is because the index is determined by comparing distances, which are measurable functions of the inputs.
Since the index set is finite, we just need to show that the preimage of each index is measurable.
The condition "index = k" is a boolean combination of distance inequalities, which are measurable.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The canonical nearest neighbor index is jointly measurable in references, target, and estimation randomness.
-/
lemma measurable_nn_index_canonical_joint
  {F : Type*} [MeasurableSpace F]
  {d : ℕ}
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (n r : ℕ) [NeZero n] :
  Measurable (fun p : (Fin n → F) × F × Ω_est => nn_index_canonical n p.1 p.2.1 (ψhat r p.2.2)) := by
    unfold nn_index_canonical;
    have h_min_meas : ∀ i j : Fin n, MeasurableSet {p : (Fin n → F) × F × Ω_est | dist (ψhat r p.2.2 (p.1 i)) (ψhat r p.2.2 p.2.1) ≤ dist (ψhat r p.2.2 (p.1 j)) (ψhat r p.2.2 p.2.1)} := by
      intro i j
      have h_meas_dist : Measurable (fun p : (Fin n → F) × F × Ω_est => dist (ψhat r p.2.2 (p.1 i)) (ψhat r p.2.2 p.2.1)) ∧ Measurable (fun p : (Fin n → F) × F × Ω_est => dist (ψhat r p.2.2 (p.1 j)) (ψhat r p.2.2 p.2.1)) := by
        constructor;
        · fun_prop;
        · fun_prop
      generalize_proofs at *; (
      exact measurableSet_le h_meas_dist.1 h_meas_dist.2);
    have h_min_meas : ∀ i : Fin n, MeasurableSet {p : (Fin n → F) × F × Ω_est | List.argmin (fun i => dist (ψhat r p.2.2 (p.1 i)) (ψhat r p.2.2 p.2.1)) (Finset.univ.toList) = some i} := by
      simp +decide [ List.argmin_eq_some_iff ];
      intro i;
      refine' Measurable.and _ _;
      · exact Measurable.forall fun j => MeasurableSet.mem ( h_min_meas i j );
      · refine' Measurable.forall _;
        intro j;
        refine' Measurable.imp _ _;
        · exact MeasurableSet.mem ( h_min_meas _ _ );
        · exact?;
    refine' measurable_of_Iic _;
    intro x;
    convert MeasurableSet.iUnion ( fun i : Fin n => MeasurableSet.iUnion ( fun hi : i ≤ x => h_min_meas i ) ) using 1;
    ext p; simp [Set.mem_preimage, Set.mem_Iic];
    cases h : List.argmin ( fun i => dist ( ψhat r p.2.2 ( p.1 i ) ) ( ψhat r p.2.2 p.2.1 ) ) Finset.univ.toList <;> simp +decide [ h ];
    simp_all +decide [ List.argmin_eq_none ];
    exact Finset.ne_empty_of_mem ( Finset.mem_univ x ) h

/-
The Mean Squared Error of the canonical DKPS predictor, as a function of the reference models and the estimation randomness, is measurable. This allows us to consider it as a random variable and bound its probability.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The MSE of the canonical DKPS predictor is a measurable function of the references and estimation randomness.
-/
lemma measurable_mse_dkps_canonical
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ}
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (n r : ℕ) :
  Measurable (fun p : (Fin n → F) × Ω_est => MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2)) := by
    by_cases hn : NeZero n <;> simp +decide [ hn, MSE_DKPS_canonical ];
    · -- The integrand is a composition of measurable functions, hence measurable.
      have h_integrand_meas : Measurable (fun p : (Fin n → F) × Ω_est × F => (nn_predictor_canonical n p.1 p.2.2 (ψhat r p.2.1) y - y p.2.2)^2) := by
        -- The index function is measurable, and the function that maps the index to the corresponding reference model is also measurable.
        have h_index_meas : Measurable (fun p : (Fin n → F) × Ω_est × F => nn_index_canonical n p.1 p.2.2 (ψhat r p.2.1)) := by
          convert measurable_nn_index_canonical_joint ψhat h_ψhat_meas n r using 1;
          constructor <;> intro h <;> have := h.comp ( measurable_fst.prodMk ( measurable_snd.comp measurable_snd |> Measurable.prodMk <| measurable_fst.comp measurable_snd ) ) <;> aesop;
        have h_ref_meas : Measurable (fun p : (Fin n → F) × Ω_est × F => y (p.1 (nn_index_canonical n p.1 p.2.2 (ψhat r p.2.1)))) := by
          apply_rules [ Measurable.comp, hy_meas ];
          have h_ref_meas : ∀ i : Fin n, Measurable (fun p : (Fin n → F) × Ω_est × F => p.1 i) := by
            exact fun i => measurable_pi_apply i |> Measurable.comp <| measurable_fst;
          convert Measurable.comp ( show Measurable fun p : Fin n × ( ( Fin n → F ) × Ω_est × F ) => p.2.1 p.1 from ?_ ) ( show Measurable fun p : ( Fin n → F ) × Ω_est × F => ( nn_index_canonical n p.1 p.2.2 ( ψhat r p.2.1 ), p ) from ?_ ) using 1;
          · exact?;
          · exact Measurable.prodMk h_index_meas measurable_id;
        exact Measurable.pow_const ( h_ref_meas.sub ( hy_meas.comp measurable_snd.snd ) ) _;
      have h_int_meas : ∀ {g : (Fin n → F) × Ω_est × F → ℝ}, Measurable g → Measurable (fun p : (Fin n → F) × Ω_est => ∫ f : F, g (p.1, p.2, f) ∂Pf) := by
        intro g hg;
        apply_rules [ MeasureTheory.StronglyMeasurable.measurable, hg ];
        apply_rules [ MeasureTheory.StronglyMeasurable.integral_prod_right ];
        exact hg.stronglyMeasurable.comp_measurable ( measurable_fst.fst.prodMk ( measurable_fst.snd.prodMk measurable_snd ) );
      convert h_int_meas h_integrand_meas using 1;
      simp +decide [ nn_predictor_canonical_safe ];
      simp +decide [ hn.out ];
    · simp +decide [ nn_predictor_canonical_safe, hn ];
      cases n <;> simp_all +decide [ NeZero ];
      exact False.elim <| hn <| NeZero.of_gt <| Nat.succ_pos _

/-
For any c and δ, if r is large enough, the probability (under the joint measure) that the estimated perspectives are within distance c of the true perspectives is at least 1 - δ.
This follows from the DKPS concentration hypothesis by choosing a small enough error parameter (min(c, δ)) and lifting the probability bound to the joint measure.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The concentration event holds with high probability under the joint measure for large r.
-/
lemma prob_concentration_joint
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d))
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (n : ℕ) (c δ : ℝ) (hc : 0 < c) (hδ : 0 < δ) :
  ∃ R, ∀ r ≥ R,
    let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    μ_joint { x | Event_Concentration ψ (ψhat r x.2.2) n x.1 x.2.1 c } ≥ ENNReal.ofReal (1 - δ) := by
      have := exists_R_concentration Pf ψ P_est ψhat h_conc n ( Min.min c δ );
      refine' Exists.elim ( this ( lt_min hc hδ ) ) fun R hR => ⟨ R, fun r hr => le_trans _ ( hR r hr |> le_trans <| MeasureTheory.measure_mono _ ) ⟩;
      · exact ENNReal.ofReal_le_ofReal ( sub_le_sub_left ( min_le_right _ _ ) _ );
      · exact fun x hx => ⟨ fun i => le_trans ( hx.1 i ) ( min_le_left _ _ ), le_trans ( hx.2 ) ( min_le_left _ _ ) ⟩

/-
The set of tuples (references, target, estimation randomness) that satisfy the concentration condition is measurable.
The concentration condition is a finite conjunction of distance inequalities involving measurable functions.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The concentration event is a measurable set in the product space of references, target, and estimation randomness.
-/
lemma measurable_set_event_concentration
  {F : Type*} [MeasurableSpace F]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (n r : ℕ) (c : ℝ) :
  MeasurableSet { x : (Fin n → F) × F × Ω_est | Event_Concentration ψ (ψhat r x.2.2) n x.1 x.2.1 c } := by
    convert MeasurableSet.inter ?_ ?_ using 1;
    · convert MeasurableSet.iInter fun i => measurableSet_le ( show Measurable fun x : ( Fin n → F ) × ( F × Ω_est ) => dist ( ψhat r x.2.2 ( x.1 i ) ) ( ψ ( x.1 i ) ) from ?_ ) measurable_const using 1;
      rotate_right;
      exact fun _ => c;
      · aesop;
      · fun_prop (disch := solve_by_elim);
    · convert measurableSet_le ( show Measurable fun x : ( Fin n → F ) × F × Ω_est => dist ( ψhat r x.2.2 x.2.1 ) ( ψ x.2.1 ) from ?_ ) measurable_const using 1;
      fun_prop

/-
The set of reference models and target model such that there exists a reference model close to the target is measurable.
This is a finite union of measurable sets defined by distance inequalities.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The set of (refs, target) satisfying Event_GoodRef is measurable.
-/
lemma measurable_set_event_good_ref_base
  {F : Type*} [MeasurableSpace F]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  (n : ℕ) (ε' : ℝ) :
  MeasurableSet { p : (Fin n → F) × F | Event_GoodRef ψ n p.1 p.2 ε' } := by
    unfold Event_GoodRef;
    simp +decide only [Set.setOf_exists];
    refine' MeasurableSet.iUnion fun i => _;
    refine' measurableSet_le _ _;
    · fun_prop;
    · exact measurable_const

/-
The set of (reference models, target model, estimation randomness) such that there exists a reference model close to the target is measurable.
This event depends only on the models, not on the estimation randomness, and is the preimage of a measurable set under a measurable projection.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The set of (refs, target, omega) satisfying Event_GoodRef is measurable.
-/
lemma measurable_set_event_good_ref_joint
  {F : Type*} [MeasurableSpace F]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (n : ℕ) (ε' : ℝ) :
  MeasurableSet { x : (Fin n → F) × F × Ω_est | Event_GoodRef ψ n x.1 x.2.1 ε' } := by
    convert measurable_set_event_good_ref_base ψ hψ n ε' |> MeasurableSet.preimage <| measurable_fst.prodMk measurable_snd.fst using 1

/-
The probability of the "Good Reference" event (which depends only on the reference models and the target model) is the same under the joint distribution (including estimation randomness) as it is under the marginal distribution of the models. This is a standard property of product measures for cylinder sets.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The probability of Event_GoodRef on the joint space is the same as on the base space.
-/
lemma prob_event_good_ref_lift
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (n : ℕ) (ε' : ℝ) :
  let μ_base := (Measure.pi (fun _ : Fin n => Pf)).prod Pf
  let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  μ_joint { x | Event_GoodRef ψ n x.1 x.2.1 ε' } = μ_base { p | Event_GoodRef ψ n p.1 p.2 ε' } := by
    -- Apply the definition of the product measure.
    apply prob_good_refs_lift;
    exact hψ

/-
For any ε', c, and δ, if n and r are large enough, the probability that both a good reference exists and the estimated perspectives are concentrated is at least 1 - δ.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
The joint good event: both good reference exists and concentration holds.
-/
def JointGoodEvent
  {F : Type*} {d : ℕ}
  (ψ : F → EuclideanSpace ℝ (Fin d))
  (ψhat : F → EuclideanSpace ℝ (Fin d))
  (n : ℕ) (refs : Fin n → F) (target : F)
  (ε' c : ℝ) : Prop :=
  Event_GoodRef ψ n refs target ε' ∧ Event_Concentration ψ ψhat n refs target c

/--
Lemma: The probability of the joint good event is high for large n and r.
-/
lemma prob_JointGoodEvent_high
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ)
  (ε' c δ : ℝ) (hε' : 0 < ε') (hc : 0 < c) (hδ : 0 < δ) :
  ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    μ_joint { x | JointGoodEvent ψ (ψhat r x.2.2) n x.1 x.2.1 ε' c } ≥ ENNReal.ofReal (1 - δ) := by
      -- By Lemma `prob_Event_GoodRef_high`, there exists `N` such that for `n ≥ N`, `P_joint(GoodRef) ≥ 1 - δ / 2`.
      obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N,
        let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
        μ_joint { x | Event_GoodRef ψ n x.1 x.2.1 ε' } ≥ ENNReal.ofReal (1 - δ / 2) := by
          have := prob_event_good_ref_lift Pf ψ hψ P_est;
          convert prob_Event_GoodRef_high Pf ψ hψ h_dense ε' hε' ( δ / 2 ) ( half_pos hδ ) using 1;
          aesop;
      refine' ⟨ N, fun n hn => _ ⟩;
      -- By Lemma `prob_concentration_joint`, there exists `R` such that for `r ≥ R`, `P_joint(Concentration) ≥ 1 - δ / 2`.
      obtain ⟨R, hR⟩ : ∃ R, ∀ r ≥ R,
        let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
        μ_joint { x | Event_Concentration ψ (ψhat r x.2.2) n x.1 x.2.1 c } ≥ ENNReal.ofReal (1 - δ / 2) := by
          convert prob_concentration_joint Pf ψ P_est ψhat h_conc n c ( δ / 2 ) hc ( half_pos hδ ) using 1;
      refine' ⟨ R, fun r hr => _ ⟩;
      have := prob_inter_bound ( ( Measure.pi fun _ : Fin n => Pf ).prod ( Pf.prod P_est ) ) ( measurable_set_event_good_ref_joint ψ hψ n ε' ) ( measurable_set_event_concentration ψ hψ ( ψhat ) ( h_ψhat_meas ) n r c ) ( δ / 2 ) ( δ / 2 ) ?_ ?_ ?_ ?_ <;> norm_num at *;
      · by_cases hδ' : δ ≤ 1 <;> simp_all +decide [ JointGoodEvent ];
        · exact this;
        · rw [ ENNReal.ofReal_eq_zero.mpr ( by linarith ) ] ; norm_num;
      · exact hN n hn;
      · exact hR r hr;
      · positivity;
      · positivity

/-
Definition of the squared error function and a lemma stating its joint measurability.
This is needed to integrate it over the joint distribution.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Squared error function for the canonical predictor.
-/
noncomputable def SquaredError
  {F : Type*} {d : ℕ}
  (n : ℕ) (refs : Fin n → F) (target : F)
  (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ) : ℝ :=
  (nn_predictor_canonical_safe n refs target ψhat y - y target)^2

/--
Lemma: SquaredError is measurable.
-/
lemma measurable_squared_error
  {F : Type*} [MeasurableSpace F]
  {d : ℕ}
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y)
  (n r : ℕ) :
  Measurable (fun x : (Fin n → F) × F × Ω_est => SquaredError n x.1 x.2.1 (ψhat r x.2.2) y) := by
    by_cases hn : NeZero n <;> simp_all +decide [ SquaredError ];
    · refine' Measurable.pow_const _ _;
      refine' Measurable.sub _ _;
      · unfold nn_predictor_canonical_safe;
        have h_measurable_index : Measurable (fun x : (Fin n → F) × F × Ω_est => nn_index_canonical n x.1 x.2.1 (ψhat r x.2.2)) := by
          exact?;
        have h_measurable_y : Measurable (fun x : (Fin n → F) × F × Ω_est => y (x.1 (nn_index_canonical n x.1 x.2.1 (ψhat r x.2.2)))) := by
          have h_measurable_y : ∀ i : Fin n, Measurable (fun x : (Fin n → F) × F × Ω_est => y (x.1 i)) := by
            exact fun i => hy_meas.comp ( measurable_pi_apply i |> Measurable.comp <| measurable_fst );
          have h_measurable_y : Measurable (fun x : (Fin n → F) × F × Ω_est => ∑ i : Fin n, (if i = nn_index_canonical n x.1 x.2.1 (ψhat r x.2.2) then y (x.1 i) else 0)) := by
            refine' Finset.measurable_sum _ fun i _ => _;
            exact Measurable.ite ( measurableSet_eq_fun measurable_const h_measurable_index ) ( h_measurable_y i ) measurable_const;
          convert h_measurable_y using 1;
          ext x; simp +decide [ Finset.sum_ite, Finset.filter_eq', Finset.filter_ne' ] ;
        aesop;
      · exact hy_meas.comp ( measurable_snd.fst );
    · rw [ show n = 0 by exact Nat.eq_zero_of_not_pos fun h => hn <| NeZero.of_gt h ] ; norm_num [ nn_predictor_canonical_safe ] ; fun_prop (disch := solve_by_elim)

/-
If the joint good event holds (good reference exists and concentration holds), then the squared error of the canonical predictor is bounded by (γ * (4c + ε'))^2.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: If the joint good event holds, the squared error is bounded.
-/
lemma squared_error_bound_on_event
  {F : Type*} {d : ℕ}
  (n : ℕ) [NeZero n] (refs : Fin n → F) (target : F)
  (ψ : F → EuclideanSpace ℝ (Fin d)) (ψhat : F → EuclideanSpace ℝ (Fin d))
  (y : F → ℝ)
  (c ε' γ : ℝ)
  (h_nonneg_γ : 0 ≤ γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_event : JointGoodEvent ψ ψhat n refs target ε' c) :
  SquaredError n refs target ψhat y ≤ (γ * (4 * c + ε'))^2 := by
    unfold SquaredError;
    convert pow_le_pow_left₀ ( abs_nonneg _ ) ( show |nn_predictor_canonical n refs target ψhat y - y target| ≤ γ * ( 4 * c + ε' ) from ?_ ) 2 using 1;
    · unfold nn_predictor_canonical_safe; split_ifs <;> simp +decide [ * ] ;
      exact absurd ‹_› ( NeZero.ne n );
    · apply deterministic_error_bound_canonical;
      any_goals tauto;
      · exact h_event.2.1;
      · exact h_event.2.2;
      · exact h_event.1

/-
The squared error of the canonical predictor is always at most 4, given that the score function y takes values in [-1, 1].
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The squared error is globally bounded by 4.
-/
lemma squared_error_global_bound
  {F : Type*} {d : ℕ}
  (n : ℕ) (refs : Fin n → F) (target : F)
  (ψhat : F → EuclideanSpace ℝ (Fin d)) (y : F → ℝ)
  (hy_bound : ∀ f, |y f| ≤ 1) :
  SquaredError n refs target ψhat y ≤ 4 := by
    unfold SquaredError;
    rcases n with ( _ | n );
    · unfold nn_predictor_canonical_safe; norm_num; nlinarith [ abs_le.mp ( hy_bound target ) ] ;
    · unfold nn_predictor_canonical_safe;
      unfold nn_predictor_canonical;
      norm_num +zetaDelta at *;
      nlinarith [ abs_le.mp ( hy_bound ( refs ( nn_index_canonical ( n + 1 ) refs target ψhat ) ) ), abs_le.mp ( hy_bound target ) ]

/-
The expected MSE (integral over references and estimation randomness) is equal to the expected squared error (integral over references, target, and estimation randomness). This allows us to bound the MSE by bounding the joint squared error.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The expected MSE over training data equals the expected squared error over the joint distribution.
-/
lemma expected_mse_eq_joint_expectation
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ}
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (n r : ℕ) :
  let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
  let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
  ∫ p, MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ∂μ_train =
  ∫ x, SquaredError n x.1 x.2.1 (ψhat r x.2.2) y ∂μ_joint := by
    simp +decide [ SquaredError, MSE_DKPS_canonical ];
    erw [ MeasureTheory.integral_prod ];
    · erw [ MeasureTheory.integral_prod ];
      · congr! 2;
        erw [ MeasureTheory.integral_prod_symm ];
        refine' MeasureTheory.Integrable.mono' _ _ _;
        refine' fun p => 4;
        · norm_num;
        · refine' Measurable.aestronglyMeasurable _;
          have h_measurable : Measurable (fun p : (Fin n → F) × F × Ω_est => SquaredError n p.1 p.2.1 (ψhat r p.2.2) y) := by
            exact?;
          exact h_measurable.comp ( measurable_const.prodMk measurable_id' );
        · refine' Filter.Eventually.of_forall fun p => _;
          simp +zetaDelta at *;
          exact le_trans ( squared_error_global_bound _ _ _ _ _ hy_bound ) ( by norm_num );
      · refine' MeasureTheory.Integrable.mono' _ _ _;
        refine' fun x => 4;
        · simp +decide [ MeasureTheory.integrable_const_iff ];
        · refine' Measurable.aestronglyMeasurable _;
          exact?;
        · simp +zetaDelta at *;
          exact Filter.Eventually.of_forall fun x => squared_error_global_bound n x.1 x.2.1 ( ψhat r x.2.2 ) y hy_bound;
    · refine' MeasureTheory.Integrable.mono' _ _ _;
      refine' fun p => 4;
      · simp +decide [ MeasureTheory.integrable_const_iff ];
      · refine' Measurable.aestronglyMeasurable _;
        exact?;
      · refine' Filter.Eventually.of_forall fun p => _;
        refine' le_trans ( MeasureTheory.norm_integral_le_integral_norm _ ) ( le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _ );
        refine' fun _ => 4;
        · exact Filter.Eventually.of_forall fun _ => norm_nonneg _;
        · norm_num;
        · filter_upwards [ ] with x using by simpa using squared_error_global_bound n p.1 x ( ψhat r p.2 ) y hy_bound;
        · norm_num

open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Theorem: The MSE of the canonical DKPS predictor can be made arbitrarily small with high probability over the training data.
-/
theorem dkps_mse_convergence_canonical
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ ε > 0, ∀ η > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
    μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ≤ ε } ≥ ENNReal.ofReal (1 - η) := by
      intro ε ε_pos η η_pos
      set target_E := ε * η with htarget_E
      set ε_sq := target_E / 2 with hε_sq
      set δ := target_E / 8 with hδ
      set K := Real.sqrt ε_sq with hK
      set ε' := K / (2 * γ) with hε'
      set c := K / (8 * γ) with hc;
      obtain ⟨N, hN⟩ : ∃ N : ℕ, ∀ n ≥ N, ∃ R : ℕ, ∀ r ≥ R, let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est); μ_joint { x : (Fin n → F) × F × Ω_est | JointGoodEvent ψ (ψhat r x.2.2) n x.1 x.2.1 ε' c } ≥ ENNReal.ofReal (1 - δ) := by
        apply_rules [ prob_JointGoodEvent_high ];
        · exact div_pos ( Real.sqrt_pos.mpr ( div_pos ( mul_pos ε_pos η_pos ) zero_lt_two ) ) ( mul_pos zero_lt_two hγ );
        · exact div_pos ( Real.sqrt_pos.mpr ( by positivity ) ) ( by positivity );
        · positivity;
      -- For n ≥ N and r ≥ R, we have E[MSE] ≤ target_E.
      have h_exp_mse : ∀ n ≥ N, ∃ R : ℕ, ∀ r ≥ R, ∫ p : (Fin n → F) × Ω_est, MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ∂(Measure.pi (fun _ : Fin n => Pf)).prod P_est ≤ target_E := by
        intro n hn
        obtain ⟨R, hR⟩ := hN n hn
        use R
        intro r hr
        have h_exp_mse : ∫ p : (Fin n → F) × F × Ω_est, SquaredError n p.1 p.2.1 (ψhat r p.2.2) y ∂(Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est) ≤ ε_sq + 4 * δ := by
          apply_rules [ expectation_bound_of_high_prob_bound ];
          any_goals positivity;
          · apply_rules [ measurable_squared_error ];
          · exact Filter.Eventually.of_forall fun x => ⟨ sq_nonneg _, squared_error_global_bound n x.1 x.2.1 ( ψhat r x.2.2 ) y hy_bound ⟩;
          · refine' le_trans ( hR r hr ) ( MeasureTheory.measure_mono _ );
            intro x hx
            obtain ⟨h_good_ref, h_conc⟩ := hx
            have h_sq_error : SquaredError n x.1 x.2.1 (ψhat r x.2.2) y ≤ (γ * (4 * c + ε'))^2 := by
              by_cases hn : n = 0;
              · unfold Event_GoodRef at h_good_ref; aesop;
              · convert squared_error_bound_on_event n x.1 x.2.1 ψ ( ψhat r x.2.2 ) y c ε' γ ( by positivity ) h_lip ⟨ h_good_ref, h_conc ⟩ using 1;
                exact ⟨ hn ⟩;
            simp +zetaDelta at *;
            convert h_sq_error using 1 ; ring ; norm_num [ hγ.ne', ε_pos.ne', η_pos.ne' ] ; ring;
            field_simp
            ring;
            rw [ Real.sq_sqrt ( mul_nonneg ε_pos.le η_pos.le ) ];
        convert h_exp_mse using 1;
        · exact?;
        · ring;
      refine' ⟨ N, fun n hn => _ ⟩;
      obtain ⟨ R, hR ⟩ := h_exp_mse n hn;
      use R;
      intro r hr;
      have h_markov : ∫ p : (Fin n → F) × Ω_est, MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ∂(Measure.pi (fun _ : Fin n => Pf)).prod P_est ≥ ∫ p : (Fin n → F) × Ω_est in { p : (Fin n → F) × Ω_est | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) > ε }, ε ∂(Measure.pi (fun _ : Fin n => Pf)).prod P_est := by
        rw [ ← MeasureTheory.integral_indicator ] <;> norm_num [ Set.indicator ];
        · refine' MeasureTheory.integral_mono_of_nonneg _ _ _;
          · exact Filter.Eventually.of_forall fun x => by positivity;
          · refine' MeasureTheory.Integrable.mono' _ _ _;
            use fun p => 4;
            · fun_prop;
            · exact Measurable.aestronglyMeasurable ( measurable_mse_dkps_canonical Pf ψhat h_ψhat_meas y hy_meas hy_bound n r );
            · refine' Filter.Eventually.of_forall fun p => _;
              rw [ Real.norm_of_nonneg ];
              · refine' le_trans ( MeasureTheory.integral_mono_of_nonneg _ _ _ ) _;
                use fun f => 4;
                · exact Filter.Eventually.of_forall fun _ => sq_nonneg _;
                · norm_num;
                · filter_upwards [ ] with f using by nlinarith only [ abs_le.mp ( hy_bound f ), abs_le.mp ( show |nn_predictor_canonical_safe n p.1 f ( ψhat r p.2 ) y| ≤ 1 from by
                                                                                                              unfold nn_predictor_canonical_safe; aesop; ) ] ;
                · norm_num;
              · exact MeasureTheory.integral_nonneg fun _ => sq_nonneg _;
          · filter_upwards [ ] with p using by split_ifs <;> linarith [ show 0 ≤ MSE_DKPS_canonical Pf n p.1 y ( ψhat r p.2 ) from MeasureTheory.integral_nonneg fun _ => sq_nonneg _ ] ;
        · have h_meas : Measurable (fun p : (Fin n → F) × Ω_est => MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2)) := by
            apply_rules [ measurable_mse_dkps_canonical ];
          exact measurableSet_Ioi.mem.comp h_meas;
      simp_all +decide [ MeasureTheory.measureReal_def ];
      rw [ show { p : ( Fin n → F ) × Ω_est | MSE_DKPS_canonical Pf n p.1 y ( ψhat r p.2 ) ≤ ε } = ( Set.univ \ { p : ( Fin n → F ) × Ω_est | ε < MSE_DKPS_canonical Pf n p.1 y ( ψhat r p.2 ) } ) by ext; simp +decide, MeasureTheory.measure_diff ] <;> norm_num;
      · rw [ ENNReal.ofReal_le_iff_le_toReal ] <;> norm_num;
        rw [ ENNReal.toReal_sub_of_le ] <;> norm_num;
        · nlinarith [ hR r hr, show 0 ≤ ( ( Measure.pi fun x => Pf ).prod P_est { p : ( Fin n → F ) × Ω_est | ε < MSE_DKPS_canonical Pf n p.1 y ( ψhat r p.2 ) } ).toReal by positivity ];
        · exact le_trans ( MeasureTheory.measure_mono ( Set.subset_univ _ ) ) ( by simp +decide [ MeasureTheory.IsProbabilityMeasure.measure_univ ] );
      · exact measurableSet_lt measurable_const ( measurable_mse_dkps_canonical Pf ψhat h_ψhat_meas y hy_meas hy_bound n r ) |> MeasurableSet.nullMeasurableSet

/-
The set of tuples (references, target, estimation randomness) satisfying the JointGoodEvent condition is measurable. This follows because it is the intersection of two measurable sets: the GoodRef event and the Concentration event.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The joint good event is measurable.
-/
lemma measurable_set_joint_good_event
  {F : Type*} [MeasurableSpace F]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (n r : ℕ) (ε' c : ℝ) :
  MeasurableSet { x : (Fin n → F) × F × Ω_est | JointGoodEvent ψ (ψhat r x.2.2) n x.1 x.2.1 ε' c } := by
    apply_rules [ MeasurableSet.inter, MeasurableSet.iUnion ];
    · convert measurable_set_event_good_ref_joint ψ hψ n ε' using 1;
    · convert MeasurableSet.iInter fun i => measurableSet_le ( show Measurable fun x : ( Fin n → F ) × ( F × Ω_est ) => dist ( ψhat r x.2.2 ( x.1 i ) ) ( ψ ( x.1 i ) ) from ?_ ) measurable_const using 1;
      rotate_right;
      exact fun _ => c;
      · aesop;
      · fun_prop;
    · have h_meas : Measurable (fun x : (Fin n → F) × F × Ω_est => dist (ψhat r x.2.2 x.2.1) (ψ x.2.1)) := by
        fun_prop;
      exact measurableSet_le h_meas measurable_const

/-
For any target expected error > 0, there exist N and R such that for n ≥ N and r ≥ R, the expected squared error of the canonical predictor is at most the target error.
This is proved by bounding the squared error on a high-probability "good" event and using the global bound on the "bad" event.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Lemma: The expected squared error of the canonical predictor can be made arbitrarily small.
-/
lemma expected_squared_error_convergence
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ target_E > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est)
    ∫ x, SquaredError n x.1 x.2.1 (ψhat r x.2.2) y ∂μ_joint ≤ target_E := by
      intro target_E htarget_E_pos
      obtain ⟨ε_sq, hε_sq⟩ : ∃ ε_sq > 0, ε_sq < target_E / 2 := by
        exact exists_between ( half_pos htarget_E_pos )
      obtain ⟨δ, hδ⟩ : ∃ δ > 0, δ < target_E / 8 := by
        exact exists_between ( by linarith )
      obtain ⟨K, hK⟩ : ∃ K > 0, K = Real.sqrt ε_sq := by
        exact ⟨ Real.sqrt ε_sq, Real.sqrt_pos.2 hε_sq.1, rfl ⟩
      obtain ⟨ε', hε'⟩ : ∃ ε' > 0, ε' = K / (2 * γ) := by
        exact ⟨ K / ( 2 * γ ), div_pos hK.1 ( mul_pos zero_lt_two hγ ), rfl ⟩
      obtain ⟨c, hc⟩ : ∃ c > 0, c = K / (8 * γ) := by
        exact ⟨ K / ( 8 * γ ), div_pos hK.1 ( mul_pos ( by norm_num ) hγ ), rfl ⟩
      obtain ⟨N, hN⟩ : ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R, let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est); μ_joint { x | JointGoodEvent ψ (ψhat r x.2.2) n x.1 x.2.1 ε' c } ≥ ENNReal.ofReal (1 - δ) := by
        apply prob_JointGoodEvent_high Pf ψ hψ P_est ψhat h_ψhat_meas h_conc h_dense ε' c δ hε'.1 hc.1 hδ.1 |> fun ⟨N, hN⟩ => ⟨N, fun n hn => hN n hn⟩;
      use N + 1;
      intro n hn
      obtain ⟨R, hR⟩ := hN n (by linarith)
      use R
      intro r hr
      have h_prob : let μ_joint := (Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est); μ_joint { x | SquaredError n x.1 x.2.1 (ψhat r x.2.2) y ≤ ε_sq } ≥ ENNReal.ofReal (1 - δ) := by
        refine' le_trans ( hR r hr ) ( MeasureTheory.measure_mono _ );
        intro x hx;
        convert squared_error_bound_on_event n x.1 x.2.1 ψ ( ψhat r x.2.2 ) y c ε' γ ( by linarith ) h_lip hx using 1;
        · rw [ hc.2, hε'.2 ] ; ring;
          simp +decide [ mul_assoc, mul_comm, mul_left_comm, hγ.ne', hK.2, Real.sq_sqrt hε_sq.1.le ];
        · exact ⟨ by linarith ⟩;
      have h_exp_bound : ∫ x, SquaredError n x.1 x.2.1 (ψhat r x.2.2) y ∂(Measure.pi (fun _ : Fin n => Pf)).prod (Pf.prod P_est) ≤ ε_sq + 4 * δ := by
        apply_rules [ expectation_bound_of_high_prob_bound ];
        · apply_rules [ measurable_squared_error ];
        · norm_num;
        · exact Filter.Eventually.of_forall fun x => ⟨ sq_nonneg _, squared_error_global_bound n x.1 x.2.1 ( ψhat r x.2.2 ) y hy_bound ⟩;
        · linarith;
        · linarith;
      linarith

/-
Theorem: For any ε > 0 and η > 0, there exist N and R such that for n ≥ N and r ≥ R, the MSE of the canonical DKPS predictor is at most ε with probability at least 1 - η.
This is proved by bounding the expected MSE (using `expected_squared_error_convergence`) and applying Markov's inequality.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Theorem: The MSE of the canonical DKPS predictor can be made arbitrarily small with high probability over the training data.
-/
theorem dkps_mse_convergence_canonical_thm
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ ε > 0, ∀ η > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
    μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ≤ ε } ≥ ENNReal.ofReal (1 - η) := by
      -- Apply the theorem `dkps_mse_convergence_canonical` with the given ε and η.
      apply dkps_mse_convergence_canonical Pf ψ hψ P_est ψhat h_ψhat_meas y hy_meas hy_bound γ hγ h_lip h_conc h_dense

/-
Theorem: For any ε > 0 and η > 0, there exist N and R such that for n ≥ N and r ≥ R, the MSE of the canonical DKPS predictor is at most ε with probability at least 1 - η.
This is proved by bounding the expected MSE (using `expected_squared_error_convergence`) and applying Markov's inequality.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Theorem: The MSE of the canonical DKPS predictor can be made arbitrarily small with high probability over the training data.
-/
theorem dkps_mse_convergence_canonical_v2
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ) :
  ∀ ε > 0, ∀ η > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
    μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ≤ ε } ≥ ENNReal.ofReal (1 - η) := by
      -- Apply the lemma `dkps_mse_convergence_canonical` with the given parameters.
      apply dkps_mse_convergence_canonical;
      all_goals assumption

/-
Checking if the theorem `dkps_mse_convergence_canonical` is already defined.
-/
#check dkps_mse_convergence_canonical

/-
If the baseline MSE is positive, then for sufficiently large n and r, the DKPS MSE is strictly less than the baseline MSE with high probability.
This follows from the fact that the DKPS MSE converges to 0 (in probability), so it eventually becomes smaller than any positive constant.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Main Theorem (Query-efficiency via DKPS nearest neighbor):
If the baseline subset-score estimator has strictly positive MSE, then for sufficiently large n and r,
the DKPS nearest-neighbor predictor achieves strictly smaller MSE with high probability over the training data.
-/
theorem quench_query_efficiency
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (yQ : F → ℝ) (hyQ_meas : Measurable yQ)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ)
  (h_baseline_pos : MSE_baseline Pf yQ y > 0) :
  ∀ η > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
    μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) < MSE_baseline Pf yQ y } ≥ ENNReal.ofReal (1 - η) := by
      intro η hη_pos
      obtain ⟨ N, hN ⟩ : ∃ N : ℕ, ∀ n ≥ N, ∃ R : ℕ, ∀ r ≥ R,
        let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est;
        μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) ≤ MSE_baseline Pf yQ y / 2 } ≥ ENNReal.ofReal (1 - η) := by
          convert dkps_mse_convergence_canonical Pf ψ hψ P_est ψhat h_ψhat_meas y hy_meas hy_bound γ hγ h_lip h_conc h_dense ( MSE_baseline Pf yQ y / 2 ) ( half_pos h_baseline_pos ) η hη_pos using 1
      generalize_proofs at *; (
      exact ⟨ N, fun n hn => by obtain ⟨ R, hR ⟩ := hN n hn; exact ⟨ R, fun r hr => le_trans ( hR r hr ) ( MeasureTheory.measure_mono fun p hp => lt_of_le_of_lt hp.out ( half_lt_self h_baseline_pos ) ) ⟩ ⟩)

/-
Checking the existence of the main theorems.
-/
#check dkps_mse_convergence_canonical
#check dkps_mse_convergence_canonical_v2
#check quench_query_efficiency

/-
If the baseline MSE is positive, then for sufficiently large n and r, the DKPS MSE is strictly less than the baseline MSE with high probability.
This follows from the fact that the DKPS MSE converges to 0 (in probability), so it eventually becomes smaller than any positive constant.
-/
open Metric MeasureTheory ProbabilityTheory Filter Topology

/--
Main Theorem (Query-efficiency via DKPS nearest neighbor):
If the baseline subset-score estimator has strictly positive MSE, then for sufficiently large n and r,
the DKPS nearest-neighbor predictor achieves strictly smaller MSE with high probability over the training data.
-/
theorem quench_query_efficiency_thm
  {F : Type*} [MeasurableSpace F] (Pf : Measure F) [IsProbabilityMeasure Pf]
  {d : ℕ} (ψ : F → EuclideanSpace ℝ (Fin d)) (hψ : Measurable ψ)
  {Ω_est : Type*} [MeasurableSpace Ω_est] (P_est : Measure Ω_est) [IsProbabilityMeasure P_est]
  (ψhat : ℕ → Ω_est → F → EuclideanSpace ℝ (Fin d))
  (h_ψhat_meas : ∀ r, Measurable (fun p : Ω_est × F => ψhat r p.1 p.2))
  (y : F → ℝ) (hy_meas : Measurable y) (hy_bound : ∀ f, |y f| ≤ 1)
  (yQ : F → ℝ) (hyQ_meas : Measurable yQ)
  (γ : ℝ) (hγ : 0 < γ)
  (h_lip : ∀ f f', |y f - y f'| ≤ γ * dist (ψ f) (ψ f'))
  (h_conc : DKPS_concentration_hypothesis ψ Ω_est P_est ψhat)
  (h_dense : Model_distribution_denseness Pf ψ)
  (h_baseline_pos : MSE_baseline Pf yQ y > 0) :
  ∀ η > 0, ∃ N, ∀ n ≥ N, ∃ R, ∀ r ≥ R,
    let μ_train := (Measure.pi (fun _ : Fin n => Pf)).prod P_est
    μ_train { p | MSE_DKPS_canonical Pf n p.1 y (ψhat r p.2) < MSE_baseline Pf yQ y } ≥ ENNReal.ofReal (1 - η) := by
      exact?
