/-
# Spectral perturbation challenge solution file
-/

import ForMathlib.Analysis.InnerProductSpace.Spectrum
import ForMathlib.Analysis.InnerProductSpace.CourantFischer
import ForMathlib.Analysis.InnerProductSpace.DavisKahan

#print axioms ForMathlib.inner_eigenvectorBasis_map_sub_eigenvectorBasis
#print axioms ForMathlib.re_inner_map_self_eq_sum_eigenvalues_mul_sq
#print axioms ForMathlib.exists_unit_vector_re_inner_le_eigenvalue
#print axioms ForMathlib.forall_unit_vector_eigenvalue_le_re_inner
#print axioms ForMathlib.abs_eigenvalues_sub_le
#print axioms ForMathlib.sum_norm_inner_eigenvectorBasis_map_sub_sq_le
#print axioms ForMathlib.sum_cross_norm_inner_eigenvectorBasis_sq_le
#print axioms ForMathlib.gap_of_rank_floor
#print axioms ForMathlib.sum_cross_norm_inner_eigenvectorBasis_sq_le_of_rank_floor
